### ISSUE TITLE
within-time-node drops an internal error on an not selected day

### ISSUE THREAD

**Issue by baderas** [rdmtc/node-red-contrib-sun-position#100]
**Describe the bug**
within-time-node drops an internal error within-time-switch:Error can not calc time when on a day that is not an included day

**To Reproduce**
Create an within-time-node with a given start and end time, check mo-fri and let saturday and sunday out. On saturday, a internal error within-time-switch:Error can not calc time drops.
On saturday - before the first message - "day is not selected" appears (expected behaviour). After the first message, the error above occurs and the flow stopps.

**Expected behavior**
day is not selected appears and the flow does not abort due to an error.

**Screenshots**
![image](https://user-images.githubusercontent.com/13378513/73120906-0e7c3a00-3f74-11ea-94b0-1c3ac9e80c8a.png)

**System information (please complete the following information):**
 - Plugin Version 1.0.3
 - Node-Red Version 1.0.3
 - Hardware Docker on Raspberry Pi 3

**Comment by Hypnos3** [comment]
Hello, my family is currently suffering from a cold, which is why I can't get a look at it.  As soon as that is over, I will look at it.

**Comment by Hypnos3** [comment]
This should be fixed with the new Version 1.0.4
