### ISSUE TITLE
Rule of clock-timer does not match on end of the day

### ISSUE THREAD

**Issue by hasenbolle** [rdmtc/node-red-contrib-sun-position#102]
**Describe the bug**
The clock timer with from date civilDusk and untilDate civilSet as the two rules, does not match the rule from date civilDusk if the time is around 23:23. A short debug shows me that the rule gets the day of tomorrow on validation, which is at that time not correct.

**To Reproduce**
1. Use this flow
`[{"id":"b3d46b12.0cd328","type":"debug","z":"fa2cb05e.65849","name":"","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"true","targetType":"full","x":870,"y":880,"wires":[]},{"id":"232b5b83.34cc84","type":"clock-timer","z":"fa2cb05e.65849","name":"","topic":"","positionConfig":"873fdd2c.6a528","outputs":2,"autoTrigger":false,"autoTriggerTime":1200000,"storeName":"","overwriteExpire":"","rules":[{"index":0,"name":"","isValid":false,"valid":{},"timeValue":"sunriseEnd","timeType":"pdsTime","timeOp":0,"timeOpText":"↥ bis","offsetValue":"","offsetType":"none","multiplier":60000,"timeDays":"*","timeMonths":"*","timeOnlyEvenDays":false,"timeOnlyOddDays":false,"timeMinValue":"","timeMinType":"none","offsetMinValue":"","offsetMinType":"none","multiplierMin":60000,"timeMaxValue":"","timeMaxType":"none","offsetMaxValue":"","offsetMaxType":"none","multiplierMax":60000,"payloadValue":"true","payloadType":"bool","payloadOffsetValue":"","payloadOffsetType":"none","payloadOffsetMultiplier":60000,"payloadFormat":99,"topic":"","validOperandAValue":"","validOperandAType":"none","validOperator":"true","validOperatorText":"ist true","validOperandBValue":"","validOperandBType":"num","valid2LogOperator":0,"valid2LogOperatorText":"N/A","valid2OperandAValue":"","valid2OperandAType":"msg","valid2Operator":"true","valid2OperatorText":"ist true","valid2OperandBValue":"","valid2OperandBType":"num","description":"<div><i class=\"fa fa-clock-o\" aria-hidden=\"true\"></i> ↥ bis <var>Sonnenaufgang Ende</var></div><div><div class=\"indent-payload-text\"><i class=\"fa fa-step-backward\" aria-hidden=\"true\"></i> <span>Payload:</span> <var>true</var></div></div>","timeMinOp":0,"timeMaxOp":0},{"index":1,"name":"","isValid":false,"valid":{},"timeValue":"civilDusk","timeType":"pdsTime","timeOp":1,"timeOpText":"↧ von","offsetValue":"","offsetType":"none","multiplier":60000,"timeDays":"*","timeMonths":"*","timeOnlyEvenDays":false,"timeOnlyOddDays":false,"timeMinValue":"","timeMinType":"none","offsetMinValue":"","offsetMinType":"none","multiplierMin":60000,"timeMaxValue":"","timeMaxType":"none","offsetMaxValue":"","offsetMaxType":"none","multiplierMax":60000,"payloadValue":"true","payloadType":"bool","payloadOffsetValue":"","payloadOffsetType":"none","payloadOffsetMultiplier":60000,"payloadFormat":99,"topic":"","validOperandAValue":"","validOperandAType":"none","validOperator":"true","validOperatorText":"ist true","validOperandBValue":"","validOperandBType":"num","valid2LogOperator":0,"valid2LogOperatorText":"N/A","valid2OperandAValue":"","valid2OperandAType":"msg","valid2Operator":"true","valid2OperatorText":"ist true","valid2OperandBValue":"","valid2OperandBType":"num","description":"<div><i class=\"fa fa-clock-o\" aria-hidden=\"true\"></i> ↧ von <var>bürgerliche Abenddämmerung</var></div><div><div class=\"indent-payload-text\"><i class=\"fa fa-step-backward\" aria-hidden=\"true\"></i> <span>Payload:</span> <var>true</var></div></div>","timeMinOp":0,"timeMaxOp":0}],"payloadDefault":"false","payloadDefaultType":"bool","payloadDefaultTimeFormat":0,"payloadDefaultOffset":0,"payloadDefaultOffsetType":"none","payloadDefaultOffsetMultiplier":60000,"x":700,"y":880,"wires":[[],["b3d46b12.0cd328"]]},{"id":"b88757ba.4b66f8","type":"change","z":"fa2cb05e.65849","name":"","rules":[{"t":"set","p":"ts","pt":"msg","to":"payload","tot":"msg"}],"action":"","property":"","from":"","to":"","reg":false,"x":510,"y":880,"wires":[["232b5b83.34cc84"]]},{"id":"b4fe02d0.0a642","type":"inject","z":"fa2cb05e.65849","name":"2323","topic":"","payload":"1582323780000","payloadType":"num","repeat":"","crontab":"","once":false,"onceDelay":0.1,"x":330,"y":880,"wires":[["b88757ba.4b66f8"]]},{"id":"873fdd2c.6a528","type":"position-config","z":"","name":"Home","isValide":"true","longitude":"0","latitude":"0","angleType":"deg","timeZoneOffset":99,"timeZoneDST":0,"stateTimeFormat":"3","stateDateFormat":"12"}]`

2. Start the injection
3. clock-timer does not match any rule

**Expected behavior**
The clock-timer should match with rule 2, because from date civilDusk (Rule 2) is valid with the time 23:23.

**Screenshots**
![image](https://user-images.githubusercontent.com/12832850/75085671-c711ab00-552b-11ea-80e0-bf94285983d4.png)

**System information:**
 - Version 1.0.4
 - Node-Red Version 1.0.3
 - Hardware RaspberryPi 4

Best regards 
Chris

**Comment by Hypnos3** [comment]
I have already seen the error in my productive system. Unfortunately, I haven't been able to re-create it in the development system (maybe it is because it has to be just before midnight).

Therefore, it may take some time before I can investigate this further.

**Comment by hasenbolle** [comment]
If you take my test flow, you can recreate the bug.

**Comment by hasenbolle** [comment]
As a quick and dirty fix for me, i removed following check:

https://github.com/rdmtc/node-red-contrib-sun-position/blob/7acf1d2996ba207fdd0d9dd385f000113484ca4e/nodes/clock-timer.js#L451
to
```js
if (num >=0  && cmp(num)) {
```
This does work. However on the end of the day, the rule "until civilSet" is choosen, which is not correct. But it does nevertheless work for me.

**Comment by Hypnos3** [comment]
I have implemented this in node-red-contrib-sun-position@1.0.6, This is a test release and needs to be installed explicit over command line.

**Comment by hasenbolle** [comment]
Thanks for the quick update. First tests looking good. Awesome work.

**Comment by hasenbolle** [comment]
Ok did a second test with following flow:

`[{"id":"8e941ff6.87598","type":"clock-timer","z":"207f7b57.14eb84","name":"Zeitschaltuhr Licht","topic":"","positionConfig":"873fdd2c.6a528","outputs":1,"autoTrigger":false,"autoTriggerTime":1200000,"startDelayTime":"0","storeName":"","overwriteExpire":"","rules":[{"index":0,"name":"Morgens Dunkel","isValid":false,"valid":{},"timeValue":"blueHourDawnStart","timeType":"pdsTime","timeOp":0,"timeOpText":"↥ bis","offsetValue":"","offsetType":"none","multiplier":60000,"timeDays":"*","timeMonths":"*","timeOnlyEvenDays":false,"timeOnlyOddDays":false,"timeMinValue":"","timeMinType":"none","offsetMinValue":"","offsetMinType":"none","multiplierMin":60000,"timeMaxValue":"","timeMaxType":"none","offsetMaxValue":"","offsetMaxType":"none","multiplierMax":60000,"payloadValue":"true","payloadType":"bool","payloadOffsetValue":"","payloadOffsetType":"none","payloadOffsetMultiplier":60000,"payloadFormat":99,"topic":"","validOperandAValue":"","validOperandAType":"none","validOperator":"true","validOperatorText":"ist true","validOperandBValue":"","validOperandBType":"num","valid2LogOperator":0,"valid2LogOperatorText":"N/A","valid2OperandAValue":"","valid2OperandAType":"msg","valid2Operator":"true","valid2OperatorText":"ist true","valid2OperandBValue":"","valid2OperandBType":"num","description":"<div><i class=\"fa fa-clock-o\" aria-hidden=\"true\"></i> ↥ bis <var>Blaue Morgenstunde Begin</var></div><div><div class=\"indent-payload-text\"><i class=\"fa fa-step-backward\" aria-hidden=\"true\"></i> <span>Payload:</span> <var>true</var></div></div>","timeMinOp":0,"timeMaxOp":0,"timeDateStart":"","timeDateEnd":""},{"index":1,"name":"Abends Dunkel","isValid":false,"valid":{},"timeValue":"sunset","timeType":"pdsTime","timeOp":1,"timeOpText":"↧ von","offsetValue":"","offsetType":"none","multiplier":3600000,"timeDays":"*","timeMonths":"*","timeOnlyEvenDays":false,"timeOnlyOddDays":false,"timeMinValue":"","timeMinType":"none","offsetMinValue":"","offsetMinType":"none","multiplierMin":60000,"timeMaxValue":"","timeMaxType":"none","offsetMaxValue":"","offsetMaxType":"none","multiplierMax":60000,"payloadValue":"true","payloadType":"bool","payloadOffsetValue":"","payloadOffsetType":"none","payloadOffsetMultiplier":3600000,"payloadFormat":99,"topic":"","validOperandAValue":"","validOperandAType":"none","validOperator":"true","validOperatorText":"ist true","validOperandBValue":"","validOperandBType":"num","valid2LogOperator":0,"valid2LogOperatorText":"N/A","valid2OperandAValue":"","valid2OperandAType":"msg","valid2Operator":"true","valid2OperatorText":"ist true","valid2OperandBValue":"","valid2OperandBType":"num","description":"<div><i class=\"fa fa-clock-o\" aria-hidden=\"true\"></i> ↧ von <var>Sonnenuntergang Ende</var></div><div><div class=\"indent-payload-text\"><i class=\"fa fa-step-backward\" aria-hidden=\"true\"></i> <span>Payload:</span> <var>true</var></div></div>","timeDateStart":"","timeDateEnd":"","timeMinOp":0,"timeMaxOp":0}],"payloadDefault":"false","payloadDefaultType":"bool","payloadDefaultTimeFormat":0,"payloadDefaultOffset":0,"payloadDefaultOffsetType":"none","payloadDefaultOffsetMultiplier":60000,"x":520,"y":1340,"wires":[[]]},{"id":"c6cb3f67.282d8","type":"inject","z":"207f7b57.14eb84","name":"","topic":"","payload":"1582415100000","payloadType":"num","repeat":"","crontab":"","once":false,"onceDelay":0.1,"x":120,"y":1340,"wires":[["f962ebb8.c27a88"]]},{"id":"f962ebb8.c27a88","type":"change","z":"207f7b57.14eb84","name":"","rules":[{"t":"set","p":"ts","pt":"msg","to":"payload","tot":"msg"}],"action":"","property":"","from":"","to":"","reg":false,"x":310,"y":1340,"wires":[["8e941ff6.87598"]]},{"id":"873fdd2c.6a528","type":"position-config","z":"","name":"Home","isValide":"true","longitude":"0","latitude":"0","angleType":"deg","timeZoneOffset":99,"timeZoneDST":0,"stateTimeFormat":"3","stateDateFormat":"12"}]`

Sadly now it doesn't work on the start of the day. It shoud evaluate to "untill civilSet".

**Comment by Hypnos3** [comment]
In my case it seems to work:
![image](https://user-images.githubusercontent.com/12692680/75110990-227b9000-5635-11ea-95d5-761c1fa7db1f.png)

In your second example the first rule (*Morgens Dunkel*) is used.

Independently I have found an other problem which will cause no output at all.

**Comment by hasenbolle** [comment]
I've tried again, with the same flow. It didn't worked again.  Then i added a debug node after the inject node to check if the time is right. And then it worked.
Removed the debug node and it still works.

Thats weird. 

Now i cannot reproduce the problem. 
I will see if this happens again.

Thanks for investigating.

**Comment by Hypnos3** [comment]
There seems still problems to investigate.

**Comment by hasenbolle** [comment]
Yes. Now i can reproduce the issue again. Let me know if you need some assistance.

**Comment by Hypnos3** [comment]
I'm still testing.

I found out that I had a knot in my head when implementing the starting time for calculating the solar time. That should fit with version 1.0.9.

I still worry that the error does not always occur. This may indicate that there are other bugs.

**Comment by Hypnos3** [comment]
still testing

**Comment by hasenbolle** [comment]
thanks for looking into it. Just tested with the same flow and version 1.0.10.

I does work for the next day (ex. 27.2.2020, 00:46:40). But if you use a past day (ex. 23.2.2020, 00:46:40), it does not work.

**Comment by Hypnos3** [comment]
Ok, in my tests it now seems to be that the calculation of the sun time is for the correct day before and after midnight (local time).

I needed so many attempts to solve this because the behavior in my development environment (Windows) and my productive (Linux) was completely different (same Nodejs version).
Which I unfortunately do not understand at all, because the operating system should be completely irrelevant due to node js.

I'm not coming to test today.
My tests are still ongoing. I have never tested appointments in the past.  I'll take a look at that.  It will probably not be until the weekend.

**Comment by Hypnos3** [comment]
My first test does not show any Problem before Midnight and after Midnight the last two years ago:

![image](https://user-images.githubusercontent.com/12692680/75457815-3b5dab80-597d-11ea-82eb-d969c5d7f16c.png)

here is my test setup:
```json
[
    {
        "id": "f14e22f9.2401f",
        "type": "clock-timer",
        "z": "959733ce.a50c2",
        "name": "",
        "topic": "",
        "positionConfig": "650223e.daba8dc",
        "outputs": 2,
        "autoTrigger": false,
        "autoTriggerTime": 1200000,
        "startDelayTime": "0",
        "storeName": "",
        "overwriteExpire": "",
        "rules": [
            {
                "index": 0,
                "name": "",
                "isValid": false,
                "valid": {},
                "timeValue": "sunriseEnd",
                "timeType": "pdsTime",
                "timeOp": 0,
                "timeOpText": "↥ bis",
                "offsetValue": "",
                "offsetType": "none",
                "multiplier": 60000,
                "timeDays": "*",
                "timeMonths": "*",
                "timeOnlyEvenDays": false,
                "timeOnlyOddDays": false,
                "timeMinValue": "",
                "timeMinType": "none",
                "offsetMinValue": "",
                "offsetMinType": "none",
                "multiplierMin": 60000,
                "timeMaxValue": "",
                "timeMaxType": "none",
                "offsetMaxValue": "",
                "offsetMaxType": "none",
                "multiplierMax": 60000,
                "payloadValue": "true",
                "payloadType": "bool",
                "payloadOffsetValue": "",
                "payloadOffsetType": "none",
                "payloadOffsetMultiplier": 60000,
                "payloadFormat": 99,
                "topic": "",
                "validOperandAValue": "",
                "validOperandAType": "none",
                "validOperator": "true",
                "validOperatorText": "ist true",
                "validOperandBValue": "",
                "validOperandBType": "num",
                "valid2LogOperator": 0,
                "valid2LogOperatorText": "N/A",
                "valid2OperandAValue": "",
                "valid2OperandAType": "msg",
                "valid2Operator": "true",
                "valid2OperatorText": "ist true",
                "valid2OperandBValue": "",
                "valid2OperandBType": "num",
                "description": "<div><i class=\"fa fa-clock-o\" aria-hidden=\"true\"></i> ↥ bis <var>Sonnenaufgang Ende</var></div><div><div class=\"indent-payload-text\"><i class=\"fa fa-step-backward\" aria-hidden=\"true\"></i> <span>Payload:</span> <var>true</var></div></div>",
                "timeMinOp": 0,
                "timeMaxOp": 0,
                "timeDateStart": "",
                "timeDateEnd": ""
            },
            {
                "index": 1,
                "name": "",
                "isValid": false,
                "valid": {},
                "timeValue": "civilDusk",
                "timeType": "pdsTime",
                "timeOp": 1,
                "timeOpText": "↧ von",
                "offsetValue": "",
                "offsetType": "none",
                "multiplier": 60000,
                "timeDays": "*",
                "timeMonths": "*",
                "timeOnlyEvenDays": false,
                "timeOnlyOddDays": false,
                "timeMinValue": "",
                "timeMinType": "none",
                "offsetMinValue": "",
                "offsetMinType": "none",
                "multiplierMin": 60000,
                "timeMaxValue": "",
                "timeMaxType": "none",
                "offsetMaxValue": "",
                "offsetMaxType": "none",
                "multiplierMax": 60000,
                "payloadValue": "true",
                "payloadType": "bool",
                "payloadOffsetValue": "",
                "payloadOffsetType": "none",
                "payloadOffsetMultiplier": 60000,
                "payloadFormat": 99,
                "topic": "",
                "validOperandAValue": "",
                "validOperandAType": "none",
                "validOperator": "true",
                "validOperatorText": "ist true",
                "validOperandBValue": "",
                "validOperandBType": "num",
                "valid2LogOperator": 0,
                "valid2LogOperatorText": "N/A",
                "valid2OperandAValue": "",
                "valid2OperandAType": "msg",
                "valid2Operator": "true",
                "valid2OperatorText": "ist true",
                "valid2OperandBValue": "",
                "valid2OperandBType": "num",
                "description": "<div><i class=\"fa fa-clock-o\" aria-hidden=\"true\"></i> ↧ von <var>bürgerliche Abenddämmerung</var></div><div><div class=\"indent-payload-text\"><i class=\"fa fa-step-backward\" aria-hidden=\"true\"></i> <span>Payload:</span> <var>true</var></div></div>",
                "timeMinOp": 0,
                "timeMaxOp": 0,
                "timeDateStart": "",
                "timeDateEnd": ""
            }
        ],
        "payloadDefault": "false",
        "payloadDefaultType": "bool",
        "payloadDefaultTimeFormat": 0,
        "payloadDefaultOffset": 0,
        "payloadDefaultOffsetType": "none",
        "payloadDefaultOffsetMultiplier": 60000,
        "x": 800,
        "y": 3675,
        "wires": [
            [],
            [
                "595a937a.f3692c"
            ]
        ]
    },
    {
        "id": "5a59a46d.8e9f8c",
        "type": "inject",
        "z": "959733ce.a50c2",
        "name": "",
        "topic": "start/stop",
        "payload": "23:30",
        "payloadType": "str",
        "repeat": "",
        "crontab": "",
        "once": false,
        "onceDelay": 0.1,
        "x": 395,
        "y": 3735,
        "wires": [
            [
                "a614b584.933118"
            ]
        ]
    },
    {
        "id": "1a789cb0.97cfd3",
        "type": "inject",
        "z": "959733ce.a50c2",
        "name": "",
        "topic": "start/stop",
        "payload": "0:01",
        "payloadType": "str",
        "repeat": "",
        "crontab": "",
        "once": false,
        "onceDelay": 0.1,
        "x": 385,
        "y": 3780,
        "wires": [
            [
                "a614b584.933118"
            ]
        ]
    },
    {
        "id": "595a937a.f3692c",
        "type": "switch",
        "z": "959733ce.a50c2",
        "name": "",
        "property": "payload.rule.id",
        "propertyType": "msg",
        "rules": [
            {
                "t": "eq",
                "v": "1",
                "vt": "num"
            },
            {
                "t": "eq",
                "v": "2",
                "vt": "num"
            },
            {
                "t": "else"
            }
        ],
        "checkall": "true",
        "repair": false,
        "outputs": 3,
        "x": 1000,
        "y": 3675,
        "wires": [
            [],
            [],
            [
                "d924c259.c3129"
            ]
        ]
    },
    {
        "id": "d924c259.c3129",
        "type": "debug",
        "z": "959733ce.a50c2",
        "name": "out",
        "active": true,
        "tosidebar": true,
        "console": false,
        "tostatus": false,
        "complete": "true",
        "targetType": "full",
        "x": 1165,
        "y": 3675,
        "wires": []
    },
    {
        "id": "9ce00576.f55238",
        "type": "inject",
        "z": "959733ce.a50c2",
        "name": "",
        "topic": "",
        "payload": "",
        "payloadType": "date",
        "repeat": "",
        "crontab": "",
        "once": false,
        "onceDelay": 0.1,
        "x": 375,
        "y": 3675,
        "wires": [
            [
                "f14e22f9.2401f"
            ]
        ]
    },
    {
        "id": "a614b584.933118",
        "type": "function",
        "z": "959733ce.a50c2",
        "name": "prepare",
        "func": "\nconst minutesEachLoop = 1440;\nconst loopCycle = 0.03 // sekunden\nlet timeObj = context.get(\"timeObj\");\n\nconst startYearOffset = -2;     // start two years ago:\nconst startMonthOffset = 0;\nconst startDayOffset = 0;\n\nif (timeObj && msg.topic.includes('stop')) {\n    clearInterval(timeObj);\n    context.set(\"timeObj\", null);\n    let d = new Date(context.get(\"date\"));\n    node.status({fill:\"red\",shape:\"ring\",text:\"off - \" + d.toLocaleTimeString()+' ' + d.getFullYear() + '-' + (d.getMonth() +1) + '-' + d.getDate()});\n} else if (!timeObj && msg.topic.includes('start')) {\n    context.set(\"message\", msg);\n    let d = new Date();\n    \n    d.setFullYear(d.getFullYear() + startYearOffset);\n    d.setMonth(d.getMonth() + startMonthOffset);\n    d.setDate(d.getDate() + startDayOffset);\n    \n    let num = msg.payload.split(':') || [0,0];\n    d.setHours(parseInt(num[0]) || 0);\n    d.setMinutes(parseInt(num[1]) || 0);\n    context.set(\"date\", d.getTime());\n    msg.lts = d.toLocaleTimeString();\n    msg.ts = d.getTime();\n    node.log(\"sending \" + d.toLocaleTimeString() + ' #### ' + d.toLocaleDateString() + ' ####################################### payload='+msg.payload+' topic='+msg.topic+' ts='+msg.ts);\n    node.send(msg);\n\n    let timeObj = setInterval(function(){\n        let msg = context.get(\"message\");\n        let d = new Date(context.get(\"date\"));\n        //d.setHours(d.getHours()+1);\n        d.setMinutes(d.getMinutes() + minutesEachLoop)\n        context.set(\"date\", d.getTime());\n        msg.lts = d.toLocaleTimeString();\n        msg.ts = d.getTime();\n        node.status({fill:\"green\",shape:\"dot\",text:d.toLocaleTimeString()+' ' + d.getFullYear() + '-' + (d.getMonth() +1) + '-' + d.getDate()});\n        node.log(\"sending \" + d.toLocaleTimeString() + ' #### ' + d.toLocaleDateString() + ' ####################################### payload='+msg.payload+' topic='+msg.topic+' ts='+msg.ts);\n        node.send(msg);\n\t}, (1000 * loopCycle));\n    context.set(\"timeObj\", timeObj);\n    node.status({fill:\"green\",shape:\"ring\",text:d.toLocaleTimeString()+' ' + d.getFullYear() + '-' + (d.getMonth() +1) + '-' + d.getDate()});\n} else {\n    let d = new Date(context.get(\"date\"));\n    d.setMinutes(d.getMinutes() + 1)\n    //d.setHours(d.getHours()+1);\n    msg.lts = d.toLocaleTimeString();\n    msg.ts = d.getTime();\n    node.status({fill:\"green\",shape:\"dot\",text:d.toLocaleTimeString()+' ' + d.getFullYear() + '-' + (d.getMonth() +1) + '-' + d.getDate()});\n    node.log(\"sending interrupt msg \" + d.toLocaleTimeString() + ' #### ' + d.toLocaleDateString() + ' ####################################### payload='+msg.payload+' topic='+msg.topic+' ts='+msg.ts);\n    node.send(msg);\n}\n\nreturn null;",
        "outputs": 1,
        "noerr": 0,
        "x": 600,
        "y": 3735,
        "wires": [
            [
                "f14e22f9.2401f"
            ]
        ]
    },
    {
        "id": "650223e.daba8dc",
        "type": "position-config",
        "z": "",
        "name": "",
        "isValide": "true",
        "longitude": "0",
        "latitude": "0",
        "angleType": "deg",
        "timeZoneOffset": 99,
        "timeZoneDST": 0,
        "stateTimeFormat": "HH:mm:ss",
        "stateDateFormat": "yyyy-MM-dd"
    }
]
```

**Comment by Hypnos3** [comment]
I have found no problem and published 1.0.11.

The new version should not behave differently to this problem than version 1.0.10. I could now neither reproduce the problem with the past in my productive nor in my development system.

**Comment by hasenbolle** [comment]
Thanks for the update. 

Sadly it doesn't work.

Yesterday i updated to the version 1.0.10. On 00:36 the time-inject node triggered because of a new sun position. That signal goes directly to the clock-timer node (same configuration as the clock-timer node in my example flow). The clock-timer node evaluated the current sun position to false (Daylight). 

After that i triggered right away my test flow (with the same time as in the nigt - 00:36) and also this one evaluated to false. 

Today, after a node-red restart, the same test flow and the same time evauluated to true (correct behaviour).

![image](https://user-images.githubusercontent.com/12832850/75523916-36e0d380-5a0d-11ea-8414-d987a46fc9ec.png)
![image](https://user-images.githubusercontent.com/12832850/75523954-45c78600-5a0d-11ea-9a0c-8202ed8d3990.png)

Right now your test flow does also work.

Thats really weird. 

I will try your testflow tonight on 00:36

**Comment by hasenbolle** [comment]
The last couple of days i had no problems. Looks like it is fixed. Thanks for your help

**Comment by Hypnos3** [comment]
Meanwhile I get the confirmation that a similar bug (# 98) has been fixed, so I am hopeful to have fixed the issue.
