### ISSUE TITLE
blind-control: expiration time does not work for longer periods

### ISSUE THREAD

**Issue by DirkHBo** [rdmtc/node-red-contrib-sun-position#112]
**Describe the bug**
I use the blind-control including overwrite. When I set the expiration time to some minutes the overrite will be reset within the period set. When I set the expiration period to 2h the overwrite status will not be reset.

Set the expiration period to 2h.
`[{"id":"fd30ddd8.79fad8","type":"inject","z":"706ab47d.f78e1c","name":"","topic":"","payload":"","payloadType":"date","repeat":"60","crontab":"","once":false,"onceDelay":0.1,"x":110,"y":1140,"wires":[["13e3a75.1ee6159"]]},{"id":"13e3a75.1ee6159","type":"blind-control","z":"706ab47d.f78e1c","name":"","topic":"","positionConfig":"f1f8e703.a91c78","outputs":"1","autoTrigger":false,"autoTriggerTime":3600000,"storeName":"","blindIncrement":"0.5","blindOpenPos":1,"blindClosedPos":0,"blindPosReverse":false,"blindPosDefault":"open (max)","blindPosDefaultType":"levelFixed","overwriteExpire":"7200000","rules":[{"index":0,"name":"Werktags morgens","isValid":false,"valid":{},"timeValue":"6:45","timeType":"entered","timeOp":0,"timeOpText":"↥ bis","offsetValue":"","offsetType":"none","multiplier":60000,"timeDays":"*","timeMonths":"*","timeOnlyEvenDays":false,"timeOnlyOddDays":false,"timeMinValue":"","timeMinType":"none","offsetMinValue":"","offsetMinType":"none","multiplierMin":60000,"timeMaxValue":"","timeMaxType":"none","offsetMaxValue":"","offsetMaxType":"none","multiplierMax":60000,"levelValue":"closed (min)","levelType":"levelFixed","levelOp":0,"levelOpText":"↕  Absolut","validOperandAValue":"day.tomorrow.isWeekendOrHoliday","validOperandAType":"global","validOperator":"false","validOperatorText":"ist false","validOperandBValue":"","validOperandBType":"num","valid2LogOperator":0,"valid2LogOperatorText":"N/A","valid2OperandAValue":"","valid2OperandAType":"msg","valid2Operator":"true","valid2OperatorText":"ist true","valid2OperandBValue":"","valid2OperandBType":"num","description":"<div><i class=\"fa fa-code-fork\" aria-hidden=\"true\"></i> <var>global....tomorrow.isWeekendOrHoliday</var> ist false</div><div><i class=\"fa fa-clock-o\" aria-hidden=\"true\"></i> ↥ bis <var>6:45</var></div><div>↕  Absolut <var>geschlossen (min)</var></div>","timeMinOp":0,"timeMaxOp":0,"timeDateStart":"","timeDateEnd":""},{"index":1,"name":"Wochenende morgens","isValid":false,"valid":{},"timeValue":"09:00","timeType":"entered","timeOp":0,"timeOpText":"↥ bis","offsetValue":"","offsetType":"none","multiplier":60000,"timeDays":"*","timeMonths":"*","timeOnlyEvenDays":false,"timeOnlyOddDays":false,"timeMinValue":"","timeMinType":"none","offsetMinValue":"","offsetMinType":"none","multiplierMin":60000,"timeMaxValue":"","timeMaxType":"none","offsetMaxValue":"","offsetMaxType":"none","multiplierMax":60000,"levelValue":"closed (min)","levelType":"levelFixed","levelOp":0,"levelOpText":"↕  Absolut","validOperandAValue":"day.today.isWeekendOrHoliday","validOperandAType":"global","validOperator":"true","validOperatorText":"ist true","validOperandBValue":"","validOperandBType":"num","valid2LogOperator":0,"valid2LogOperatorText":"N/A","valid2OperandAValue":"","valid2OperandAType":"msg","valid2Operator":"true","valid2OperatorText":"ist true","valid2OperandBValue":"","valid2OperandBType":"num","description":"<div><i class=\"fa fa-code-fork\" aria-hidden=\"true\"></i> <var>global.day.today.isWeekendOrHoliday</var> ist true</div><div><i class=\"fa fa-clock-o\" aria-hidden=\"true\"></i> ↥ bis <var>09:00</var></div><div>↕  Absolut <var>geschlossen (min)</var></div>","timeMinOp":0,"timeMaxOp":0,"timeDateStart":"","timeDateEnd":""},{"index":2,"name":"Sonnenaufgang","isValid":false,"valid":{},"timeValue":"sunrise","timeType":"pdsTime","timeOp":0,"timeOpText":"↥ bis","offsetValue":"10","offsetType":"num","multiplier":60000,"timeDays":"*","timeMonths":"*","timeOnlyEvenDays":false,"timeOnlyOddDays":false,"timeMinValue":"","timeMinType":"none","offsetMinValue":"","offsetMinType":"none","multiplierMin":60000,"timeMaxValue":"","timeMaxType":"none","offsetMaxValue":"","offsetMaxType":"none","multiplierMax":60000,"levelValue":"closed (min)","levelType":"levelFixed","levelOp":0,"levelOpText":"↕  Absolut","validOperandAValue":"","validOperandAType":"none","validOperator":"true","validOperatorText":"ist true","validOperandBValue":"","validOperandBType":"num","valid2LogOperator":0,"valid2LogOperatorText":"N/A","valid2OperandAValue":"","valid2OperandAType":"msg","valid2Operator":"true","valid2OperatorText":"ist true","valid2OperandBValue":"","valid2OperandBType":"num","description":"<div><i class=\"fa fa-clock-o\" aria-hidden=\"true\"></i> ↥ bis <var>Sonnenaufgang Begin</var> + 00:10</div><div>↕  Absolut <var>geschlossen (min)</var></div>","timeMinOp":0,"timeMaxOp":0,"timeDateStart":"","timeDateEnd":""},{"index":3,"name":"Sonnenuntergang","isValid":false,"valid":{},"timeValue":"sunset","timeType":"pdsTime","timeOp":1,"timeOpText":"↧ von","offsetValue":"30","offsetType":"num","multiplier":60000,"timeDays":"*","timeMonths":"*","timeOnlyEvenDays":false,"timeOnlyOddDays":false,"timeMinValue":"","timeMinType":"none","offsetMinValue":"","offsetMinType":"none","multiplierMin":60000,"timeMaxValue":"","timeMaxType":"none","offsetMaxValue":"","offsetMaxType":"none","multiplierMax":60000,"levelValue":"closed (min)","levelType":"levelFixed","levelOp":0,"levelOpText":"↕  Absolut","validOperandAValue":"","validOperandAType":"none","validOperator":"true","validOperatorText":"ist true","validOperandBValue":"","validOperandBType":"num","valid2LogOperator":0,"valid2LogOperatorText":"N/A","valid2OperandAValue":"","valid2OperandAType":"msg","valid2Operator":"true","valid2OperatorText":"ist true","valid2OperandBValue":"","valid2OperandBType":"num","description":"<div><i class=\"fa fa-clock-o\" aria-hidden=\"true\"></i> ↧ von <var>Sonnenuntergang Ende</var> + 00:30</div><div>↕  Absolut <var>geschlossen (min)</var></div>","timeMinOp":0,"timeMaxOp":0,"timeDateStart":"","timeDateEnd":""},{"index":4,"name":"Werktags abends","isValid":false,"valid":{},"timeValue":"21:30","timeType":"entered","timeOp":1,"timeOpText":"↧ von","offsetValue":"","offsetType":"none","multiplier":60000,"timeDays":"*","timeMonths":"*","timeOnlyEvenDays":false,"timeOnlyOddDays":false,"timeMinValue":"","timeMinType":"none","offsetMinValue":"","offsetMinType":"none","multiplierMin":60000,"timeMaxValue":"","timeMaxType":"none","offsetMaxValue":"","offsetMaxType":"none","multiplierMax":60000,"levelValue":"closed (min)","levelType":"levelFixed","levelOp":0,"levelOpText":"↕  Absolut","validOperandAValue":"day.tomorrow.isWeekendOrHoliday","validOperandAType":"global","validOperator":"false","validOperatorText":"ist false","validOperandBValue":"","validOperandBType":"num","valid2LogOperator":0,"valid2LogOperatorText":"N/A","valid2OperandAValue":"","valid2OperandAType":"msg","valid2Operator":"true","valid2OperatorText":"ist true","valid2OperandBValue":"","valid2OperandBType":"num","description":"<div><i class=\"fa fa-code-fork\" aria-hidden=\"true\"></i> <var>global....tomorrow.isWeekendOrHoliday</var> ist false</div><div><i class=\"fa fa-clock-o\" aria-hidden=\"true\"></i> ↧ von <var>21:30</var></div><div>↕  Absolut <var>geschlossen (min)</var></div>","timeMinOp":0,"timeMaxOp":0,"timeDateStart":"","timeDateEnd":""},{"index":5,"name":"Wochenende abends","isValid":false,"valid":{},"timeValue":"22:30","timeType":"entered","timeOp":1,"timeOpText":"↧ von","offsetValue":"","offsetType":"none","multiplier":60000,"timeDays":"*","timeMonths":"*","timeOnlyEvenDays":false,"timeOnlyOddDays":false,"timeMinValue":"","timeMinType":"none","offsetMinValue":"","offsetMinType":"none","multiplierMin":60000,"timeMaxValue":"","timeMaxType":"none","offsetMaxValue":"","offsetMaxType":"none","multiplierMax":60000,"levelValue":"closed (min)","levelType":"levelFixed","levelOp":0,"levelOpText":"↕  Absolut","validOperandAValue":"","validOperandAType":"none","validOperator":"true","validOperatorText":"ist true","validOperandBValue":"","validOperandBType":"num","valid2LogOperator":0,"valid2LogOperatorText":"N/A","valid2OperandAValue":"","valid2OperandAType":"msg","valid2Operator":"true","valid2OperatorText":"ist true","valid2OperandBValue":"","valid2OperandBType":"num","description":"<div><i class=\"fa fa-clock-o\" aria-hidden=\"true\"></i> ↧ von <var>22:30</var></div><div>↕  Absolut <var>geschlossen (min)</var></div>","timeMinOp":0,"timeMaxOp":0,"timeDateStart":"","timeDateEnd":""}],"sunControlMode":"0","sunFloorLength":"","sunMinAltitude":"","sunMinDelta":"","blindPosMin":"closed (min)","blindPosMinType":"levelFixed","blindPosMax":"open (max)","blindPosMaxType":"levelFixed","smoothTime":"","windowTop":"","windowBottom":"","windowAzimuthStart":"","windowAzimuthEnd":"","oversteerValue":"","oversteerValueType":"none","oversteerCompare":"gte","oversteerThreshold":"","oversteerThresholdType":"num","oversteerBlindPos":"open (max)","oversteerBlindPosType":"levelFixed","oversteer2Value":"","oversteer2ValueType":"none","oversteer2Compare":"gte","oversteer2Threshold":"","oversteer2ThresholdType":"num","oversteer2BlindPos":"open (max)","oversteer2BlindPosType":"levelFixed","oversteer3Value":"","oversteer3ValueType":"none","oversteer3Compare":"gte","oversteer3Threshold":"","oversteer3ThresholdType":"num","oversteer3BlindPos":"open (max)","oversteer3BlindPosType":"levelFixed","x":400,"y":1140,"wires":[["c1a2bce6.5bbdc"]]},{"id":"f1f8e703.a91c78","type":"position-config","z":"","name":"Home","isValide":"true","longitude":"0","latitude":"0","angleType":"deg","timeZoneOffset":"99","timeZoneDST":"0","stateTimeFormat":"3","stateDateFormat":"12"}]`

**Expected behavior**
Override status should be reset after expiration time period 

**Screenshots**
![grafik](https://user-images.githubusercontent.com/47914186/75626762-7ef92500-5bca-11ea-8164-66c9cde9f164.png)

**System information (please complete the following information):**
 - node-red-contrib-sun-position 1.0.11 (also in previous version)
 - Node-Red Version 1.0.3 running as docker image

**Additional context**
As I can not set an explicit position for the roller-shutters, it is just possible to set up, down and stop. So I set blind control to work within the range 0 to 1 with 0.5 steps. The vailues will be translated to up, down, stop actions and of course the other way around. (0.5 is stop that will force the rollershutters to go to a saved position)

**Comment by Hypnos3** [comment]
Ich sehe erstmal keinen Grund warum der überschriebene Wert nicht 2h anhalten sollte. Ich selbst habe bei mir 4h für das Überschreiben eingestellt und bin mir recht sicher das es funktioniert.

Aber ich werde das mal testen.

Beachten muss man, das man die Zeit auch mit einer eingehenden Nachricht einstellen kann. Falls eine eingehenden Nachricht `msg.expire` oder `msg.payload.expire` gesetzt hat und das als Zahl interpretiert werden kann oder wenn im topic Feld irgendwie das Wort **expire** vorkommt und der Payload als Zahl interpretiert werden kann, wird die Zeit auf diesen Wert in **Millisekunden** gesetzt. Wenn bereits eine Überschreibung aktiv ist, wird die Zeit einfach angepasst.
Bei einer sehr kleinen Zahl kann es so aussehen als ob die Zeit dann abläuft. (Falls man mit Prioritäten arbeitet muss das auch passen.)

**Comment by Hypnos3** [comment]
Ich hab es gleich getestet:
![image](https://user-images.githubusercontent.com/12692680/75633599-7d4d5280-5c06-11ea-83b8-815971c8e558.png)

```
1 Mar 19:45:47 - [debug] [blind-control:c0dbfdd3.d6196] --- blind-control - input msg.topic=leve
1 Mar 19:45:47 - [debug] [blind-control:c0dbfdd3.d6196] needOverwrite prio=0 expire=NaN newPos=0
1 Mar 19:45:47 - [debug] [blind-control:c0dbfdd3.d6196] overwrite newPos=0.5
1 Mar 19:45:47 - [debug] [blind-control:c0dbfdd3.d6196] setExpiringOverwrite
1 Mar 19:45:47 - [debug] [blind-control:c0dbfdd3.d6196] using default expire value 7200000
1 Mar 19:45:47 - [debug] [blind-control:c0dbfdd3.d6196] expires in 7200000ms
[...]
1 Mar 21:45:47 - [debug] [blind-control:c0dbfdd3.d6196] timeout - overwrite expired
1 Mar 21:45:47 - [debug] [blind-control:c0dbfdd3.d6196] blindPosOverwriteReset expire=1583095547824
```

Exakt 2h nach dem Override ist dieser "expired" und keine Sekunde eher.

**Comment by Hypnos3** [comment]
Vielleicht kannst du bei dir das Debug-Level von Node/RedMatic auf `debug` ändern und im Logfile nachsehen.
Ich werde ab der nächsten Version mehr Informationen im Log ab dem LogLevel `info` bereitstellen.

ENGLISH:
May you can change the debug level from Node / RedMatic to `debug` and look in the log file. From the next version, I will provide more information in the log from the log level `info`.

**Comment by DirkHBo** [comment]
Hallo,
danke für das Testen und das Feedback.
Nur um Missverständnisse auszuschliessen: Wenn ich das Timeot auf 4 Minuten stelle, erfolgt der Reset auch nach 4 Minuten. Wenn ich das Timeout auf 2 Stunden stelle, bleibt die Priorität erhalten - bis zum Node-Red Neustart, full deploy oder dem manuellen Reset.

Tatsächlich kommt am blind-control-Node nur payload, topic.levelOverride und Priority an.
![grafik](https://user-images.githubusercontent.com/47914186/76142239-e8b27c80-606b-11ea-8eed-803c27d35247.png)

Ich habe das log-level erhöht und lasse das Szenario noch Mal in Echtzeit ablaufen.

Nur eine Idee - vielleicht wäre es hilfreich, wenn der Node nicht nur die Prio anzeigt, sondern auch die TTL.
![grafik](https://user-images.githubusercontent.com/47914186/76142285-578fd580-606c-11ea-8df2-3c3682df2d5e.png)

An der Stelle auch vielen Dank für den wirklich schönen Node!

**Comment by Hypnos3** [comment]
Ich denke den Fehler gefunden zu haben. Ich hab es jetzt erst noch als beta Version released. Das bedeutet man kann die Version noch nicht regulär über Node-Red installieren, sondern nur über die Kommandozeile.

Entweder wartest du noch etwas oder wenn du es ausprobieren willst ist folgendes nötig:

Auf einem regulärem Linux:
```bash
npm install node-red-contrib-sun-position@1.0.13-beta
```

Auf einer Homematic CCU/RaspberryMatic muss man sich dazu mittels SSH einloggen und folgendes eingeben (alle 3 Zeilen einzeln, ohne #):
```bash
# source /usr/local/addons/redmatic/home/.profile
# cd /usr/local/addons/redmatic/var
# npm install --save --no-package-lock --global-style --save-prefix="~" --production node-red-contrib-sun-position@1.0.13-beta
```

**Comment by DirkHBo** [comment]
Test läuft mit 1.0.13-beta
![grafik](https://user-images.githubusercontent.com/47914186/76160152-f3324c00-6127-11ea-8cfc-88a291b9ca48.png)

**Comment by DirkHBo** [comment]
Das Zurücksetzen funktioniert jetzt wie erwartet.
Vielen Dank!
