### ISSUE TITLE
Messages through all outputs

### ISSUE THREAD

**Issue by FordAndii** [rdmtc/node-red-contrib-sun-position#12]
Hi, I just tried the sun-position node for the first time and I wonder whether it works the way I thought it should. I have defined 4 non-overlapping azimuth intervals. My understanding is that an incoming message should be forwarded to output 1 and at most 1 of the further outputs 2-5. However, all 5 outputs are firing:

[
{
"id": "1c01837f.6e6615",
"type": "sun-position",
"z": "40c3d124.71962",
"name": "",
"positionConfig": "7a9f37a8.318228",
"rules": [
{
"valueLow": "90",
"valueLowType": "num",
"valueHigh": "130",
"valueHighType": "num"
},
{
"valueLow": "130",
"valueLowType": "num",
"valueHigh": "210",
"valueHighType": "num"
},
{
"valueLow": "210",
"valueLowType": "num",
"valueHigh": "240",
"valueHighType": "num"
},
{
"valueLow": "240",
"valueLowType": "num",
"valueHigh": "350",
"valueHighType": "num"
}
],
"onlyOnChange": "true",
"topic": "",
"outputs": 5,
"start": "",
"startType": "none",
"startOffset": 0,
"startOffsetType": "none",
"startOffsetMultiplier": 60000,
"end": "",
"endType": "none",
"endOffset": 0,
"endOffsetType": "none",
"endOffsetMultiplier": 60000,
"x": 840,
"y": 620,
"wires": [
[
"b3820316.503ea8"
],
[
"5bb895f1.c64344"
],
[
"998cfb3b.ecc4f"
],
[
"37a540d8.69cfd8"
],
[
"74cd63c6.d04b94"
]
]
},
{
"id": "c127f351.795cc",
"type": "inject",
"z": "40c3d124.71962",
"name": "",
"topic": "",
"payload": "",
"payloadType": "date",
"repeat": "",
"crontab": "",
"once": false,
"onceDelay": 0.1,
"x": 660,
"y": 620,
"wires": [
[
"1c01837f.6e6615"
]
]
},
{
"id": "b3820316.503ea8",
"type": "debug",
"z": "40c3d124.71962",
"name": "",
"active": true,
"tosidebar": true,
"console": false,
"tostatus": false,
"complete": "true",
"targetType": "full",
"x": 1030,
"y": 560,
"wires": []
},
{
"id": "5bb895f1.c64344",
"type": "debug",
"z": "40c3d124.71962",
"name": "",
"active": true,
"tosidebar": true,
"console": false,
"tostatus": false,
"complete": "true",
"targetType": "full",
"x": 1030,
"y": 580,
"wires": []
},
{
"id": "998cfb3b.ecc4f",
"type": "debug",
"z": "40c3d124.71962",
"name": "",
"active": true,
"tosidebar": true,
"console": false,
"tostatus": false,
"complete": "true",
"targetType": "full",
"x": 1030,
"y": 600,
"wires": []
},
{
"id": "37a540d8.69cfd8",
"type": "debug",
"z": "40c3d124.71962",
"name": "",
"active": true,
"tosidebar": true,
"console": false,
"tostatus": false,
"complete": "true",
"targetType": "full",
"x": 1030,
"y": 620,
"wires": []
},
{
"id": "74cd63c6.d04b94",
"type": "debug",
"z": "40c3d124.71962",
"name": "",
"active": true,
"tosidebar": true,
"console": false,
"tostatus": false,
"complete": "true",
"targetType": "full",
"x": 1030,
"y": 640,
"wires": []
},
{
"id": "7a9f37a8.318228",
"type": "position-config",
"z": "",
"name": "S",
"isValide": "true",
"longitude": "0",
"latitude": "0",
"angleType": "deg",
"timezoneOffset": "1"
}
]

**Comment by Hypnos3** [comment]
Thank you for your Ticket.
Problem is solved with Version 0.2.9.
