### ISSUE TITLE
Node installation not working

### ISSUE THREAD

**Issue by rene54321** [rdmtc/node-red-contrib-sun-position#130]
Hi, I like to install your node on my RPI4. But I get errors

1. Searched in Node Red
2. Installed your node
3. See error

The error:
node-red-contrib-sun-position
Cannot read property 'nodes' of null 

![grafik](https://user-images.githubusercontent.com/15846090/78336766-37323880-7590-11ea-8580-8a5e7027bc57.png)

System information
 - Node Version [ 1.0.16]
 - Node-Red Version [ 0.20.8]
 - Hardware [e.g. RaspberryPi3, TinkerboardS, etc.]

Any help is highly appriciated.

best regards René

**Comment by rene54321** [comment]
Ok thanks I try to update Node Red

**Comment by Hypnos3** [comment]
Documentation fixed with Version 1.0.17.
