### ISSUE TITLE
Alternative Zeit in der inject at time node schlägt fehl

### ISSUE THREAD

**Issue by HMelzer** [rdmtc/node-red-contrib-sun-position#132]
Ich verwende die o.g Node zur Rollladensteuerung und versuche, den Zeitpunkt des Hochfahrens in Abhängigkeit davon zu gestalten, ab Sommerzeit ist oder nicht.
Dazu löse ich in einer _inject-at-time-node_ zum Zeitpunkt 3:05 Uhr einen Inject aus, welcher die Zeitzone liefert (Z):

![Sommerzeit](https://user-images.githubusercontent.com/49859355/78363496-27c8e480-75bc-11ea-807b-dbd2c2e73ef8.jpg)

In der nachfolgenden _function-node_ wird aus der empfangenen Zeitzone ermittelt, ob Sommerzeit ist oder nicht und eine globale Variable gesetzt:

var zz = msg.payload;
switch (zz)
{
case "GMT+2 ":
    sz = true;
    break;
case "GMT+1 ":
    sz = false;
    break;
default: sz = false;
}
msg={payload:sz};
node.status({fill:"green",shape:"dot",text:"Zeitzone "+zz+", Sommerzeit: "+sz});
global.set("SZ",sz);
return msg;

Allerdings schlägt die Ausführung immer dann fehl, wenn der alternative Zeitpunkt später liegt, als der im oberen Teil bereits definierte Zeitpunkt, obwohl die Bedingung hinsichtlich der Variable SZ erfüllt sein sollte:

![incjet_at_time](https://user-images.githubusercontent.com/49859355/78364713-387a5a00-75be-11ea-85b5-a6d841aff26c.jpg)

Ist dies nun ein Bug oder ist es genau so zu verstehen? Dann geht es aus der Anleitung so jedoch nicht hervor.

**Comment by Hypnos3** [comment]
Kann ich erstmal nicht nachvollziehen.

Bei mir geht es:
![image](https://user-images.githubusercontent.com/12692680/78398576-9b3a1880-75f3-11ea-9c3e-89024136c8f8.png)

```JSON
[{"id":"17e59870.14b4a8","type":"time-inject","z":"de4e9c38.0d942","name":"","nameInt":"true","positionConfig":"","payload":"true","payloadType":"bool","payloadTimeFormat":0,"payloadOffset":0,"payloadOffsetType":"none","payloadOffsetMultiplier":60000,"topic":"","time":"21:26","timeType":"entered","offset":0,"offsetType":"none","offsetMultiplier":60000,"timeEnd":"","timeEndType":"none","timeEndOffset":0,"timeEndOffsetType":"none","timeEndOffsetMultiplier":60000,"timeDays":"*","timeOnlyOddDays":false,"timeOnlyEvenDays":false,"timeMonths":"*","timedatestart":"","timedateend":"","property":"SZ","propertyType":"global","propertyCompare":"true","propertyThreshold":"","propertyThresholdType":"num","timeAlt":"21:29","timeAltType":"entered","timeAltDays":"*","timeAltOnlyOddDays":false,"timeAltOnlyEvenDays":false,"timeAltMonths":"*","timeAltOffset":0,"timeAltOffsetType":"none","timeAltOffsetMultiplier":60000,"once":false,"onceDelay":0.1,"addPayload1":"","addPayload1Type":"none","addPayload1Value":"","addPayload1ValueType":"date","addPayload1Format":"0","addPayload1Offset":0,"addPayload1OffsetType":"none","addPayload1OffsetMultiplier":60000,"addPayload1Next":true,"addPayload1Days":"*","addPayload2":"","addPayload2Type":"none","addPayload2Value":"","addPayload2ValueType":"date","addPayload2Format":"0","addPayload2Offset":0,"addPayload2OffsetType":"none","addPayload2OffsetMultiplier":60000,"addPayload2Next":true,"addPayload2Days":"*","addPayload3":"","addPayload3Type":"none","addPayload3Value":"","addPayload3ValueType":"date","addPayload3Format":"0","addPayload3Offset":0,"addPayload3OffsetType":"none","addPayload3OffsetMultiplier":60000,"addPayload3Next":true,"addPayload3Days":"*","recalcTime":2,"x":390,"y":2300,"wires":[["f22de852.4aa238"]]},{"id":"f22de852.4aa238","type":"debug","z":"de4e9c38.0d942","name":"","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"false","x":580,"y":2300,"wires":[]},{"id":"97818d07.e90c8","type":"function","z":"de4e9c38.0d942","name":"","func":"var zz = msg.payload;\nswitch (zz) {\n    case \"GMT+2\":\n        sz = true;\n        break;\n    case \"GMT+1\":\n        sz = false;\n    break;\n    default: sz = false;\n}\nmsg = {payload:sz};\nnode.status({fill:\"green\",shape:\"dot\",text:\"Zeitzone \"+zz+\", Sommerzeit: \"+sz});\nglobal.set(\"SZ\",sz);\nreturn msg;","outputs":1,"noerr":0,"x":410,"y":2360,"wires":[[]]},{"id":"d7a70cba.594d5","type":"inject","z":"de4e9c38.0d942","name":"","topic":"","payload":"GMT+2","payloadType":"str","repeat":"","crontab":"","once":false,"onceDelay":0.1,"x":190,"y":2360,"wires":[["97818d07.e90c8"]]},{"id":"ce9a2a88.c42238","type":"inject","z":"de4e9c38.0d942","name":"","topic":"","payload":"GMT+1","payloadType":"str","repeat":"","crontab":"","once":false,"onceDelay":0.1,"x":190,"y":2400,"wires":[["97818d07.e90c8"]]},{"id":"e9824d6c.98404","type":"time-inject","z":"de4e9c38.0d942","name":"","nameInt":"true","positionConfig":"","payload":"true","payloadType":"bool","payloadTimeFormat":0,"payloadOffset":0,"payloadOffsetType":"none","payloadOffsetMultiplier":60000,"topic":"","time":"21:26","timeType":"entered","offset":0,"offsetType":"none","offsetMultiplier":60000,"timeEnd":"","timeEndType":"none","timeEndOffset":0,"timeEndOffsetType":"none","timeEndOffsetMultiplier":60000,"timeDays":"*","timeOnlyOddDays":false,"timeOnlyEvenDays":false,"timeMonths":"*","timedatestart":"","timedateend":"","property":"SZ","propertyType":"global","propertyCompare":"false","propertyThreshold":"","propertyThresholdType":"num","timeAlt":"21:29","timeAltType":"entered","timeAltDays":"*","timeAltOnlyOddDays":false,"timeAltOnlyEvenDays":false,"timeAltMonths":"*","timeAltOffset":0,"timeAltOffsetType":"none","timeAltOffsetMultiplier":60000,"once":false,"onceDelay":0.1,"addPayload1":"","addPayload1Type":"none","addPayload1Value":"","addPayload1ValueType":"date","addPayload1Format":"0","addPayload1Offset":0,"addPayload1OffsetType":"none","addPayload1OffsetMultiplier":60000,"addPayload1Next":true,"addPayload1Days":"*","addPayload2":"","addPayload2Type":"none","addPayload2Value":"","addPayload2ValueType":"date","addPayload2Format":"0","addPayload2Offset":0,"addPayload2OffsetType":"none","addPayload2OffsetMultiplier":60000,"addPayload2Next":true,"addPayload2Days":"*","addPayload3":"","addPayload3Type":"none","addPayload3Value":"","addPayload3ValueType":"date","addPayload3Format":"0","addPayload3Offset":0,"addPayload3OffsetType":"none","addPayload3OffsetMultiplier":60000,"addPayload3Next":true,"addPayload3Days":"*","recalcTime":2,"x":410,"y":2420,"wires":[["1830a03.65f796"]]},{"id":"1830a03.65f796","type":"debug","z":"de4e9c38.0d942","name":"","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"false","x":600,"y":2420,"wires":[]}]
```

Was bedeutet denn "schlägt die Ausführung immer dann fehl"?

**Comment by HMelzer** [comment]
Mit dem Fehlschlgen ist gemeint, dass nicht wie erwartet, zum alternativen Zeitpunkt getriggert wird, sonder immer zum dem, der oben angegeben ist, auch wenn die Bedingung erfüllt ist.
Mit einer änlichen Variante, wie in dem von Hypno angegebenen Beispiel habe ich das ja auch zunächst erfolgreich probiert und dann so wie dargestellt umgesetz. Damit funktioniert es aber eben nicht mehr. Keine Ahnung, warum das so ist.

**Comment by HMelzer** [comment]
Das Fehlschlagen besteht darin, dass, nicht wie zu erwarten, zum alternativen Zeitpunkt getriggert wird, sondern zu dem oben angegebenen Zeitpunk (dem früheren), trotz der erfüllten Bedingung.
Mit einer ähnlichen Variante wie der von Hypno3 hatte ich das ja auch erfolgreich getestet und dann so wie gezeigt umgesetz. Dann jedoch funktionierte es eben nicht mehr. Ich habe keine Ahnung, weshalb nicht. Bei mir vergehen ja immer 24 Stunden, bis die Node wieder getriggert wird. Möglicherweise liegt es daran.

**Comment by Hypnos3** [comment]
Ich habe den Test mal im Produktivsystem bei mir nachgebaut und werde das mal ein paar Tage beobachten.

**Comment by HMelzer** [comment]
Da ich mehrere Rollläden habe und die Konstruktion bereits für alle verwendet habe, habe ich gestern noch bei zwei  Rollläden die Einstellungen so verändert, dass bei der ersten Zeit die spätere steht und bei der alternativen Zeit die frühere und die Bedingung natürlich so umgedreht, dass bei diesem Zeitpunkt eigentlich nicht getriggert werden sollte.
Im Ergebnis ist festzustellen, dass immer auf den frühsten Zeitpunkt getriggert wird, in diesem Fall sogar, obwohl die Bedingung nicht erfüllt ist.
Wie verhält es sich eigentlich mit der Neuberechnung? Wenn ich eine solche ausschließen will, muss ich dann 0 eintragen?

**Comment by Hypnos3** [comment]
Es wird intern immer zum früheren Zeitpunkt der Timer gesetzt und wenn diese Zeit Eintritt dann geprüft ob die Bedingung stimmt und wenn diese stimmt der Payload gesendet, sonst der Timer neu (dann auf die nächste Zeit) gestellt. Das ist bewusst so gebaut um einerseits die Bedingung spätest möglich zu prüfen (kann sich ja ständig ändern) und andererseits nicht ständig neu prüfen zu müssen. 

Das funktioniert auch. Heute früh wurde der Payload 7:30 Uhr und nicht 6:45 gesendet. 

Verwenden Sie auch die aktuelle Version der Node? Es gab ältere Versionen wo es Probleme gab. 
Wenn dem so ist Bitte mal das exportieren und hier posten, vielleicht macht irgendwo eine Einstellung in den Tiefen Probleme.

Ich habe gestern noch eine neue Version der Node veröffentlicht, bei welcher jetzt direkt in der Bedingung (anstelle global.SZ) abgefragt werden kann ob Sommerzeit ist.

Dann noch ein Hinweis: Es gibt auch im Paket neben der time-Inject auch gleich eine Node speziell für die Rolladensteuerung, je nachdem was man möchte ist diese vielleicht auch schon wieder Overkill.

**Comment by HMelzer** [comment]
Ich verstehe das immer noch nicht richtig. Was ist der frühere Zeitpunkt? Ist das generell der früheste, der gesetzt wurde oder eben der, der in der Node ganz oben steht, für den aber keine Bedingung formuliert werden kann. Die Bedingung steht immer bei dem alternativen Zeitpunkt.
Ist es nun egal, ob oben der frühere Zeitpunkt steht und der spätere als alternativer Zeitpunkt angegeben wird oder kann es auch anders herum angegeben werden.
Ich verwende übrigens die Version 1.0.16.

Ich habe jetzt noch einmal alle Flows neu gestartet und will morgen sehen, ob es möglicherweise irgenwo einen Hänger gabt. Sollte das nicht zum Erfolg führen werde ich dann Red Node komplett neu starten. Ein Versuch ist es wert.

Sollte alles nicht zum Erfolg führen, werde ich darauf zurück kommen und den Flow exportieren und hier posten.

Das es die Node zur Rollladensteuerung gibt, habe ich schon gesehen, war mir aber für den Moment zu überladen.

Ich findes es übrigens gut, dass mein Ansatz mit der Sommerzeit nun auch so schnell Eingang in die neue Version der Node gefunden hat. Man weiß ja nicht, wie lange die uns noch erhalten bleibt.
Ich werde diese aber erst installieren, wenn ich meine Tests abgeschlossen habe.

**Comment by HMelzer** [comment]
Nun, was soll ich sagen: Offenbar viel Läem um nichts.

Nachdem ich, wie gestern angekündigt, alle Flows neu gestartet habe, gingen heute Morgen die Rollos zum gewünschten Zeitpunkt hoch.

Offenbar war da irgend etwas hängen geblieben, was zu dem beschriebenen Verhalten führte.
Ich werde es weiter beobachten.

Das Ganze hat wenigsten dazu geführt, das die Node eine interessante Erweiterung erfahren hat,

Vielen Dank für das Verständnis und die Hilfe.
