### ISSUE TITLE
[FR] Docu: blind-control mode change by message seems not working

### ISSUE THREAD

**Issue by Hypnos3** [rdmtc/node-red-contrib-sun-position#133]
Question from [Homematic forum](https://homematic-forum.de/forum):

Habe ich eine Frage ob ich da etwas falsch verstanden habe. In der englischen Anleitung steht

an incoming message with msg.mode, msg.payload.mode or where the msg.topic contains setMode and the value of msg.payload is a valid number, will allow to set the mode of the sun control.
a value of 0 will deactivate sun control, 1 will set to maximize sunlight (Winter) and 2 will set to restrict sunlight (Summer).
The maximum adjustable mode is influenced by the settings of the node. The mode can not be set to restrict sunlight (2) if in the settings is setup only maximize sunlight (1).

Beim Senden einer Nachricht um den Modus zu ändern erfolgt jedoch keine Reaktion des Nodes den Modus zu ändern.
Oder ist das nicht mehr in der aktuellen Version implementiert?

**Comment by Hypnos3** [comment]
Hallo,

ich hab das gleich getestet und bei mir funktioniert es mit allen Möglichkeiten:
![image](https://user-images.githubusercontent.com/12692680/78406647-5ae29680-7603-11ea-9518-fff392ec387f.png)

Man muss nur sicher eine Zahl senden, entweder als `msg.mode` oder `msg.payload.mode` oder mit `msg.payload`, wenn die topic "setMode" enthält.
0 = aus;
1 = winter;
2 = Sommer Modus.

Strings, Booleans, etc... funktionieren nicht. Bei der Topic ist Groß und Kleinschreibung wichtig.

Gruß

**Comment by jmabad100** [comment]
The maximum adjustable mode is influenced by the settings of the node. The mode can not be set to restrict sunlight (2) if in the settings is setup only maximize sunlight (1).

Por lo tanto, sólo puedes modificar hacia valores menores. Si quieres modificar todos los valores, el nodo tiene que estar configurado en modo "restrict sunlight" (2)

**Comment by Hypnos3** [comment]
Documentation needs to be enhanced for that.

**Comment by jonferreira** [comment]
what's the logic behind this?

I have my house set by default in "winter mode / maximize sunlight" but want each roller shutter to change to "summer mode / reduce sunlight" based on inside and outside temperature - apparently that can't be done??

**Comment by Hypnos3** [comment]
The summer mode has more configuration than the winter mode or if sun control is off.
If the node is setup as "winter mode / maximize sunlight", may be configuration missing if the node is set by message to summer mode.

In the next release the mode will be persist in the node context and to thus a deploy will not change the mode. So I see no problem to setup the node with summer mode and overwrite this mode based on temperature with winter mode. So a change in the configuration will not lead into a mode change.
