### ISSUE TITLE
Don't work the oversteers

### ISSUE THREAD

**Issue by jmabad100** [rdmtc/node-red-contrib-sun-position#136]
I've tried to configurate an oversteers and don't work.

Coud you help me?

Thank so much

**Comment by Hypnos3** [comment]
I tested it right away and it seems to works for me:
![image](https://user-images.githubusercontent.com/12692680/78932691-45101e00-7aa8-11ea-868c-d2e6cb10db3b.png)

![image](https://user-images.githubusercontent.com/12692680/78932728-5527fd80-7aa8-11ea-9cb6-3bc3c060ee30.png)

Oversteer only works during sun control. It is intended to overwrite the sun control with a fixed shutter position in the event of cloudy weather, rain, high temperatures, etc.

What is the exact problem? Can you perhaps describe it in more detail?

**Comment by jmabad100** [comment]
Thank so much Hypnos3,

My problem was exactly that one, I was testing the oversteers with no Sun control!!!

Now, I just test it and works perfectly.

Thanks again.
