### ISSUE TITLE
Rules -  Problems when evaluating two global variables using "AND" or "OR"

### ISSUE THREAD

**Issue by jmabad100** [rdmtc/node-red-contrib-sun-position#138]
I need your help once again.

When I define a rule it can't evaluate two variables with "AND" or "OR". The rule only responds to the first variable, in this case global.lluvia but not global.presencia

Attached screeshot

![Captura de pantalla 2020-04-14 a las 23 44 36](https://user-images.githubusercontent.com/47498211/79277568-5b541a80-7eaa-11ea-8892-c89bca9c8d32.png)

You can help me?

Thank you very much for your interest

**Comment by Hypnos3** [comment]
I'am working on a solution. Because this entails extensive changes, it may take some time to complete.

**Comment by Ixuser-1** [comment]
I can also confirm this behavior when using multiple messages as conditions.

**Comment by Hypnos3** [comment]
It is fixed in the development branch.

**Comment by Hypnos3** [comment]
solved with Version 1.1.0
