### ISSUE TITLE
within Time node - Monatsberechnung inkorrekt im aktuellen Release 1.0.17

### ISSUE THREAD

**Issue by bluebook1** [rdmtc/node-red-contrib-sun-position#141]
Hi, ich hab, glaube ich, einen kleinen Bug gefunden, der sich wie folgt äußert:

Die Monatsberechnung in der Within time node scheint fehlerhaft zu sein. 
Heute z.B. (24.04) - haben wir Juni, gestern war Mai usw. 

Ich hatte diese Auffälligkeit schon im Homematic Forum vorgestellt - hier hatten sich auch schon mehrere Personen gemeldet, dass es bei Ihnen auch so aussieht. Ist also auch kein Einzelfall.

![grafik](https://user-images.githubusercontent.com/64259489/80348367-fd421280-886d-11ea-84c6-2b8252e76c74.png)

![grafik](https://user-images.githubusercontent.com/64259489/80348521-32e6fb80-886e-11ea-87c9-c43f01635f0b.png)

Falls noch was an Infos fehlt oder ich irgendwie helfen kann - gerne.

Grüßle 
Bluebook1

**Comment by tottiMG** [comment]
Das kann ich bestätigen.

Ich habe eine Gültigkeit von Mai bis Oktober eingetragen und es wurde **Monat nicht Gültig** angezeigt. Wenn ich den Monat März dazu nehme klappt es. Heute ist der 05.05.2020

**Comment by Hypnos3** [comment]
Problem gefunden, wird mit der nächsten version behoben.

**Comment by tottiMG** [comment]
Hallo ich weiss ist stressig solche Fehler zu lokalisieren und beheben, wollte aber einen Stand weitergeben, den ich aktuell habe:

Heute ist der 17.5. und ich musste den Januar aktivieren um die Meldung "aktueller Monat" zu bekommen.

Diese Info ist nur zur Problemfindung gedacht

**Comment by Hypnos3** [comment]
Bitte mit der Version 1.1.0 neu testen.
