### ISSUE TITLE
within time node - valid days not working

### ISSUE THREAD

**Issue by jooka1978** [rdmtc/node-red-contrib-sun-position#142]
**Describe the bug**
I have a within time node and for valid days only work day (Mon-Tu-We-Thu-Fi) is selected. I unchecked Sat and Sun. Today is Saturday and the nodes indicates a yellow sign saying the day is not selected. BUT it emits a message on both output.
Thanks for looking into it.

**To Reproduce**

**Expected behavior**
If a day is not selected stop the message.

**Screenshots**
![image](https://user-images.githubusercontent.com/37218509/80271484-ddb9b700-86c0-11ea-9d62-91e1c04b3096.png)
![image](https://user-images.githubusercontent.com/37218509/80271625-2625a480-86c2-11ea-8553-1314a7a692b2.png)

**System information (please complete the following information):**
 - Version [1.0.17]
 - Node-Red Version [1.0.5]
 - Hardware [RaspberryPi3]

**Additional context**

**Comment by Hypnos3** [comment]
Sorry, I can not reproduce this. If the status is "day is not selected" the message is only send to the second output.

**Comment by Hypnos3** [comment]
Please retest with Version 1.1.0
