### ISSUE TITLE
Auto trigger calculation is not working for first rule per day

### ISSUE THREAD

**Issue by MrLight** [rdmtc/node-red-contrib-sun-position#143]
**Describe the bug**
The auto trigger calculation is not working for the first rule per day. If I have a first rule per day which is running from 8:00 AM it does not trigger at 8:00AM but sometimes afterwards (auto trigger interval actually set to 20min) the second one until 9:30AM is triggering precisely at the specified time. I think there is an error in the first calculation per day.  

**To Reproduce**
1. take a clock-timer-node set up a rule from 8:00.
2. setup a second rule from 9:30
3. setup autotrigger with interval 20min
4. watch the first trigger will be somewhere around +/- 8:10

**System information (please complete the following information):**
 - Version 1.0.17
 - Node-Red Version 1.0.6

**Comment by Hypnos3** [comment]
I will improve it with the next Version. However, there may still be situations in which the next valid rule is not recognized.

**Comment by steffanv** [comment]
I think this problem appears also for a second rule:
![image](https://user-images.githubusercontent.com/7317719/82141870-e2453b80-9838-11ea-92ef-0d752a17e4d7.png)
Based on my current location the second rule should trigger around 9.20 pm
![image](https://user-images.githubusercontent.com/7317719/82141956-1587ca80-9839-11ea-8b1e-d990fcc5a331.png)
Despite an auto trigger with max 10 minutes the second rule usually triggers the blind around 10 pm

**Comment by Hypnos3** [comment]
I have still changed anything in the beta version.

**Comment by Hypnos3** [comment]
Please retest with Version 1.1.0

**Comment by MrLight** [comment]
HI,
I have updated to the latest Version yesterday. But the triggers from today have not fired yet.
I have assumed one ON event at 12:00 until 12:10 and another one from 14:00 to 14:10. But both where not triggered. I will double check that and will try to give you some more valuable feedback in the next days.
In the previous version I used a dummy trigger directly after midnight to get all in sync. That worked great, for the test I have deactivated the dummy trigger. My auto trigger is set to max. 20min at the moment.

**Comment by MrLight** [comment]
It looks like the timer node is not sending the configured topic anymore. So my underlying logic is not detecting the event correctly.
I have injected the node manually before the screenshot. Because of that the correct trigger time is not representable, but in this case it fired at the configured timestamp....
![image](https://user-images.githubusercontent.com/566059/82748980-669e3e00-9da6-11ea-8e97-acdc7f2aaf70.png)

**Comment by Hypnos3** [comment]
I have created a new issue for that problem.
Maybe there is something broken.

**Comment by MrLight** [comment]
The trigger worked correct today! 
Thank you for fixing that!
