### ISSUE TITLE
Sonne am Himmel

### ISSUE THREAD

**Issue by niwre2019** [rdmtc/node-red-contrib-sun-position#144]
Hallo,
ich versuche meine Markise mit dem Rolladen-Node zu steuern. Wenn die Sonne am Himmel kleiner einem bestimmten Prozentsatz ist, dann soll die Markise öffnen. Ich habe es derzeit schon auf kleiner 85 Prozent Sonne am Himmel stehen und trotzdem wird die Markise nicht geöffnet, obwohl der Himmel komplett bedeckt ist und es sogar leicht regnet.
Die Steuerung der Markise wurde durch nichts anderes übersteuert, sondern durch das aktuelle Sonnenlicht geschlossen. Meinen Standort habe ich korrekt festgelegt.
Habe ich da etwas in der Funktionalität falsch verstanden?
Viele Grüße 
Niwre2019

**Comment by niwre2019** [comment]
Hallo,
das Thema kann geschlossen werden, ich konnte es selbst mit der Übersteuerung und der Übergabe von Wetterdaten lösen.
Sorry

**Comment by mpolinowski** [comment]
Hallo @niwre2019 ,

kannst du Deine Einstellungen eventuell posten? Wir haben vermutlich das gleiche Problem und kommen gerade nicht weiter :)

**Comment by niwre2019** [comment]
Hallo @mpolinowski ,
das ist leider schwierig, da der Flow sehr komplex geworden ist und entsprechend viel Erklärung nötig wäre. Ich habe es so gelöst, dass ich die Wetterdaten von DWD regelmäßig alle 10 Minuten abfrage und diese Daten (Regenwahrscheinlichkeit, Bewölkung, Wind, signifikantes Wetter) auswerte. Wenn sich die Werte in einem bestimmten Bereich bewegen, dann wird eine Variable entsprechend auf True/False gesetzt.
Diese Variablen verwende ich dann in den Bedingungen im Rolladen-Node. Ich hoffe, das hilft euch weiter. :)

**Comment by mpolinowski** [comment]
Hey,

danke für deine schnelle Antwort!

Wir schauen mal ob wir das hinbekommen :)
