### ISSUE TITLE
Wrong calculations

### ISSUE THREAD

**Issue by PierreScerri** [rdmtc/node-red-contrib-sun-position#145]
**Describe the bug**
Time calculations are not inconsistent

**To Reproduce**
Does it on its own

**Expected behavior**
Proper status display and triggering at the correct time.

**Screenshots**
![Screenshot 2020-05-19 at 12 11 13](https://user-images.githubusercontent.com/34303331/82314642-68dd5280-99ca-11ea-807a-db7230269188.png)
![Screenshot 2020-05-19 at 12 29 04](https://user-images.githubusercontent.com/34303331/82315947-6845bb80-99cc-11ea-8e6a-b2889b7c44ad.png)

**System information (please complete the following information):**
 - Version 1.0.17
 - Node-Red Version 12.15.0
 - Hardware Raspberry Pi3 running Hassio

**Additional context**
In the first screenshot, the 'Night Shutters' node is set to trigger at Sunset. The 'Windows Open' node is set to trigger at 20 minutes before Sunset.  It is, however, showing 20 minutes after sunset in the status.

On another occasion, the 'Windows Open' node' status was at sunset.

On another occasion both nodes were triggered at 20 minutes before sunset.  

Restarting Node-Red corrected the times displayed (second screenshot).

Behaviour is inconsistent.

**Comment by Hypnos3** [comment]
Hi,

Does only the status indicate an incorrect time or is the actual trigger timestamp wrong?
Can you please post a screenshot of the settings or export the node?

thank you

**Comment by PierreScerri** [comment]
Seems to have settled down today.  Will get back to you if it misbehaves.

Thank you.
