### ISSUE TITLE
How to inject a message daily when sun azimuth equals 250

### ISSUE THREAD

**Issue by mattmattmatt** [rdmtc/node-red-contrib-sun-position#148]
**What's the recommended way to inject a message once per day when the sun's azimuth equals e.g. `250`?**

It seems like the `inject at time` node should be able to do this, but it only seems to support hardcoded sun events like `sunset` and `nautical dawn`. I tried to hack it with the `alternate time` functionality of that node, but to no success.

I worked around this issue currently by blindly injecting a message into the system _every minute_  and then checking with the `sun position` node if the azimuth equals a certain value. While this works, it seems overly complex and not ideal.

![image](https://user-images.githubusercontent.com/927830/82531776-d4234380-9af4-11ea-8a49-a879dea37e10.png)
_Workaround_

**Comment by Hypnos3** [comment]
This is an interesting use case. The time Inject node currently only support fixed azimuth angles which are the sun times. There is a possibility to adding a time offset to these timestamps.

The way you modeled it is currently the only way. I will think 🤔 about it, if I could implement this in any way.

**Comment by mattmattmatt** [comment]
Thanks for the quick response. 🙏 

It sounds like since sunset is based on a fixed azimuth, a similar check could be done with an arbitrary azimuth as well. In any case, thanks for looking into it 👍

**Comment by Hypnos3** [comment]
I have implemented something in version 1.1.1, but it is not really tested.
