### ISSUE TITLE
Eine Prio mit exeption:0 wird durch die Node selbsttätig zurück gesetzt

### ISSUE THREAD

**Issue by ThomasLoeffel** [rdmtc/node-red-contrib-sun-position#149]
**Beschreibung:**
Um meine Dachflächenfenster zu schützen, wird durch eine Prio das Schließen des Rollladen bei geöffneten Fenster verhindert.

Mir ist die Tage aufgefallen das dieses aber durch eine Regel der Node überschrieben wird. Heute Abend habe ich es getestet und kann das bestätigen.

Obwohl das Fenster offen war und dieses in der Node auch angezeigt wird, wurde die Regel bei Dämmerung schließen abgewickelt und die Prio "9" gelöscht.

**Test:** 
Schließen um 22:25 Uhr, vorher offen. Dann mit Prio 9 überschreiben. Berechnung auf 1 min und Haltezeit auf 5 Sekunden.

**Ergebnis:** 
Prio 9 wird überschrieben durch Regel schließen. Ich habe Dein Beispiel genutzt um dieses einmal nachzustellen. Auch hier wird die Prio durch die Regel in der Node gelöscht. Bei drücken auf Knopf 1 = manches mal wird Prio gelöscht. Ich mache gerade Tests bei welchen Bedingungen das passiert.

Gruß Thomas

**Screenshots**
![grafik](https://user-images.githubusercontent.com/44590735/82606157-e9f93d00-9bb6-11ea-9744-cc2068f6419f.png)

Änderung des Aufbaus:
![grafik](https://user-images.githubusercontent.com/44590735/82606418-57a56900-9bb7-11ea-827a-ab8417403cdd.png)

![grafik](https://user-images.githubusercontent.com/44590735/82606486-73a90a80-9bb7-11ea-9a4f-b3a2f4a1aa72.png)

![grafik](https://user-images.githubusercontent.com/44590735/82606523-7e639f80-9bb7-11ea-800e-2ac9bfc81027.png)

![grafik](https://user-images.githubusercontent.com/44590735/82607174-a30c4700-9bb8-11ea-82af-0e88d8788b04.png)

**Zusatz:**
Hier ein Beispiel aus der Debug-Node. Ohne Reset wird der Wert gelöscht.
![grafik](https://user-images.githubusercontent.com/44590735/82611514-f6829300-9bc0-11ea-8692-2516bb368434.png)

**Nur am Rande:** 
Die Doku mit dem Feueralarm klappt nur solange wie Deine "expire" Zeit in der Node anhält. Bei z.B. 5 Sek, verfällt es dann nach 5 Sek. und die Node geht zurück in die Auto-Funktion.

![grafik](https://user-images.githubusercontent.com/44590735/82612479-419da580-9bc3-11ea-8075-46e1114873e7.png)

**Comment by Hypnos3** [comment]
Ich konnte das jetzt erstmal nicht nachvollziehen.

Es gibt kein automatisches auslaufen des Überschreibens?
![image](https://user-images.githubusercontent.com/12692680/82681496-24fa7f80-9c4e-11ea-9813-a754543a8b92.png)

Das muss so aussehen:
![image](https://user-images.githubusercontent.com/12692680/82682149-13fe3e00-9c4f-11ea-842e-f47c387c0259.png)


Seit der letzten Version kann man den Regeln auch eine Priorität mitgeben und diese damit höher priorisieren als manuelles überschreiben.
Das muss auf 0 stehen, wenn man das nicht will:
![image](https://user-images.githubusercontent.com/12692680/82681621-55421e00-9c4e-11ea-8e4d-ef4cd0816183.png)


Wäre es möglich den Flow mal zu exportieren?

**Comment by ThomasLoeffel** [comment]
Hallo Hypnos,

sorry für die späte Rückmeldung. Ich habe dieses Thema über Tage geloogt um mir Klarheit zu verschaffen. Es scheint das sich zwei Themen vermischen. Zu Einen hat ein Flow der die Prio setzt als auch die Prio wieder löscht einen Fehler gehabt, zum Anderen hat der Blind Node sobald man vor der Node als auch danach etwas ändert ebenfalls sein Verhalten verändert. Keine Ahnung warum. Naja sieht nach einem Userfehler aus.

Danke Dir!
Gruß Thomas
