### ISSUE TITLE
Reset Maximum/Minimum wird nicht angezeigt

### ISSUE THREAD

**Issue by zygi79** [rdmtc/node-red-contrib-sun-position#151]
Hallo,

ich habe ein Problem mit den Regeln. Ich wollte das Beispiel aus der Anleitung nachbauen um meine Rolladen von geschlossen auf 10% zu bewegen, sobald der Fensteröffnungssensor "geöffnet" signalisiert. Dazu hatte ich zuerst die Minimum Overwrite auf 10% gesetzt und wollte dann die Regel erzeugen, dass dieser Overwrite zurückgesetzt wird. Bei mir werden in den Nodes "Blind Control" unter Rolladenposition Optionen jedoch nur 3 Möglichkeiten angezeigt: Absolut, Minimum (übersteuernd) und Maximum (übersteuernd). Die beiden Reset Optionen für Minimum und Maximum die in der Anleitung aufgeführt werden fehlen bei mir. 
Muss man da irgendwo etwas besonderes in den Nodes konfigurieren, damit die angezeigt werden? Hatte mich eigentlich an das Beispiel "Die Regelausführung, Caching, Bsp. Betrachten von Fensteröffnung" aus der Anleitung gehalten.

**Comment by Hypnos3** [comment]
Hallo,

das sit leider etwas veraltet. Diese Reset Optionen sind schon seit längerem nicht mehr vorhanden und bis jetzt hat diese noch niemand vermist.

Die aktuelle Anleitung ist die englische:
https://github.com/rdmtc/node-red-contrib-sun-position/blob/master/blind_control.md

Die [deutsche](https://github.com/rdmtc/RedMatic/wiki/Rollladen-und-Jalousiesteuerung) ist leider nicht aktuell und müsste mal überarbeitet werden (freiwillige vor ;) ).

Für das Reset gibt es aber mehrere neue Möglichkeiten.

Für eine Zeit kann man jetzt in der Regel direkt ein min und ein max angeben:
![image](https://user-images.githubusercontent.com/12692680/82755412-8e57cb00-9dd3-11ea-9128-34158526531c.png)

Als Position lässt sich die "default" Position setzen:
![image](https://user-images.githubusercontent.com/12692680/82755442-bfd09680-9dd3-11ea-828a-ed07d1770377.png)

Gerade letzteres entspricht den alten Reset Optionen, mit dem Unterschied das es die Position komplett zurücksetzt.

**Comment by zygi79** [comment]
Hallo,

vielen Dank. Sowas hatte ich mir schon gedacht, aber da es in allen Anleitungen (auch in der von dir verlinkten englischen Doku sind noch alle 5 Zustände erwähnt) noch vorkam und ich auch in den Changelogs nicht wirklich was dazu gefunden habe, bin ich erstmal davon ausgegangen was falsch gemacht zu haben.
Aber mit der von dir gezeigten Anleitung komme ich weiter. Nochmal vielen Dank!

**Comment by Yattien** [comment]
Falls noch jmd. über die Änderung stolpert: die englischen Seiten sind in das [Wiki](https://github.com/rdmtc/node-red-contrib-sun-position/wiki/blind-control) gezogen, die Links in der deutschen Beschreibung stimmen nicht mehr.

**Comment by Hypnos3** [comment]
Na dann sollten die Links mal angepasst werden ;)

**Comment by Hypnos3** [comment]
links corrected with next version
