### ISSUE TITLE
"within-time" add field in message to specify if in or out of time limit

### ISSUE THREAD

**Issue by rejoc** [rdmtc/node-red-contrib-sun-position#156]
Some time you only want to know if the timestamp is in or out of the time limit and inject this in a function. Right know you have to duplicate your function (or add a "change" module) on each of the output to differentiate the states.

If there was a specific item added to the out message, you could inject the 2 outputs to the same function that would use this new item.

So I propose to add a new item to the output message like "output" with values "in" or "out" (or whatever the user wants (if the value is empty, then there would be no added item....)

It would also be usefull if you inject both ouputs to a single debug display...

**Comment by Hypnos3** [comment]
new Version will have `withinTimeStart` and `withinTimeEnd` and `withinTime` property in the message
![image](https://user-images.githubusercontent.com/12692680/91233738-20a09f80-e732-11ea-9f62-a9acec29bc06.png)

![image](https://user-images.githubusercontent.com/12692680/91233773-31511580-e732-11ea-8df2-dff1cfe683cd.png)

where  `withinTime` will be the boolean if in or out of time
