### ISSUE TITLE
rules - "enthält irgendeins"

### ISSUE THREAD

**Issue by og9gjz567** [rdmtc/node-red-contrib-sun-position#158]
Hi,
thanks for your great work! It works like a charm. I now want to include the weather data, so the blinds won't close if there is no sun. I created a new rule, which contains the following:
![grafik](https://user-images.githubusercontent.com/58255842/83761420-938c0400-a676-11ea-8e76-e845683f3067.png)

I want to set the minimum postion on cloudy, rainy, snowing... conditions to 100% (open). Can you tell me how to use the "enthält irgendeins" condition?

Thanks!

**Comment by Hypnos3** [comment]
In the next version are implemented:
![image](https://user-images.githubusercontent.com/12692680/91235042-ed134480-e734-11ea-9c8d-ab30c67d59de.png)

For contains all/some the value must contain a list of values separated by comma `,` or semicolon `;` or pipe `|`.

![image](https://user-images.githubusercontent.com/12692680/91236208-a07d3880-e737-11ea-81ec-3f21077eec16.png)

![image](https://user-images.githubusercontent.com/12692680/91236319-e63a0100-e737-11ea-85ff-f17fdfb87b9a.png)
