### ISSUE TITLE
time-inject: wrong displayed times and (multiple) wrong trigger times

### ISSUE THREAD

**Issue by cswebdev** [rdmtc/node-red-contrib-sun-position#159]
**Describe the bug**
i use the time-inject node to trigger the garden lights at specific times depending on the sun position (on = civil dusk, off = civil dawn).

there seems to be 2 issues for me:

1.) the status which is displayed next to the node is only correct after the first deploy. when the first time the node was triggered, the new displayed value for next trigger time seems to be wrong.
For example at the moment, the displayed value for the next civil dusk is at 12.06.2020 23:45:21 which is A) in the past and B) not a correct calculated value for civil dusk for my lat/long location.

2.) it will trigger at the correct time, but also at other times. so last night, the expected time was 04:32 but it has also triggered at 01:00 and 02:20. 

it is completely independent from the chosen sun set method (nautical dusk, astronomical dusk etc), they all not working. even using an exact timestamp to trigger seems not to work correctly.

i have checked the defined time and timezone on my server, it is set correctly.

**Expected behavior**
the status of the used nodes should display the next time when the it will trigger again. this value will be automatically updated after a trigger.
it will only trigger once in 24h, the time of the selected sun position.

**System information (please complete the following information):**
 - Node Version 10.14.1
 - Node-Red Version 1.0.4
- sun-position version 1.1.3

**Additional context**
n/a

It would be nice to get some help, this things are driving me crazy at the moment.

**Comment by cswebdev** [comment]
have again checked the issue to give you more detailed information.

This is how to reproduce the bug:

1. create a time-inject node, configure a time where it should trigger, like 10:00 AM
2. deploy with "only changed nodes"
3. change the time in node from step 1 from 10:00 AM to 10:01 AM
4. deploy with "only changed nodes"

Expected Result: it will only trigger at 10:01 AM

But Result is: it will trigger on 10:00 AM and on 10:01 AM

To avoid this, the workaround is to restart the whole flows, or to restart the machine where node red is running. then it would run again as expected.

**Comment by petarvucetin** [comment]
I am not sure this is related but just today nothing was injected as the node completely skipped today's date. https://imgur.com/0UNWLH1 It went from 6/28 to 6/30 skipping today's date.

**Comment by PierreScerri** [comment]
I have the same issue.

This flow:
![Screenshot 2020-07-02 at 21 06 43](https://user-images.githubusercontent.com/34303331/86400190-7879d780-bca8-11ea-93a0-d2ff4e735d1a.png)
with inject enhanced node set like this:
![Screenshot 2020-07-02 at 20 59 31](https://user-images.githubusercontent.com/34303331/86400199-7d3e8b80-bca8-11ea-9494-f3a568913a07.png)
triggers like this:
![Screenshot 2020-07-02 at 21 06 28](https://user-images.githubusercontent.com/34303331/86400209-816aa900-bca8-11ea-83bd-429627f41a37.png)

Sunset is given as 20:23:41 by the node itself.

The time shown in the node status changrs with each trigger.

The workaround suggested above to restart did not work for me.
