### ISSUE TITLE
differenttime values

### ISSUE THREAD

**Issue by Missenberger79** [rdmtc/node-red-contrib-sun-position#163]
**Describe the bug**
The different nodes calculated for the same position different timevalues for the same event in node TimeInject and Sun-position.

**Screenshots**

![image](https://user-images.githubusercontent.com/58929668/84819890-0dc66c00-b019-11ea-9f72-6d3b8b4499b8.png)

**System information (please complete the following information):**
 - Node Version 10.20.1
 - Node-Red Version 1.0.3

`[
    {
        "id": "a0e60779.a02828",
        "type": "inject",
        "z": "6dce5c12.bb5e94",
        "name": "",
        "topic": "",
        "payload": "true",
        "payloadType": "bool",
        "repeat": "",
        "crontab": "",
        "once": false,
        "onceDelay": 0.1,
        "x": 1230,
        "y": 180,
        "wires": [
            [
                "77fd6a27.bd3b14"
            ]
        ]
    },
    {
        "id": "c481c31a.4774f",
        "type": "debug",
        "z": "6dce5c12.bb5e94",
        "name": "sunposition",
        "active": true,
        "tosidebar": true,
        "console": false,
        "tostatus": false,
        "complete": "payload",
        "targetType": "msg",
        "x": 1690,
        "y": 180,
        "wires": []
    },
    {
        "id": "77fd6a27.bd3b14",
        "type": "sun-position",
        "z": "6dce5c12.bb5e94",
        "name": "",
        "positionConfig": "2dfd3e6a.c59292",
        "rules": [],
        "onlyOnChange": "true",
        "topic": "",
        "outputs": 1,
        "start": "",
        "startType": "none",
        "startOffset": 0,
        "startOffsetType": "num",
        "startOffsetMultiplier": 60000,
        "end": "",
        "endType": "none",
        "endOffset": 0,
        "endOffsetType": "num",
        "endOffsetMultiplier": 60000,
        "x": 1410,
        "y": 120,
        "wires": [
            [
                "7a166b0d.d50f34"
            ]
        ]
    },
    {
        "id": "56523b6.37af8c4",
        "type": "debug",
        "z": "6dce5c12.bb5e94",
        "name": "Sonnenuntergang Beginn",
        "active": true,
        "tosidebar": true,
        "console": false,
        "tostatus": false,
        "complete": "payload",
        "targetType": "msg",
        "x": 1730,
        "y": 260,
        "wires": []
    },
    {
        "id": "761450c1.e2a44",
        "type": "time-inject",
        "z": "6dce5c12.bb5e94",
        "name": "",
        "nameInt": "Sonnenuntergang Begin",
        "positionConfig": "2dfd3e6a.c59292",
        "payload": "sunsetStart",
        "payloadType": "pdsTime",
        "payloadTimeFormat": "3",
        "payloadOffset": 0,
        "payloadOffsetType": "none",
        "payloadOffsetMultiplier": 60000,
        "topic": "",
        "injectTypeSelect": "none",
        "intervalCount": 1,
        "intervalCountType": "num",
        "intervalCountMultiplier": 60000,
        "time": "",
        "timeType": "entered",
        "offset": 0,
        "offsetType": "none",
        "offsetMultiplier": 60000,
        "timeEnd": "",
        "timeEndType": "entered",
        "timeEndOffset": 0,
        "timeEndOffsetType": "none",
        "timeEndOffsetMultiplier": 60000,
        "timeDays": "*",
        "timeOnlyOddDays": false,
        "timeOnlyEvenDays": false,
        "timeMonths": "*",
        "timedatestart": "",
        "timedateend": "",
        "property": "",
        "propertyType": "none",
        "propertyCompare": "true",
        "propertyThreshold": "",
        "propertyThresholdType": "num",
        "timeAlt": "",
        "timeAltType": "entered",
        "timeAltDays": "*",
        "timeAltOnlyOddDays": false,
        "timeAltOnlyEvenDays": false,
        "timeAltMonths": "*",
        "timeAltOffset": 0,
        "timeAltOffsetType": "none",
        "timeAltOffsetMultiplier": 60000,
        "once": false,
        "onceDelay": 0.1,
        "addPayload1": "",
        "addPayload1Type": "none",
        "addPayload1Value": "",
        "addPayload1ValueType": "date",
        "addPayload1Format": "0",
        "addPayload1Offset": 0,
        "addPayload1OffsetType": "none",
        "addPayload1OffsetMultiplier": 60000,
        "addPayload1Next": true,
        "addPayload1Days": "*",
        "addPayload2": "",
        "addPayload2Type": "none",
        "addPayload2Value": "",
        "addPayload2ValueType": "date",
        "addPayload2Format": "0",
        "addPayload2Offset": 0,
        "addPayload2OffsetType": "none",
        "addPayload2OffsetMultiplier": 60000,
        "addPayload2Next": true,
        "addPayload2Days": "*",
        "addPayload3": "",
        "addPayload3Type": "none",
        "addPayload3Value": "",
        "addPayload3ValueType": "date",
        "addPayload3Format": "0",
        "addPayload3Offset": 0,
        "addPayload3OffsetType": "none",
        "addPayload3OffsetMultiplier": 60000,
        "addPayload3Next": true,
        "addPayload3Days": "*",
        "recalcTime": 2,
        "x": 1290,
        "y": 260,
        "wires": [
            [
                "56523b6.37af8c4"
            ]
        ]
    },
    {
        "id": "7a166b0d.d50f34",
        "type": "change",
        "z": "6dce5c12.bb5e94",
        "name": "sunsetStart",
        "rules": [
            {
                "t": "set",
                "p": "payload",
                "pt": "msg",
                "to": "payload.times.sunsetStart.value",
                "tot": "msg"
            }
        ],
        "action": "",
        "property": "",
        "from": "",
        "to": "",
        "reg": false,
        "x": 1450,
        "y": 60,
        "wires": [
            [
                "c481c31a.4774f"
            ]
        ]
    },
    {
        "id": "2dfd3e6a.c59292",
        "type": "position-config",
        "z": "",
        "name": "Ingolstadt",
        "isValide": "true",
        "longitude": "0",
        "latitude": "0",
        "angleType": "deg",
        "timeZoneOffset": "99",
        "timeZoneDST": "0",
        "stateTimeFormat": "3",
        "stateDateFormat": "12"
    }
]`

**Comment by Hypnos3** [comment]
the inject node always calculates a point in time in the future, which is tomorrow or sometime later.
The sun-position node always calculates the times for the current day.

The times are different for each day, therefore the difference. It's only seconds between two days.

**Comment by Hypnos3** [comment]
Maybe I build in a selection if the time of the current day or the next value should be given.

**Comment by Missenberger79** [comment]
This will be perfect
