### ISSUE TITLE
Extract Start Time and End Time

### ISSUE THREAD

**Issue by PierreScerri** [rdmtc/node-red-contrib-sun-position#166]
How can I pass on the Start Time+Offset and the EndTime+Offset to the next node?

Thank you.

**Comment by PierreScerri** [comment]
How can I change the status to report HH:MM - HH:MM (24-hour time)?

**Comment by Hypnos3** [comment]
For which node of the package you are asking?

**Comment by PierreScerri** [comment]
Time range node

**Comment by Hypnos3** [comment]
The start and end times currently not part of the message object. I will add these to the message with the next version.

**Comment by Hypnos3** [comment]
new version will have a `withinTimeStart` and `withinTimeEnd` and `withinTime` property:
![image](https://user-images.githubusercontent.com/12692680/91233538-b7b92780-e731-11ea-8bf5-42f9911c135a.png)

![image](https://user-images.githubusercontent.com/12692680/91233587-d5868c80-e731-11ea-95ad-f04da3b0cc25.png)
