### ISSUE TITLE
Travis CI build failing

### ISSUE THREAD

**Issue by tomhoover** [rdmtc/node-red-contrib-sun-position#169]
**Describe the bug**
Travis CI build is failing for `Node.js v8`, as the latest ESLint dropped support for it.

**Screenshots**
![Screen Shot 2020-07-25 at 7 40 46 AM](https://user-images.githubusercontent.com/159040/88457217-45aba500-ce4a-11ea-95f0-4c2097e82e6a.png)

**Expected behavior**
Builds pass for both v8 and v10.

**System information (please complete the following information):**
 - Node.js v8
 - Node-Red Version: N/A

**Additional context**
I'd created a simple PR #167 to correct a link in the README; however, the Travis CI build failed for `Node.js v8` (`Node.js v10` is passing). 

Per [this ESlink blog post](https://eslint.org/blog/2020/05/eslint-v7.0.0-released), "Node.js 8 reached EOL in December 2019, and we are officially dropping support for it in this release." 

The needed correction appears to be either (1) drop v8 from `.travis.yml`, or (2) `npm install -g eslint@6` to use the older version of ESLint with Node 8 support.

**Comment by Hypnos3** [comment]
Maybe I should also drop Node.js V8 Support. As I developing and using this nodes on Node.js 10.
