### ISSUE TITLE
Witin-Time Alternate Start/End

### ISSUE THREAD

**Issue by PierreScerri** [rdmtc/node-red-contrib-sun-position#170]
**Please consider the other places for Support:**

* [RedMatic Slack (chat like WhatsApp or Facebook Messenger)](https://join.slack.com/t/homematicuser/shared_invite/enQtNDgyNDM2OTkyMDA2LWY1YjY0NTE0NmY0OWM3YWUzMzAzMTgxYmRjMTMyOWE3NjkxNDdlMDY5ZjlhYzM5Nzg2N2U2YjdmNzNlYWNhNTU)
* [RedMatic Forum](https://homematic-forum.de/forum/viewforum.php?f=77)
* [RedMatic Wiki](https://github.com/rdmtc/RedMatic/wiki)

**Describe the Problem**
When an 'Alternate Start' time with a 'Start Offset' is set, the offset is not saved.
When an Alternate End' time is set, there is no 'End Offset' visible.

**Expected behavior**
'Start Offset' should be saved.
'End Offset' should be visible.

**Screenshots**
![Screenshot 2020-07-26 at 12 52 20](https://user-images.githubusercontent.com/34303331/88477357-9fda6200-cf3f-11ea-9d39-1d923b6ae26b.jpg)

**System information (please complete the following information):**

* Version [e.g. 1.1.3]
* Node-Red Version
26 Jul 13:05:56 - [info] Node-RED version: v1.1.0
26 Jul 13:05:56 - [info] Node.js  version: v12.17.0

**Additional context**
None

**Comment by Hypnos3** [comment]
Thanks for reporting the problem. Because of vacation I will not be able to see this for the next few weeks.

**Comment by PierreScerri** [comment]
Have a good time.  See you after your vacation.
