### ISSUE TITLE
[FR] Allow override expire by rules

### ISSUE THREAD

**Issue by Hypnos3** [rdmtc/node-red-contrib-sun-position#173]
Allow a config option for overrides to be expire if position is changed by a rule (may be rule-priority).

[source](https://homematic-forum.de/forum/viewtopic.php?f=77&t=60058)

**Comment by Hypnos3** [comment]
first implementation done in 1.1.4, but not fully tested

**Comment by mivodu** [comment]
I would like to test this. Clan you please advise, how to enable this expiry on position change by rule? I couldn‘t find it in the documentation and as well don‘t see a way in the node itself (version 1.1.6).

**Comment by Hypnos3** [comment]
This can be set for every absolutely rule individually.  There is a checkbox for this in the settings dialog.  When working with priorities in overwriting, the rule must have the same or a higher priority.

**Comment by Hypnos3** [comment]
Unfortunately, the documentation is not yet up to date.  Maybe I'll get to include that in the documentation this weekend.

**Comment by hvorragend** [comment]
Is it possible to just reset the manual overwrite at a given time? It seems that the current solution is resetting each overwrite until the rule is done. 

[Source](https://homematic-forum.de/forum/viewtopic.php?f=77&t=60058&p=671381#p671381)
