### ISSUE TITLE
Error with Latitude and Longitude

### ISSUE THREAD

**Issue by josemabcn** [rdmtc/node-red-contrib-sun-position#174]
**Describe the bug**
I'm using Node Red in a Raspeberry PI 4. I installed the example 4 to control blind and setup mi time zone. When I deploy the flow appears this message:

"Error: Latitude and Longitude is wrong"
Warning; Could not evaluate msg.raining, using "undefined"

I'm living in Barcelona, Spain, and I set my Latitude and Longitude according with the configuration in the propoerty tab inside the blind node.

**System information (please complete the following information):**
 - Node Version:  Current version: 7.1.0
 - Home Assistant: Current version 3.5.0

**Additional context**

**Comment by Hypnos3** [comment]
for me this is working:
![image](https://user-images.githubusercontent.com/12692680/91229766-aae50580-e72a-11ea-8d64-dedc9e91d4e3.png)

![image](https://user-images.githubusercontent.com/12692680/91229979-ff888080-e72a-11ea-8e51-732316233534.png)

The error message "Latitude and Longitude is wrong!" comes when the coordinates are missing or the config node is not setup properly.

For further investigation i need an export of the blind-node. (The coordinates are for privacy reasons not in the export.)

**Comment by josemabcn** [comment]
Dear Hypnos3, the problem has been solved. Thanks a lot. I have another problem, but I will open another issue. Thanks
