### ISSUE TITLE
blind control: empty rule offset

### ISSUE THREAD

**Issue by mivodu** [rdmtc/node-red-contrib-sun-position#18]
When adding to a rule an offset of type 'Anzahl', the number is gone after saving:

![blind_control_empty offset](https://user-images.githubusercontent.com/47735196/57478861-4df6df00-729c-11e9-8fca-b190b5476501.JPG)

**Comment by Hypnos3** [comment]
released node-red-contrib-sun-position@0.3.0-beta-4, which should fix this issue
