### ISSUE TITLE
"Error get time: wrong type "none"=""" when I set the auto trigger option

### ISSUE THREAD

**Issue by josemabcn** [rdmtc/node-red-contrib-sun-position#180]
**Please consider the other places for Support:**
Finally I can understan more of the option for the blind controller, and they works for my awning, but when I tested all my selection I need to put the node in auto trigger option, and then the debug windows shows constantly the message "Error get time: wrong type "none"=""". But the flow continue working well.

This is the entire flow:

`[{"id":"d4a3966c.d20f08","type":"tab","label":"Flow 3","disabled":false,"info":""},{"id":"5ac9fe50.c1584","type":"inject","z":"d4a3966c.d20f08","name":"","props":[{"p":"payload"},{"p":"topic","vt":"str"}],"repeat":"","crontab":"","once":false,"onceDelay":0.1,"topic":"start/stop","payload":"0","payloadType":"num","x":175,"y":255,"wires":[["257323e8.cc8cac"]]},{"id":"46296375.c31cfc","type":"inject","z":"d4a3966c.d20f08","name":"reset","props":[{"p":"payload"},{"p":"topic","vt":"str"}],"repeat":"","crontab":"","once":false,"onceDelay":0.1,"topic":"resetOverwrite","payload":"true","payloadType":"bool","x":150,"y":345,"wires":[["257323e8.cc8cac"]]},{"id":"1ac11c0d.285d74","type":"inject","z":"d4a3966c.d20f08","name":"0%","props":[{"p":"payload","v":"0","vt":"num"},{"p":"topic","v":"levelOverwrite","vt":"string"}],"repeat":"","crontab":"","once":false,"onceDelay":0.1,"topic":"levelOverwrite","payload":"0","payloadType":"num","x":150,"y":385,"wires":[["257323e8.cc8cac"]]},{"id":"5ef15c04.d328b4","type":"inject","z":"d4a3966c.d20f08","name":"60%","props":[{"p":"payload","v":"0.6","vt":"num"},{"p":"topic","v":"levelOverwrite","vt":"string"}],"repeat":"","crontab":"","once":false,"onceDelay":0.1,"topic":"levelOverwrite","payload":"0.6","payloadType":"num","x":150,"y":430,"wires":[["257323e8.cc8cac"]]},{"id":"5bbdca3f.bf92a4","type":"comment","z":"d4a3966c.d20f08","name":"manual overrides:","info":"","x":145,"y":300,"wires":[]},{"id":"9776a19.6e85b6","type":"inject","z":"d4a3966c.d20f08","name":"90%, expire 2,5s","props":[{"p":"payload","v":"{\"position\":0.9,\"expire\":2500}","vt":"json"},{"p":"topic","v":"","vt":"string"}],"repeat":"","crontab":"","once":false,"onceDelay":0.1,"topic":"","payload":"{\"position\":0.9,\"expire\":2500}","payloadType":"json","x":180,"y":480,"wires":[["257323e8.cc8cac"]]},{"id":"843a2b6.0a143d8","type":"inject","z":"d4a3966c.d20f08","name":"30% importance 1","props":[{"p":"payload","v":"{\"position\":0.3,\"importance\":1}","vt":"json"},{"p":"topic","v":"","vt":"string"}],"repeat":"","crontab":"","once":false,"onceDelay":0.1,"topic":"","payload":"{\"position\":0.3,\"importance\":1}","payloadType":"json","x":160,"y":525,"wires":[["257323e8.cc8cac"]]},{"id":"21886442.57d07c","type":"inject","z":"d4a3966c.d20f08","name":"100% importance 1","props":[{"p":"payload","v":"{\"importance\":1, \"position\":1}","vt":"json"},{"p":"topic","v":"","vt":"string"}],"repeat":"","crontab":"","once":false,"onceDelay":0.1,"topic":"","payload":"{\"importance\":1, \"position\":1}","payloadType":"json","x":170,"y":570,"wires":[["257323e8.cc8cac"]]},{"id":"1dd9620.a2ce79e","type":"comment","z":"d4a3966c.d20f08","name":"Example 4:","info":"","x":115,"y":210,"wires":[]},{"id":"e94e166e.779dd8","type":"ha-entity","z":"d4a3966c.d20f08","name":"","server":"f6976039.c880a","version":1,"debugenabled":false,"outputs":1,"entityType":"sensor","config":[{"property":"name","value":"VarToldo2"},{"property":"device_class","value":""},{"property":"icon","value":""},{"property":"unit_of_measurement","value":""}],"state":"payload","stateType":"msg","attributes":[],"resend":true,"outputLocation":"","outputLocationType":"global","inputOverride":"allow","x":1330,"y":480,"wires":[[]]},{"id":"340460c7.58d86","type":"change","z":"d4a3966c.d20f08","name":"Level","rules":[{"t":"set","p":"payload","pt":"msg","to":"payload.level","tot":"msg"}],"action":"","property":"","from":"","to":"","reg":false,"x":1130,"y":440,"wires":[["588b20dd.639e7"]]},{"id":"588b20dd.639e7","type":"function","z":"d4a3966c.d20f08","name":"","func":"msg.payload = (msg.payload)*100;\nreturn msg;","outputs":1,"noerr":0,"initialize":"","finalize":"","x":1270,"y":620,"wires":[["d286b311.e75be","e94e166e.779dd8"]]},{"id":"d286b311.e75be","type":"debug","z":"d4a3966c.d20f08","name":"Toldo2","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"payload","targetType":"msg","statusVal":"","statusType":"auto","x":1460,"y":640,"wires":[]},{"id":"257323e8.cc8cac","type":"blind-control","z":"d4a3966c.d20f08","name":"Control Toldo Terraza","topic":"","positionConfig":"cfecfb51.96b478","outputs":2,"autoTrigger":true,"autoTriggerTime":"60000","startDelayTime":10000,"storeName":"","blindIncrement":"0.1","blindOpenPos":"1","blindClosedPos":"0","blindPosReverse":false,"blindPosDefault":"open (max)","blindPosDefaultType":"levelFixed","overwriteExpire":"","rules":[{"index":0,"name":"","isValid":false,"valid":{},"timeValue":"","timeType":"none","timeOp":0,"timeOpText":"↥ until","offsetValue":"","offsetType":"none","multiplier":60000,"timeDays":"*","timeMonths":"*","timeOnlyEvenDays":false,"timeOnlyOddDays":false,"timeDateStart":"","timeDateEnd":"","timeMinValue":"","timeMinType":"none","offsetMinValue":"","offsetMinType":"none","multiplierMin":60000,"timeMaxValue":"","timeMaxType":"none","offsetMaxValue":"","offsetMaxType":"none","multiplierMax":60000,"levelValue":"50%","levelType":"levelFixed","levelOp":2,"levelOpText":"⭱️❗ maximum (oversteer)","topic":"","importance":0,"validOperandAValue":"raining","validOperandAType":"msg","validOperator":"true","validOperatorText":"is true","validOperandBValue":"","validOperandBType":"num","valid2LogOperator":0,"valid2LogOperatorText":"N/A","valid2OperandAValue":"","valid2OperandAType":"msg","valid2Operator":"true","valid2OperatorText":"is true","valid2OperandBValue":"","valid2OperandBType":"num","description":"<div><i class=\"fa fa-code-fork\" aria-hidden=\"true\"></i> <var>msg.raining</var> is true</div><div>⭱️❗ maximum (oversteer) <var>50%</var></div>","timeMinOp":0,"timeMaxOp":0}],"sunControlMode":"2","sunFloorLength":"80","sunMinAltitude":"6","sunMinDelta":"","blindPosMin":"closed (min)","blindPosMinType":"levelFixed","blindPosMax":"open (max)","blindPosMaxType":"levelFixed","smoothTime":"","sunTopic":"","windowTop":"210","windowBottom":"10","windowAzimuthStart":"190","windowAzimuthEnd":"280","oversteerValue":"","oversteerValueType":"none","oversteerCompare":"gte","oversteerThreshold":"","oversteerThresholdType":"num","oversteerBlindPos":"open (max)","oversteerBlindPosType":"levelFixed","oversteer2Value":"","oversteer2ValueType":"none","oversteer2Compare":"gte","oversteer2Threshold":"","oversteer2ThresholdType":"num","oversteer2BlindPos":"open (max)","oversteer2BlindPosType":"levelFixed","oversteer3Value":"","oversteer3ValueType":"none","oversteer3Compare":"gte","oversteer3Threshold":"","oversteer3ThresholdType":"num","oversteer3BlindPos":"open (max)","oversteer3BlindPosType":"levelFixed","oversteerTopic":"","x":770,"y":340,"wires":[[],["340460c7.58d86"]]},{"id":"7954edf.1066014","type":"link in","z":"d4a3966c.d20f08","name":"do_refreshBlind_state","links":["5e1a797f.e1b468"],"x":595,"y":240,"wires":[["bffa7c41.9c37b","257323e8.cc8cac"]]},{"id":"bffa7c41.9c37b","type":"debug","z":"d4a3966c.d20f08","name":"Ver mensaje","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"true","targetType":"full","statusVal":"","statusType":"auto","x":760,"y":160,"wires":[]},{"id":"5e1a797f.e1b468","type":"link out","z":"d4a3966c.d20f08","name":"trigger_refreshBlind_state","links":["7954edf.1066014"],"x":955,"y":560,"wires":[]},{"id":"c54577d4.7eaf98","type":"change","z":"d4a3966c.d20f08","name":"","rules":[{"t":"set","p":"raining","pt":"msg","to":"payload","tot":"msg"}],"action":"","property":"","from":"","to":"","reg":false,"x":760,"y":640,"wires":[["5e1a797f.e1b468"]]},{"id":"21262da1.d576b2","type":"inject","z":"d4a3966c.d20f08","name":"","props":[{"p":"payload"},{"p":"topic","vt":"str"}],"repeat":"","crontab":"","once":true,"onceDelay":"0.3","topic":"is raining","payload":"true","payloadType":"bool","x":495,"y":640,"wires":[["c54577d4.7eaf98"]]},{"id":"cb36ca5e.e08d58","type":"inject","z":"d4a3966c.d20f08","name":"","props":[{"p":"payload"},{"p":"topic","vt":"str"}],"repeat":"","crontab":"","once":true,"onceDelay":"0.3","topic":"is raining","payload":"false","payloadType":"bool","x":495,"y":685,"wires":[["c54577d4.7eaf98"]]},{"id":"860616d8.a70218","type":"server-state-changed","z":"d4a3966c.d20f08","name":"","server":"f6976039.c880a","version":1,"exposeToHomeAssistant":false,"haConfig":[{"property":"name","value":""},{"property":"icon","value":""}],"entityidfilter":"variable.alarmalluvia","entityidfiltertype":"exact","outputinitially":true,"state_type":"str","haltifstate":"1","halt_if_type":"str","halt_if_compare":"is","outputs":2,"output_only_on_state_change":true,"x":220,"y":720,"wires":[["d7de1136.05f8"],[]]},{"id":"d7de1136.05f8","type":"function","z":"d4a3966c.d20f08","name":"","func":"msg.payload = true;\nmsg.topic = \"is raining\";\nreturn msg;","outputs":1,"noerr":0,"initialize":"","finalize":"","x":500,"y":720,"wires":[["d1bc0f00.f6845"]]},{"id":"d1bc0f00.f6845","type":"change","z":"d4a3966c.d20f08","name":"","rules":[{"t":"set","p":"raining","pt":"msg","to":"payload","tot":"msg"}],"action":"","property":"","from":"","to":"","reg":false,"x":760,"y":740,"wires":[["5e1a797f.e1b468"]]},{"id":"ffea9bf3.1122e8","type":"function","z":"d4a3966c.d20f08","name":"","func":"msg.payload = false;\nmsg.topic = \"is raining\";\nreturn msg;","outputs":1,"noerr":0,"initialize":"","finalize":"","x":500,"y":760,"wires":[["d1bc0f00.f6845"]]},{"id":"f54b4fb6.464d5","type":"server-state-changed","z":"d4a3966c.d20f08","name":"","server":"f6976039.c880a","version":1,"exposeToHomeAssistant":false,"haConfig":[{"property":"name","value":""},{"property":"icon","value":""}],"entityidfilter":"variable.alarmalluvia","entityidfiltertype":"exact","outputinitially":true,"state_type":"str","haltifstate":"0","halt_if_type":"str","halt_if_compare":"is","outputs":2,"output_only_on_state_change":true,"x":220,"y":780,"wires":[["ffea9bf3.1122e8"],[]]},{"id":"f6976039.c880a","type":"server","z":"","name":"Home Assistant","legacy":false,"addon":true,"rejectUnauthorizedCerts":true,"ha_boolean":"","connectionDelay":true,"cacheJson":true},{"id":"cfecfb51.96b478","type":"position-config","z":"","name":"HomeJose","isValide":"true","longitude":"0","latitude":"0","angleType":"deg","timeZoneOffset":99,"timeZoneDST":0,"stateTimeFormat":"3","stateDateFormat":"12"}]`

**System information (please complete the following information):**

Node Version 1.113.3
Node-Red Version 7.1.0

Thanks a lot in advance.

Jose

**Comment by Hypnos3** [comment]
Thank you for reporting this bug. The error is annoying, but in no way affects the function.

I will fix this in the next version.
