### ISSUE TITLE
Time Inject - Incorrect time

### ISSUE THREAD

**Issue by PierreScerri** [rdmtc/node-red-contrib-sun-position#181]
**Describe the bug**
2 Time inject nodes with settings shown in attached screenshots both show the same time in status and both trigger at this time.  One node has a time offset of -20 minutes.

**Screenshots**
![Screenshot 2020-09-02 at 09 05 41](https://user-images.githubusercontent.com/34303331/91943147-62b27e00-ecfc-11ea-8d55-a19ede9f7080.png)
![Screenshot 2020-09-02 at 09 06 07](https://user-images.githubusercontent.com/34303331/91943218-7e1d8900-ecfc-11ea-9b7f-d3b06526b0ab.png)
![Screenshot 2020-09-02 at 09 06 20](https://user-images.githubusercontent.com/34303331/91943222-7fe74c80-ecfc-11ea-9f83-b40f9951e982.png)

**Expected behavior**
Expect nodes to display correct status and trigger at the appropriate times.

**System information (please complete the following information):**
 - Node Version 1.1.6
 - Node-Red Version 1.1.3

**Additional context**
Restarted HA and Node-Red.  Issue still there.

**Comment by PierreScerri** [comment]
Tried adding a new Time-Inject.  

Set a time to 13:00 and added 10 minutes offset.  

The 10 minutes are not added.  Status shows 1:00:00.

Adding -10 minutes offset and the status shows 12:59:59

**Comment by unclej84** [comment]
Hello, same issue here - in 1.1.3 it was still working. Since upgrade to 1.1.6 it does not calculate correctly.

**Comment by PierreScerri** [comment]
Is it possible to downgrade to 1.1.3?

**Comment by unclej84** [comment]
As far as I know you can simply uninstall the new version

`npm uninstall node-red-contrib-sun-position`

 and install old version as specific via command line (not possible via gui/palette)

`npm install node-red-contrib-sun-position@1.1.3`

You should check if the changes between 1.1.3 and 1.1.6 affect you before doing.

[Npmjs.com](https://www.npmjs.com/package/node-red-contrib-sun-position?activeTab=versions) says there is 1.1.3

**Comment by PierreScerri** [comment]
I cannot remove node-red-contrib-sun-position if it is being used.
I don't fancy deleting all the nodes I'm using from the palette.
Also, as you say, I don't know if the changes affect my flows.

**Comment by unclej84** [comment]
you have to uninstall via console then the used nodes are not checked - afterwards restart nodered and you have the old version back. If it was working before the update to 1.1.6 then it should work. But make a complete backup to be sure.

**Comment by PierreScerri** [comment]
Node red is an addon to Home assistant.  Can't use the console.

**Comment by unclej84** [comment]
I have the same with RaspberryMatic (RedMatic) but I can use SSH to login to console - there should be something simmilar on Home assistant but if you are not familiar with it I guess you have to wait for the update.

**Comment by PierreScerri** [comment]
I can ssh but Hassio has limited commands.

**Comment by PierreScerri** [comment]
In the following screen grab, sunset is at 19:27:27.
The tooltip shows that the 10 minute offset is added but somehow it is not used when the node is triggered.

![Screenshot 2020-09-04 at 12 51 55](https://user-images.githubusercontent.com/34303331/92231679-7f41e800-eead-11ea-9e89-1f50331b9d97.png)

**Comment by GeorgeCastanza** [comment]
I'm seeing this as well. I've got the sunset offset by -30 and it's not changing.  

The within time node (which I presume is yours as well) does correctly offset the time. 

Latest version of enhanced inject. 

Here is a screenshot of the appropriate details from the node:
![image](https://user-images.githubusercontent.com/30585632/92300512-b93ee700-ef9e-11ea-91a6-9b381e6879c6.png)

**Comment by PierreScerri** [comment]
As an interim solution I'm using:

https://flows.nodered.org/node/node-red-contrib-eztimer

This seems to work well, but it doesn't have the same flexibility as the Time-inject node.

**Comment by Hypnos3** [comment]
Please reopen issue if Problem still occurs in Version 1.1.7
