### ISSUE TITLE
How to set min open and max open with flow variable?

### ISSUE THREAD

**Issue by squale10** [rdmtc/node-red-contrib-sun-position#184]
Hi how I can set the min and max open or close time with flow variable? it works for the offset but not for the the min and max.
The idea it is to do the setup from HOME ASSISTANT.
Thanks

**Comment by Hypnos3** [comment]
This is currently not possible I will think about to implement this in a later version.

**Comment by Hypnos3** [comment]
What can be done is to setup a rule with a minimum or a maximum Blind level:
![image](https://user-images.githubusercontent.com/12692680/93025719-b24c5000-f600-11ea-954b-2fc95e4d9b16.png)

**Comment by Hypnos3** [comment]
In the meantime there is a possibility to overwrite the most of the settings by [message object](https://github.com/rdmtc/node-red-contrib-sun-position/wiki/blind-control#advanced-overwrite-settings-by-incoming-message).

I can't think of an elegant way to use context data for this type of data. The problem here is that there is no mechanism in Node-Red to react to changes in the context of stored data.
Assuming that data from the context is used here, there is a problem with the trigger as to when it should be updated. The initial values are then also a problem. These settings are initially processed during flow. At this point in time, however, the data in the context may not yet be set.

For these reasons, the option of the setting by `msg.topic` and `msg.payload` should be sufficient for the time being. So these data needs to be send once short after flow start and if the data has changed in HOME ASSISTANT.

**Comment by chriss158** [comment]
Thanks for the change 👍 

I still don't quite get it.
Currently, I'm using 8 Blind Controllers, like in the screenshot:
![image](https://user-images.githubusercontent.com/12832850/108554638-a756c380-72f4-11eb-82a4-fea4d786f178.png)

The only difference between those 8 blind controllers are the window top/bottom/azimuth start/azimuth end and the floor length.

My goal is to use just one blind controller which is controlled by an input object with those settings. Something like this:

```json
msg = {
  "settings": {
    "windowTop": 210,
    "windowBottom": 10
 }
}
```

Is this not possible?

With this implementation it is hard to set multiple values at once. I need to send X messages to set multiple settings, which generates X output messages to control the blind.

![image](https://user-images.githubusercontent.com/12832850/108555651-0a952580-72f6-11eb-9378-bae088f33870.png)

Test and example code of "Rolladensteuerung Parameter setzen" node
```javascript
var windowSize = "small" //big
var windowDirection = "east"
var settingsToSet = [
    "setSettingsTopic",
    "setSunDataTopic",
    "setBlindSettingsTopic",
    "setWindowSettingsTop",
    "setWindowSettingsBottom",
    "setWindowSettingsAzimuthStart",
    "setWindowSettingsAzimuthEnd",
    "setSunDataFloorLength" 
]

var messages = [];
for(var setting of settingsToSet)
{
    var payload;
    var topic = setting;
    
    if(setting == "setSettingsTopic" || setting == "setSunDataTopic" || setting == "setBlindSettingsTopic")
    {
        if(windowDirection == "north") payload = "Norden";
        else if(windowDirection == "east") payload = "Osten";
        else if(windowDirection == "south") payload = "Süden";
        else if(windowDirection == "west") payload = "Westen";
    }
    else if(setting == "setWindowSettingsAzimuthStart")
    {
        if(windowDirection == "north") payload = 285;
        else if(windowDirection == "east") payload = 0;
        else if(windowDirection == "south") payload = 70;
        else if(windowDirection == "west") payload = 160;
    
    }
    else if(setting == "setWindowSettingsAzimuthEnd")
    {
        if(windowDirection == "north") payload = 360;
        else if(windowDirection == "east") payload = 160;
        else if(windowDirection == "south") payload = 250;
        else if(windowDirection == "west") payload = 340;
    }
    else if(setting == "setWindowSettingsTop")
    {
        if(windowSize == "small") payload = 210;
        else if(windowSize == "big") payload = 210;
    }
    else if(setting == "setWindowSettingsBottom")
    {
        if(windowSize == "small") payload = 100;
        else if(windowSize == "big") payload = 10;
    }
    else if(setting == "setSunDataFloorLength")
    {
        if(windowSize == "small") payload = 80;
        else if(windowSize == "big") payload = 40;
    }
    
    var message = {};
    message.topic = topic;
    message.payload = payload;
    messages.push(message);
    

}
return [messages];
```

**Comment by Hypnos3** [comment]
Ok ich werde versuchen für diese Werte, das man hier auch anstelle fester Werte flow/global/env wählen kann:
![image](https://user-images.githubusercontent.com/12692680/108598090-61e5d500-738c-11eb-8664-019b3e59865b.png)

**Comment by chriss158** [comment]
Als Eingabeparameter die zum Blindcontroller Node im Message Objekt geschickt werden klappt das nicht? Eigtl. so wie du es mit den Eingabeparameter reset, position, priority oder expire gemacht hast.

**Comment by Hypnos3** [comment]
Es gibt noch einen anderen Wunsch: Die Node soll mehr zu SubFlows kompatibel werden. Das lässt sich damit auch besser realisieren.
Der Aufwand ist nicht höher als wenn ich es so umbauen würde das es sich so wie die anderen parameter verhalten. Ich kann ja neben  flow/global/env auch die Wahl von msg anbieten. Dann kann man es auch als message property übergeben.

Ich muss dazu mir erst mal ansehen wie ich das am besten implementiere.

**Comment by Hypnos3** [comment]
Is integrated in the 2.0.0-beta and can be installed and tested. See Releases Information on how to install the beta version.
