### ISSUE TITLE
No repeat in interval between times.

### ISSUE THREAD

**Issue by PierreScerri** [rdmtc/node-red-contrib-sun-position#189]
**Describe the bug**
Interval between times is not working.  Node set as per screenshot to repeat every 150s between sunrise and sunset + 30m..

**Screenshots**
![Screenshot 2020-09-16 at 15 38 29](https://user-images.githubusercontent.com/34303331/93345306-f3c44180-f832-11ea-9652-c55bc38931d6.png)

**Expected behavior**
Repeat should repeat.

**System information (please complete the following information):**
 - Node Version 1.1.7
 - Node-Red Version 1.1.3

**Additional context**

**Comment by Hypnos3** [comment]
Thank you for reporting the problem.

Memo to myself: Problem occurs when the point in time for node-start is within start-end, because only the next start date (from the current point in time) is calculated.

**Comment by Hypnos3** [comment]
can be tested in https://github.com/rdmtc/node-red-contrib-sun-position/releases/tag/1.2.0

**Comment by GeorgeCastanza** [comment]
I know this has been fixed, but how do I get a recurring schedule when the time for node-start is within start-end?  Somebody mentioned in now deleted discussion [217 ](https://github.com/rdmtc/node-red-contrib-sun-position/discussions/217) that it was fixed. 

Say I deploy between sunrise and sunset, when the node has recurring schedule for between sunrise and sunset.

**Comment by GeorgeCastanza** [comment]
Anyone?

**Comment by Hypnos3** [comment]
which version of the node do you are using?

**Comment by GeorgeCastanza** [comment]
Latest  
1.2.4

**Comment by Hypnos3** [comment]
should be fixed in `node-red-contrib-sun-position@2.0.0-beta-8`
