### ISSUE TITLE
blind control: mixed tooltip text blindLevelMin/blindLevelMax

### ISSUE THREAD

**Issue by mivodu** [rdmtc/node-red-contrib-sun-position#19]
The tooltip for the fileds "blind level min" and "blind level max" seems to be mixed:

"blindLevelMin": "maximum position if sun calculated position"
"blindLevelMax": "minimum position if sun calculated position"

**Comment by Hypnos3** [comment]
released node-red-contrib-sun-position@0.3.0-beta-4, which should fix this issue
