### ISSUE TITLE
time-inject: alternate time not working

### ISSUE THREAD

**Issue by hmax-72** [rdmtc/node-red-contrib-sun-position#190]
it seems that the condition is not verified correctly. As a result, only the alternate time is used to trigger a message.

<img width="1477" alt="NodeRed_time_inject" src="https://user-images.githubusercontent.com/71604522/93717703-dd422100-fb77-11ea-92ae-f9b2ca3c6f72.png">

**Comment by Hypnos3** [comment]
With the latest version this works for me.
