### ISSUE TITLE
Output containing 'current' (last?) phase

### ISSUE THREAD

**Issue by lenwar** [rdmtc/node-red-contrib-sun-position#191]
**Is your feature request related to a problem? Please describe.**
N/A

**Describe the solution you'd like**
I would like the output message (payload) to contain the 'current' (or last, depending on how you look at it) solar phase. So it would contain something like:
"lastPosition: sunRise" (when the sun is between 'sunRise' and 'sunRiseEnd'), or
"lastPosition: "civilDusk" (when the sun is between 'civilDusk' and 'blueHourDuskEnd')

**Describe alternatives you've considered**
I have looked into making a number of flows and doing the above manually based upon the times provides. This is tedious to set up :-)

**Additional context**
The purpose of my request lies in usage with (for example) Home Assistant.
My idea is, that if I switch on a light, that depending on the 'current' (or last) solar state, it turns on the light at a specific luminance and/or colour temperature.
(so when I click the 'on' button for a light in the middle of the night, it will automatically turn on at a very low luminance and high colour temperature, and when I turn on that light during the day, it turns on at a higher luminance and lower colour temperature)

**Comment by Hypnos3** [comment]
I'm not sure what else to implement here. There is already the possibility to output the last and the next position of the sun. This is even possible with every change:

![image](https://user-images.githubusercontent.com/12692680/93780344-54cf8900-fc28-11ea-9f3b-db63ca5cdd5a.png)

**Comment by Hypnos3** [comment]
here the english settings:
![image](https://user-images.githubusercontent.com/12692680/93780929-0ff82200-fc29-11ea-8382-3d167fbb4531.png)

The `next sun time` is misleading, for the payload. There an object with next and last is given:
![image](https://user-images.githubusercontent.com/12692680/93781012-2aca9680-fc29-11ea-91e3-abfef575ee66.png)

**Comment by Hypnos3** [comment]
Is this what you looking for?

**Comment by lenwar** [comment]
Hi,

First off, thank you for your quick responses!

Yes and no :)
I am looking for what is called 'last' in the output, but rather than having to trigger it via "Inject Enhanced", I would like to be able to get the 'last' value when via another trigger.

So for example:
```
<All Zwave>  -> <which zwave device> -> <which button> -> <button 1> -> <last suntime> ->

  <if last suntime is solarNoon, turn on light and then set brightness to 400> or
  <if last suntime is nadir, turn on the light and set brightness to 100>
```
(etc)
 or something similar.

My initial idea was to have it added to the 'Sun position' node (and for completeness also the 'Moon position' node, though I don't have any personal use for that, but to keep them simular of course)

**Comment by Hypnos3** [comment]
This is possible by using the `time compare and change` node and configuring it as follows:
![image](https://user-images.githubusercontent.com/12692680/94126619-220bd780-fe58-11ea-9816-a8fd10a24784.png)

In this case the node only acts like a change node.

**Comment by lenwar** [comment]
Hi,

If I select 'timestamp' as input (as my zwave-buttons send out all kinds of info, but not a regular timestamp) and just don't compare it, it outputs the 'last suntime', so I can work with that. Thanks 👍
