### ISSUE TITLE
within-time documentation: What settings can be set by flow-variables?

### ISSUE THREAD

**Issue by ozett** [rdmtc/node-red-contrib-sun-position#192]
i want to use within-time in one flow and dynamically set parameter from flow-variables.

is there any place (wiki) where to see which parameter are set-able by flow-variables?
would be great to find that documented.. maybe with example flow for clearification of num/char-type...

thx

**Comment by Hypnos3** [comment]
The node compares whether the current time is within a time window and sends the message depending on this to one of the outputs.

The start end end times can be setup to be comming from message object, flow or global context.
Also the property when alternate times should be used or the alternate times itself.
![image](https://user-images.githubusercontent.com/12692680/93815396-2f597400-fc56-11ea-9244-6b609b24ccba.png)
![image](https://user-images.githubusercontent.com/12692680/93815453-47c98e80-fc56-11ea-8deb-d3d3a7a40431.png)

In the enhanced settings can be changed if for the current time not the current system time should be used:
![image](https://user-images.githubusercontent.com/12692680/93815566-79425a00-fc56-11ea-8c36-3b2fdc97296e.png)

What you cannot currently configure are the days or months.

The time information in the message object, in the global or local context can be in a format as described in the wiki: https://github.com/rdmtc/node-red-contrib-sun-position/wiki/Base-Functions#message-flow-or-global-property-or-jsonata-expression In addition, an attempt is made to interpret some date and time formats.

Will this help?

**Comment by ozett** [comment]
this helps a lot to start.


would be great to set also weekdays with a variable
( i want to set paramater for door-opening-times within one node and pass this to the flow)

but how do i put the time syntactically correct into a flow variable?

msg.starttime = str(07:55) ? num(7,55) ?

![image](https://user-images.githubusercontent.com/5937811/93855650-1da8b880-fcb8-11ea-8741-e7ab6a4439ec.png)

```
[{"id":"ca6d4f6b.e8b95","type":"inject","z":"5f4c80c5.5bca4","name":"","topic":"","payload":"7:55","payloadType":"str","repeat":"","crontab":"","once":false,"onceDelay":0.1,"x":1240,"y":1800,"wires":[["de2cba3b.347d78"]]},{"id":"d44ebd64.61a82","type":"within-time-switch","z":"5f4c80c5.5bca4","name":"MO-SO 0000:2359","positionConfig":"63cd6bf3.d04504","startTime":"starttime","startTimeType":"msg","startOffset":0,"startOffsetType":"none","startOffsetMultiplier":60000,"endTime":"23:59","endTimeType":"entered","endOffset":0,"endOffsetType":"none","endOffsetMultiplier":60000,"timeDays":"*","timeOnlyOddDays":true,"timeOnlyEvenDays":true,"timeMonths":"*","timedatestart":"","timedateend":"","propertyStart":"","propertyStartType":"none","propertyStartCompare":"true","propertyStartThreshold":"","propertyStartThresholdType":"num","startTimeAlt":"","startTimeAltType":"entered","startOffsetAlt":0,"startOffsetAltType":"none","startOffsetAltMultiplier":60000,"propertyEnd":"","propertyEndType":"none","propertyEndCompare":"true","propertyEndThreshold":"","propertyEndThresholdType":"num","endTimeAlt":"","endTimeAltType":"entered","endOffsetAlt":0,"endOffsetAltType":"none","endOffsetAltMultiplier":60000,"tsCompare":"0","x":1690,"y":1800,"wires":[["4f1acdae.678dc4"],[]]},{"id":"de2cba3b.347d78","type":"change","z":"5f4c80c5.5bca4","name":"","rules":[{"t":"move","p":"payload","pt":"msg","to":"starttime","tot":"msg"}],"action":"","property":"","from":"","to":"","reg":false,"x":1440,"y":1800,"wires":[["d44ebd64.61a82"]]},{"id":"4f1acdae.678dc4","type":"debug","z":"5f4c80c5.5bca4","name":"","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"true","targetType":"full","x":1890,"y":1800,"wires":[]},{"id":"63cd6bf3.d04504","type":"position-config","z":"","name":"GE","isValide":"true","longitude":"0","latitude":"0","angleType":"deg","timeZoneOffset":99,"timeZoneDST":0,"stateTimeFormat":"3","stateDateFormat":"12"}]
```

**Comment by Hypnos3** [comment]
for times it is the easiest to use string in one of the the formats as described here: https://github.com/rdmtc/node-red-contrib-sun-position/wiki/Base-Functions#message-flow-or-global-property-or-jsonata-expression

So best is string `07:55`

**Comment by ozett** [comment]
nice, thx. i will try.

do you consider to make weekdays set by flow?

on the wiki follows: "if it is an object, the following property's will be used if existing:"
is there an example or further explanation to something like property "lc" ???!!

**Comment by Hypnos3** [comment]
I have not yet decided whether I will enable the days of the week to be configurable. I still have to take a closer look at whether there is an easy way to do this.

There are still a few questions to be answered.
- How should it be configurable?
  - As a property of the message?
  - As a global / flow context?
  - If it is more than a property of the message, it needs to be configurable somewhere in the property dialog. How do I put that in there so that it still does is
    - understandable
    - not overloaded
- in which format should be the settings are? Internally, the days of the week are an array with the days as numerical values. `[0,1,2]` It would be easiest if the data from external is the same, so that no change be nessesary.

About the statement in the wiki: In the current version, various properties are "tried out" whether they contain a valid value:
```
    if (typeof dt === 'object') {
        if (Object.prototype.hasOwnProperty.call(dt, 'now')) {
            dt = dt.now;
        } else if (Object.prototype.hasOwnProperty.call(dt, 'date')) {
            dt = dt.date;
        } else if (Object.prototype.hasOwnProperty.call(dt, 'time')) {
            dt = dt.time;
        } else if (Object.prototype.hasOwnProperty.call(dt, 'ts')) {
            dt = dt.ts;
        } else if (Object.prototype.hasOwnProperty.call(dt, 'lc')) {
            dt = dt.lc;
        } else if (Object.prototype.hasOwnProperty.call(dt, 'value')) {
            dt = dt.value;
        } else if (Object.prototype.hasOwnProperty.call(dt, 'timeStamp')) {
            dt = dt.timeStamp;
        } else if (Object.prototype.hasOwnProperty.call(dt, 'created')) {
            dt = dt.created;
        } else if (Object.prototype.hasOwnProperty.call(dt, 'changed')) {
            dt = dt.changed;
        } else if (Object.prototype.hasOwnProperty.call(dt, 'payload')) {
            dt = dt.payload;
        } else {
            dt = String(dt);
        }
    }
```

I don't think that anyone consciously used this and I couldn't imagine any real use anymore, since you can now specify the property exactly in the settings. Therefore, I removed this already in the dev branch a few days ago, so that will no longer be available with the next version. That's why I've now removed it from the wiki.

Especially on the question `lc`. I myself use the nodes in connection with a home automation system, where the messages contain the properties ts (stand for timestamp) and lc (stand for last change timestamp).

**Comment by ozett** [comment]
why is asked:

i re-build a door opening system in node-red 
(have such already with timers in gira homeserver working for years)

i wanted to set opening times as properties in a change-node for each user.
i already set lots of parametes for door-opening and specific users and groups as property .

would be helpful for me, if i could freely set opening-days/times combination as a property 
and pass it to the within-times-node.

so to answer specific:
"property of the message" is sufficient (for me), as "flow/global context" the better...
not more than a property (at the moment) is enough
"format" should be readable and documented ! , further i dont care

![image](https://user-images.githubusercontent.com/5937811/94335081-3aefc680-ffd9-11ea-88ef-e4c0dc680a99.png)

**Comment by Hypnos3** [comment]
From the next version there will be an option to have a source for the time limitation:
![image](https://user-images.githubusercontent.com/12692680/94610112-1416e600-02a0-11eb-8528-3e327d9e6c1e.png)

more information can be found in the wiki:
https://github.com/rdmtc/node-red-contrib-sun-position/wiki/within-time#time-limit-used-from-external

Unfortunately it will take a while until I release the new version, because I still have to test a lot. Maybe I will release a beta version first. If this is the case, I'll let you know.

**Comment by ozett** [comment]
thx..ill wait for notification and test than..

**Comment by ozett** [comment]
long ago, but now i update the door-opener...

would be nice for clarification to have an example for a valid json,
wich settings for within-time could be set from a flow-variable.

documentation stops at days/monts, but also time is possible?

![image](https://user-images.githubusercontent.com/5937811/166428067-9710be90-fe10-476e-b70b-b54482878c4d.png)

**Comment by ozett** [comment]
i configured times from external flow with a missing month (5=may),
but within-time shows regardless valid. 
what do i worng?

![image](https://user-images.githubusercontent.com/5937811/166429316-fa96dede-2ac6-4d24-b123-db4bb1dea142.png)

```
[{"id":"04730a34cb5d1130","type":"inject","z":"5f4c80c5.5bca4","name":"","props":[{"p":"payload1","v":"{\"startTime\":\"23:50\",\"endTime\":\"00:05\"}","vt":"json"},{"p":"startTime","v":"23:00","vt":"str"},{"p":"payload"}],"repeat":"","crontab":"","once":false,"onceDelay":0.1,"topic":"","payload":"{\"startTime\":\"23:50\",\"endTime\":\"00:05\",\"days\":[1,2,3,4,6,0],\"months\":[0,1,2,3,4,6,7,8,9,10,11]}","payloadType":"json","x":2210,"y":1090,"wires":[["ad54406d6466ce6b"]]},{"id":"ad54406d6466ce6b","type":"within-time-switch","z":"5f4c80c5.5bca4","name":"","positionConfig":"63cd6bf3.d04504","startTime":"startTime","startTimeType":"msg","startOffset":0,"startOffsetType":"none","startOffsetMultiplier":60000,"endTime":"15:00","endTimeType":"entered","endOffset":0,"endOffsetType":"none","endOffsetMultiplier":60000,"timeRestrictions":"payload","timeRestrictionsType":"msg","timeDays":"*","timeOnlyOddDays":false,"timeOnlyEvenDays":false,"timeOnlyOddWeeks":false,"timeOnlyEvenWeeks":false,"timeMonths":"*","timedatestart":"","timedateend":"","propertyStart":"","propertyStartType":"none","propertyStartCompare":"true","propertyStartThreshold":"","propertyStartThresholdType":"num","startTimeAlt":"","startTimeAltType":"entered","startOffsetAlt":0,"startOffsetAltType":"none","startOffsetAltMultiplier":60000,"propertyEnd":"","propertyEndType":"none","propertyEndCompare":"true","propertyEndThreshold":"","propertyEndThresholdType":"num","endTimeAlt":"","endTimeAltType":"entered","endOffsetAlt":0,"endOffsetAltType":"none","endOffsetAltMultiplier":60000,"withinTimeValue":"","withinTimeValueType":"msgInput","outOfTimeValue":"","outOfTimeValueType":"msgInput","tsCompare":"0","x":2420,"y":1090,"wires":[["e4999850a17fa1d7"],[]]},{"id":"e4999850a17fa1d7","type":"debug","z":"5f4c80c5.5bca4","name":"","active":true,"tosidebar":true,"console":false,"tostatus":true,"complete":"true","targetType":"full","statusVal":"payload","statusType":"auto","x":2610,"y":1090,"wires":[]},{"id":"63cd6bf3.d04504","type":"position-config","name":"GE","isValide":"true","longitude":"0","latitude":"0","angleType":"deg","timeZoneOffset":99,"timeZoneDST":0,"stateTimeFormat":"3","stateDateFormat":"12"}]
```
