### ISSUE TITLE
Blind output with no changes between rules

### ISSUE THREAD

**Issue by Kampfschildkroete** [rdmtc/node-red-contrib-sun-position#194]
**Describe the bug**
If you have two rules with the same blind position as result the output is nevertheless triggered.

E.g.
Rule 1:
from 21 o'clock -> absolute closed
Rule 2:
from 22 o'clock -> absolute closed

After 22 o'clock the output is triggered once but the blind level wasn't changed.

**Expected behavior**
In my opinion the output shouldn't be triggered because nothing was changed.

**Comment by Hypnos3** [comment]
That is wanted behavior. The output takes place in the case of a changed position OR a changed rule.

It's because the reason has changed. If this is a problem, you can simply put an RBE node behind the node.
