### ISSUE TITLE
Enabling/disabling suncontrol sends out "1" although Rule is active (with 0.1)

### ISSUE THREAD

**Issue by guny74** [rdmtc/node-red-contrib-sun-position#208]
Merry Christmas,

I want to use the blind-controller for sunprotection (sunprotetion)  and night/day blind control (via Rules).

1.  Is it possible to activate and deactivate the procession of rules (seperatly from the sunprotection) ? At the moment I had a filter after the node, based on reason codes.

2. (more important for me): I want to activate and deactivate the suncontrol by a message.
    Based on the documentation, I send a message with "msg.mode= 2 or msg.mode =0.

   If I send a msg.mode =0 the node return a value of 1 (max open) although a rule is active (closed to 0.1)... when next automatic 
   trigger (or from outside) the node will return the the value 0.1 and the corresponding rule)

Whats did I wrong or did I missunderstood the documentation ?

Thanks you 

Regards

**********************************************************************
Redmatic Version 7.1.3
Node Red Version 1.2.6
node-red-contrib-sun-position  Version 1.1.7

**Comment by Hypnos3** [comment]
In my tests, setting `msg.mode=0` worked without any problems and kept the setting even if other messages without `msg.mode=0` arrived in between.

However, it must be noted that the setting is lost with every new deploy or node red restart.

**Comment by guny74** [comment]
Hello hymnos3,

thank you for the response...

to Anwser 1) Yes, that would be a possible solution, but then I have to put in all Rules this condition, and the conditions are limited to "2"....

to Anwser 2) I will test ist again. 

Regards

**Comment by guny74** [comment]
Hello Hypnos3,

So to Anwser 2: The Problem sat in front of the screen ( I moved the value to msg.mode  but also send an value in payload)

to Anwser 1: the restriction of to conditions brings me to an other idea. A "master" rule (with one condition) that overrules the others... would it be possible to overle a until/from conditional rule by an "master rule" with a non-from/until condition ?
If yes, where (order) I have to put the rule ?

Thank you

Regards

**Comment by Hypnos3** [comment]
If you put a rule as the first rule with only conditions and no time restriction, no other rule will be checked if the conditions of this rules are true.
If you use as shutter position N/D then the sunprotection will be still active, but no more rules.

Maybe this is what you looking for.

I am already playing with the idea of enabling more than just two conditions in a later version. In some places in the code I have already implemented this (Backend). The front end is still missing, but that also means a lot of work.

**Comment by guny74** [comment]
Thank you for help and explanation
