### ISSUE TITLE
Wrong name for 'times/nadir'

### ISSUE THREAD

**Issue by voynovia** [rdmtc/node-red-contrib-sun-position#21]
`{
"value":"2019-05-12T21:56:02.307Z",
"pos":0,
"name":"solarNoon",
"angle":270,
"ts":1557698162307
}`

**Comment by Hypnos3** [comment]
Is fixed in the latest beta.

This version can currently only be installed by command line:
```
npm install node-red-contrib-sun-position@beta
```
`

or if you using a Homematic CCU/RaspberryMatic by SSH:
```
source /usr/local/addons/redmatic/home/.profile
cd /usr/local/addons/redmatic/var
npm install --save --no-package-lock --global-style --save-prefix="~" --production node-red-contrib-sun-position@beta
```

I hopefully will release this on next weekend.

**Comment by Hypnos3** [comment]
Version 0.3.0 is released and should be available in Node-Red repository during the next few hours.
