### ISSUE TITLE
Time "frühstens (min)" via context variable?

### ISSUE THREAD

**Issue by FreeTechNick** [rdmtc/node-red-contrib-sun-position#218]
I tried to set the value for the time „frühstens (min)“ via global context variable. But no matter which type I use I always get the message undefined. If I set the value directly it works. What am I doing wrong? Thank you.

**Comment by mhop** [comment]
Works for me using `flow.... `(screenshot attached)
![image](https://user-images.githubusercontent.com/146012/107116530-1e5f7700-6874-11eb-9724-d9d7f63e17fa.png)

**Comment by FreeTechNick** [comment]
Hi Marc,

there is the same effect on your screenshot:


Does it work despite the display undefined? Another question is it possible to read out the scheduled times per payload and use them further? Thank you.

Regards Markus

**Comment by mhop** [comment]
Hi Markus,
after I've written my post I realised, you meant design-time, so I deleted the post.
I did not expect do get the value at design-time, so i have not wondered about the 'undefined'.
But at runtime it works.
Here is the screenshot I deleted:
![frühestens](https://user-images.githubusercontent.com/146012/107121581-883b4900-6893-11eb-9ab0-e34bc7627759.png)

**Comment by Hypnos3** [comment]
Problem is fixed with 1.2.0 Beta Version. (duplicate to #198)
