### ISSUE TITLE
reset when requesting position equal to automatic position

### ISSUE THREAD

**Issue by mvandenabeele** [rdmtc/node-red-contrib-sun-position#223]
I'm using the blindcontroller to open and close my covers automatically in the morning and evening. These covers can also be controlled with the push of a button. When the covers report back their position, that position is fed back to the blindcontroller with the attribute ignoreSameValue. Now, in case the cover is closed automatically and I push the button, the cover goes to the open position and the new position is set in the blindcontroller. Because it's a different position, the blindcontroller enters manual mode. Then, I push the button again (maybe I realized I pushed the wrong button when I entered the room), and the covers return to the closed position. Now, this position is fed back to the blindcontroller, but it is still in manual mode. It would be handy if the blindcontroller could detect that the cover is at the same position as it would be in automatic mode and so reset to automatic mode. For backward compatibility, this could be controlled with a new attribute, eg autoReset: true .

**Comment by Hypnos3** [comment]
I will implement a `msg.resetOnSameValue` which will reset the overwrite on same value.

**Comment by Hypnos3** [comment]
`msg.resetOnSameValue` can be tested in https://github.com/rdmtc/node-red-contrib-sun-position/releases/tag/1.2.0

I for have currently not tested `msg.resetOnSameValue`.

**Comment by mvandenabeele** [comment]
Thanks for your effort! I realy appreciate it and I will try this new version this evening, after I have figured out how to install this update in Home Assistant.

The name you choose and the code submitted however, make me think it's not completely as I had in mind. The way it's implemented, I think the node will reset after an idential position is requested twice. The value is compared to the previously requested value. I had suggested to compare against the current automatic value, which is based on sun position and rules. Glancing trough your code, I don't think this value is stored in a variable. Would need to further investigate the code to see if it's easyly done.

**Comment by mvandenabeele** [comment]
I'm getting "Error: ctrlLib.validPosition_ is not a function" when sending a message with payload { "position": 50, "ignoreSameValue": true }. Same error when sending { "position": 50, "ignoreSameValue": true, "resetOnSameValue": true }

**Comment by mvandenabeele** [comment]
Thanks for fixing the error. I tested your new version but I can't get it to reset in any way. This is the flow I tested with:

[
    {
        "id": "173ba173.59900f",
        "type": "blind-control",
        "z": "e02c5e58.56078",
        "name": "",
        "topic": "",
        "positionConfig": "23787bb9.ec4374",
        "outputs": "1",
        "autoTrigger": true,
        "autoTriggerTime": "600000",
        "startDelayTime": "0",
        "blindIncrement": "1",
        "blindOpenPos": "100",
        "blindClosedPos": 0,
        "blindPosReverse": false,
        "blindPosDefault": "open (max)",
        "blindPosDefaultType": "levelFixed",
        "overwriteExpire": "7200000",
        "rules": [
            {
                "index": 0,
                "name": "open on civilDawn, but not before 7",
                "isValid": false,
                "valid": {},
                "timeValue": "sunriseEnd",
                "timeType": "pdsTime",
                "timeOp": 0,
                "timeOpText": "↥ until",
                "offsetValue": "",
                "offsetType": "none",
                "multiplier": 1,
                "timeDays": "*",
                "timeMonths": "*",
                "timeOnlyEvenDays": false,
                "timeOnlyOddDays": false,
                "timeDateStart": "",
                "timeDateEnd": "",
                "timeMinValue": "7:00",
                "timeMinType": "entered",
                "offsetMinValue": "",
                "offsetMinType": "none",
                "multiplierMin": 60000,
                "timeMaxValue": "",
                "timeMaxType": "none",
                "offsetMaxValue": "",
                "offsetMaxType": "none",
                "multiplierMax": 60000,
                "levelValue": "closed (min)",
                "levelType": "levelFixed",
                "levelOp": 0,
                "levelOpText": "↕ absolute",
                "topic": "",
                "importance": 0,
                "resetOverwrite": false,
                "validOperandAValue": "",
                "validOperandAType": "none",
                "validOperator": "true",
                "validOperatorText": "is true",
                "validOperandBValue": "",
                "validOperandBType": "num",
                "valid2LogOperator": 0,
                "valid2LogOperatorText": "N/A",
                "valid2OperandAValue": "",
                "valid2OperandAType": "msg",
                "valid2Operator": "true",
                "valid2OperatorText": "is true",
                "valid2OperandBValue": "",
                "valid2OperandBType": "num",
                "description": "<div><i class=\"fa fa-clock-o\" aria-hidden=\"true\"></i> ↥ until <var>sunrise end</var><div class=\"indent-time-text\"><i class=\"fa fa-step-backward\" aria-hidden=\"true\"></i> <span>at the earliest (min)</span> <var>7:00</var></div></div><div>↕ absolute <var>closed (min)</var></div>",
                "timeMinOp": 0,
                "timeMaxOp": 0
            },
            {
                "index": 1,
                "name": "close civilDusk, but not later than 21:00",
                "isValid": false,
                "valid": {},
                "timeValue": "sunset",
                "timeType": "pdsTime",
                "timeOp": 1,
                "timeOpText": "↧ from",
                "offsetValue": "",
                "offsetType": "none",
                "multiplier": 1,
                "timeDays": "*",
                "timeMonths": "*",
                "timeOnlyEvenDays": false,
                "timeOnlyOddDays": false,
                "timeDateStart": "",
                "timeDateEnd": "",
                "timeMinValue": "",
                "timeMinType": "none",
                "offsetMinValue": "",
                "offsetMinType": "none",
                "multiplierMin": 60000,
                "timeMaxValue": "21:00",
                "timeMaxType": "entered",
                "offsetMaxValue": "",
                "offsetMaxType": "none",
                "multiplierMax": 60000,
                "levelValue": "closed (min)",
                "levelType": "levelFixed",
                "levelOp": 0,
                "levelOpText": "↕ absolute",
                "topic": "",
                "importance": 0,
                "resetOverwrite": false,
                "validOperandAValue": "",
                "validOperandAType": "none",
                "validOperator": "true",
                "validOperatorText": "is true",
                "validOperandBValue": "",
                "validOperandBType": "num",
                "valid2LogOperator": 0,
                "valid2LogOperatorText": "N/A",
                "valid2OperandAValue": "",
                "valid2OperandAType": "msg",
                "valid2Operator": "true",
                "valid2OperatorText": "is true",
                "valid2OperandBValue": "",
                "valid2OperandBType": "num",
                "description": "<div><i class=\"fa fa-clock-o\" aria-hidden=\"true\"></i> ↧ from <var>sunset</var><div class=\"indent-time-text\"><i class=\"fa fa-step-forward\" aria-hidden=\"true\"></i> <span>no later than (max)</span> <var>21:00</var></div></div><div>↕ absolute <var>closed (min)</var></div>",
                "timeMinOp": 0,
                "timeMaxOp": 0
            }
        ],
        "sunControlMode": "0",
        "sunFloorLength": "",
        "sunMinAltitude": "",
        "sunMinDelta": "",
        "blindPosMin": "closed (min)",
        "blindPosMinType": "levelFixed",
        "blindPosMax": "open (max)",
        "blindPosMaxType": "levelFixed",
        "smoothTime": "",
        "sunTopic": "",
        "windowTop": "",
        "windowBottom": "",
        "windowAzimuthStart": "",
        "windowAzimuthEnd": "",
        "oversteerValue": "",
        "oversteerValueType": "none",
        "oversteerCompare": "gte",
        "oversteerThreshold": "",
        "oversteerThresholdType": "num",
        "oversteerBlindPos": "open (max)",
        "oversteerBlindPosType": "levelFixed",
        "oversteer2Value": "",
        "oversteer2ValueType": "none",
        "oversteer2Compare": "gte",
        "oversteer2Threshold": "",
        "oversteer2ThresholdType": "num",
        "oversteer2BlindPos": "open (max)",
        "oversteer2BlindPosType": "levelFixed",
        "oversteer3Value": "",
        "oversteer3ValueType": "none",
        "oversteer3Compare": "gte",
        "oversteer3Threshold": "",
        "oversteer3ThresholdType": "num",
        "oversteer3BlindPos": "open (max)",
        "oversteer3BlindPosType": "levelFixed",
        "oversteerTopic": "",
        "x": 560,
        "y": 440,
        "wires": [
            [
                "f5863244.81b21"
            ]
        ]
    },
    {
        "id": "f5863244.81b21",
        "type": "debug",
        "z": "e02c5e58.56078",
        "name": "",
        "active": true,
        "tosidebar": true,
        "console": false,
        "tostatus": false,
        "complete": "payload",
        "targetType": "msg",
        "statusVal": "",
        "statusType": "auto",
        "x": 755,
        "y": 440,
        "wires": []
    },
    {
        "id": "4e460914.139678",
        "type": "inject",
        "z": "e02c5e58.56078",
        "name": "Pos 50",
        "props": [
            {
                "p": "payload"
            }
        ],
        "repeat": "",
        "crontab": "",
        "once": false,
        "onceDelay": 0.1,
        "topic": "",
        "payload": "{\"position\":50, \"ignoreSameValue\": true, \"resetOnSameValue\": true }",
        "payloadType": "json",
        "x": 270,
        "y": 440,
        "wires": [
            [
                "173ba173.59900f"
            ]
        ]
    },
    {
        "id": "f5dd4793.a80ba8",
        "type": "inject",
        "z": "e02c5e58.56078",
        "name": "Pos 0",
        "props": [
            {
                "p": "payload"
            }
        ],
        "repeat": "",
        "crontab": "",
        "once": false,
        "onceDelay": 0.1,
        "topic": "",
        "payload": "{\"position\":0, \"ignoreSameValue\": true, \"resetOnSameValue\": true }",
        "payloadType": "json",
        "x": 270,
        "y": 400,
        "wires": [
            [
                "173ba173.59900f"
            ]
        ]
    },
    {
        "id": "1f11f812.711a88",
        "type": "inject",
        "z": "e02c5e58.56078",
        "name": "Pos 100",
        "props": [
            {
                "p": "payload"
            }
        ],
        "repeat": "",
        "crontab": "",
        "once": false,
        "onceDelay": 0.1,
        "topic": "",
        "payload": "{\"position\":100, \"ignoreSameValue\": true, \"resetOnSameValue\": true }",
        "payloadType": "json",
        "x": 280,
        "y": 480,
        "wires": [
            [
                "173ba173.59900f"
            ]
        ]
    },
    {
        "id": "23787bb9.ec4374",
        "type": "position-config",
        "name": "Thuis",
        "isValide": "true",
        "longitude": "0",
        "latitude": "0",
        "angleType": "deg",
        "timeZoneOffset": "99",
        "timeZoneDST": "0",
        "stateTimeFormat": "3",
        "stateDateFormat": "12"
    }
]

Did I do something wrong?

**Comment by mvandenabeele** [comment]
To answer my own question: yes, I did something wrong. I combined ignoreSameValue and resetOnSameValue. ignoreSameValue takes precedence in code. That's a logical design decision I think. But as I feared, reset happens when a value is requested twice, while the feature request was to reset when the "autovalue at the time" is requested. The autovalue at the time is the value the cover position would be when no manual interaction had taken place.

**Comment by Hypnos3** [comment]
The order of what is evaluated first can still be changed and it probably even makes sense to turn it around. In the end, only one of the two options really makes sense, since `resetOnSameValue` automatically works like an `ignoreSameValue`.

The problem with the solution is that at the time of the evaluation of `resetOnSameValue` or` ignoreSameValue`, the shutter position is not yet fixed, as the evaluation of the rules or the calculation of the position of the sun only takes place afterwards. This has been chosen so that this calculation does not have to be carried out if there is no overwrite. What is known is the last position of the roller shutter.

To do so was a design decision. The rules and sun position calculation may needs a lot of time and ressources. I don't want to do this when it's not necessary, because these nodes should run on hardware such as the Raspberry Pi 2B or Zero.

The problem now is that the last position is caused from the last override. What you wan't to have is the position before. So one solution could be that I remember the last position without override and compare it against this. BUT: That can in turn have unwanted behavior. Example: When the shutter is closed and I open it manually and I have setup a time of 6 hours until the manual overwriting expires. Then I close the shutter manually after 5 hours, it would be bad if the `resetOnSameValue` leads to the override being lost and the shutter moving to another position.

This means that this would also have to be time-limited and the scenario would be even more complex.

If you think about it carefully, it might be better to treat the scenario externally and only tell the node if it should forget to overwrite.

**Comment by Hypnos3** [comment]
Info to @Hypnos3: :)
- rename `resetOnSameValue` to maybe something like `resetOnSameAsLastValue`, to better reflect behaviour of these setting
- change the order of the evaluation, `ignoreSameValue` after `resetOnSameAsLastValue`

**Comment by mvandenabeele** [comment]
The scenario you gave is exactly why I suggested this feature. Imagine a room with 4 windows. All covers are closed and I open 1 of the manualy. In your scenario, manual overwrite will expire in 6 hours. Now, after 5 hours, I close that cover again (at this point the new feature would do it's job). Then, after 30 minutes all covers open because of a rule or sunrise. 3 of them will do what's expected but I think it would be more logical if they all went up. I think your suggestion of storing the last position without override would be great. This can be done outside of your node ofcourse, but it makes it a lot more complicated.

I'm willing to help with this, if you could point me in the general direction.

**Comment by mvandenabeele** [comment]
That's great. Thanks!

Would you consider adding
`if (hlp.getMsgBoolValue(msg, 'resetOnSameAsAutoValue') && (node.previousData.last.level === newPos)) {`
`	node.debug('resetOnSameAsAutoValue active, reset overwrite and exit newPos=${newPos}');`
`	ctrlLib.posOverwriteReset(node);`
`	return ctrlLib.setOverwriteReason(node);`
`}`
before line 268 in blindcontroller.js? With the latest addition, it is ofcourse possible to store the last value in context, and later compare and change a msg based on the stored value. If you would be so kind as to add above lines of code, this would save 3 extra nodes per blindcontroller.

**Comment by Hypnos3** [comment]
Seems already implemented in latest beta:
```
                if (hlp.getMsgBoolValue(msg, 'resetOnSameAsLastValue') && (node.previousData.level === newPos)) {
                    node.debug(`resetOnSameAsLastValue active, reset overwrite and exit newPos=${newPos}`);
                    ctrlLib.posOverwriteReset(node);
                    return ctrlLib.setOverwriteReason(node);
                } else if (hlp.getMsgBoolValue(msg, 'ignoreSameValue') && (node.previousData.level === newPos)) {
                    node.debug(`overwrite exit true (ignoreSameValue), newPos=${newPos}`);
                    return ctrlLib.setOverwriteReason(node);
                }
```
