### ISSUE TITLE
Time by azimuth does not work

### ISSUE THREAD

**Issue by bennijamm** [rdmtc/node-red-contrib-sun-position#231]
**Describe the bug**
When I want to use the Time To Azimuth, I enter for example Start Time: 0 (degrees), End Time: 200.
The time calculation is inconsistent.
When I pass on the Start time or End Time field, I have the error:
"Cannot read property 'ts' of undefined, could not evaluate pdsTimeByAzimuth.0 start time"

**Screenshots**
![image](https://user-images.githubusercontent.com/25881082/107858156-028b4080-6e33-11eb-9d1c-6d7cd5317b3a.png)

**System information (please complete the following information):**
 - Node Version : 1.2.9

**Comment by Hypnos3** [comment]
Unfortunately, It is working for me. But I also use the latest version and there were some bug fixes for the last version.

**Comment by bennijamm** [comment]
I use the 1.1.7 version.
How up to date from 1.1.7 to the latest ?

**Comment by Hypnos3** [comment]
I have released today 1.2.2, It should be able to update over Node-Red menu. Maybe it takes some time until Node-Red recognize the new Version.

**Comment by bennijamm** [comment]
Up to date 1.2.2 and always the same error...

**Comment by bennijamm** [comment]
up !

**Comment by Hypnos3** [comment]
Could you please export your node and past it here. Maybe Tere is an internal problem with the datastructure which does not occure on my side.
