### ISSUE TITLE
overwrites of settings does not work

### ISSUE THREAD

**Issue by Hypnos3** [rdmtc/node-red-contrib-sun-position#233]
Hi, thanks for a real good node!
I use "rolladensteuerung" to control my blinds. So far works well. 
I have some trees in front of the window. When they have leafes i do not need so much shading. 
Now my idea is to set the Sunmin Altitude to dynamically to a different value. Meaning in Winter the SunMinAltitude is low in Summer it is higher to take the tree shading into account. 
According to the code it is possible to set the value by an input message. 
(...handles the input of a message object to the node
         */
        this.on('input', function (msg, send, done) {...)
So I use an simple input node to send a numeric value e.g. 50 with msg.topic "setSunDataMinAltitude". 
However it does not show any result. What I am doing wrong? Any other solutions? 
Regards Thomas

_Originally posted by @molodeztom in https://github.com/rdmtc/node-red-contrib-sun-position/discussions/225_

**Comment by molodeztom** [comment]
Thank you for a quick fix. I am going to test it today.

**Comment by Hypnos3** [comment]
If you still have a problem please reopen the issue.
