### ISSUE TITLE
within time Wochentag und Monat

### ISSUE THREAD

**Issue by niwre2019** [rdmtc/node-red-contrib-sun-position#236]
Hallo,
ich habe heute von 1.1.7 auf 1.2.2 ein Update gemacht. Leider wird jetzt eine Einschränkung auf Tage und Monate beim Node within time nicht mehr berücksichtigt, sondern nur noch die Uhrzeit.
Hat sich hier ein Fehler eingeschlichen oder hat sich grundsätzlich etwas geändert?
Gruß 
Niwre2019

**Comment by Hypnos3** [comment]
Hallo,
klingt wie ein Fehler.

Muss ich mir ansehen.
Gruß

**Comment by Hypnos3** [comment]
:man_facepalming: Der Fehler ist wirklich saublöd. Version 1.2.3 ist auf dem Weg!

**Comment by niwre2019** [comment]
Super, vielen Dank für deine schnelle Hilfe und das schnelle Update.
