### ISSUE TITLE
Window with obstruction in front

### ISSUE THREAD

**Issue by Rodrigoah** [rdmtc/node-red-contrib-sun-position#239]
**Please consider the other places for Support:**

* [RedMatic Forum](https://homematic-forum.de/forum/viewforum.php?f=77)
* [RedMatic Wiki](https://github.com/rdmtc/RedMatic/wiki)

**Describe the Problem**

Hi I want to use the blind-control node in a window that has a building in front. I want the blind to keep a constant "length on floor" but oviously this is affected by the building in front. 

Due to the building I know that once the sun is below a certain elevation, the blinds are not needed, however I am unsure on how to set this up
 
![image](https://user-images.githubusercontent.com/10799831/108360383-70e45000-71f1-11eb-9d6c-93f6d5f9e7bf.png)

**Expected behavior**

**Screenshots**

**System information (please complete the following information):**

* Version [e.g. 0.4.7]
* Node-Red Version

**Additional context**

**Comment by Hypnos3** [comment]
Exactly for such a case there is the setting of the `min altitude threshold`:
![image](https://user-images.githubusercontent.com/12692680/108384661-3f787e00-720b-11eb-970a-e41c927a2f74.png)

[wiki](https://github.com/rdmtc/node-red-contrib-sun-position/wiki/blind-control#restrict-sunlight-summer)

I use this on myself for a hill outside a window.

**Comment by HubertusH** [comment]
Hi Hypnos3,

additionally, some kind of "ceiling" would be good. We have a very low-hanging roof and so the sun is above the roof in summer and no sun rays fall into the room. According to sunpos, however, "sun in window" is set and the shutter closes.

That would be great if you could still install that.

Thanks and greetings
Hubertus

**Comment by Hypnos3** [comment]
Vielleicht kann man das ja bereits mit oversteer lösen. (Oversteer ist ein überschreiben der Sonnensteuerung - mir viel kein besserer Begriff ein). Muss ich mir selbst noch mal ansehen. Da ich aktuell gerade unbegrenzte oversteer einbaue könnte ich damit auch die minimale altitude Grenze ersetzen.

**Comment by Hypnos3** [comment]
I've tested it and with the "oversteer" it can be easily solved. With the next version the setting `min altitude threshold` will disappear and be replaced by oversteer.

Existing settings are automatically adopted as the highest priority, which also corresponds to the current behavior.

---

Ich hab es getestet und mit den "oversteer" lässt es sich einfach lösen. Mit der nächsten version wird die Einstellung `min altitude threshold` verschwinden und durch oversteer abgelöst.

Vorhandene Einstellungen werden als höchster Priorität automatisch übernommen, was auch dem jetzigen verhalten entspricht.

![image](https://user-images.githubusercontent.com/12692680/110256666-599bb580-7f9a-11eb-9758-e88d244f6828.png)
