### ISSUE TITLE
getting "internal error time-span:Cannot read property 'type' of undefined" when using calculated output value

### ISSUE THREAD

**Issue by guny74** [rdmtc/node-red-contrib-sun-position#240]
Using the time-span node, I want to send out as output the time difference of the 2 inputs time values in seconds,
I got an

`internal error time-span:Cannot read property 'type' of undefined`

Also other output variant throw this error. Only removing the the output ( = delivery input message) 
removes the error...but I need the difference in seconds.

In the past I got the seconds of time diffence correctly

![image](https://user-images.githubusercontent.com/30338811/108590140-45cd3e00-7362-11eb-9e7f-74701e0c2865.png)

**System information (please complete the following information):**
 - Node Version 1.2.3
 - Redmatic 7.1.3

Thank you

**Comment by Hypnos3** [comment]
Thank You!
I will fix in next Version asap!

**Comment by guny74** [comment]
It works again...thank you
