### ISSUE TITLE
I have a Building in Front of the Window ---

### ISSUE THREAD

**Issue by HubertusH** [rdmtc/node-red-contrib-sun-position#243]
we have a building in front of the window and would like to have so two opening angles. First from the left (sunrise) to the building, then shutter open and then from the building right to the sunset.

BR
Hubertus

**Comment by mvandenabeele** [comment]
Couldn't that be solved with a rule like this: 
![image](https://user-images.githubusercontent.com/6908633/109189007-d1e0ca80-7793-11eb-9d4a-d7726614a194.png)

**Comment by HubertusH** [comment]
Thank you - i will try this.
