### ISSUE TITLE
Rolladensteuerung Winkel und Höhe

### ISSUE THREAD

**Issue by dewebby** [rdmtc/node-red-contrib-sun-position#244]
Hallo, vielen Dank für den tollen Node.

Ich komme gerade nicht weiter.

Ich möchte den Rolladen (unterschiedliche Höhe) in Abhängigkeit von der Sonnenhöhe steuern. Soweit so gut
![Rolladen1](https://user-images.githubusercontent.com/79706481/109310825-517aa200-7845-11eb-890c-723c3d3b2b0b.jpg)

Jetzt soll diese Regel aber nur gelten, wenn die sonne im Bereich 120° bis 180° ist, ich bekomme dies einfach nicht hin ... bin ein allerdings sowohl Anfänger als auch DAU

Habe hier time by azimuth probiert, finde aber keine Hinweise, wie dies zu verwenden ist.
![Rolladen2](https://user-images.githubusercontent.com/79706481/109311264-e382aa80-7845-11eb-83da-6e526d60b70c.jpg)

Vielen Dank und sorry my english is bad, so i write german
node Red Vers. 8.x
contrib-sun-position Vers 1.2.4

**Comment by mvandenabeele** [comment]
I'm sorry if I didn't understand your question, and I might not have an answer. I just noticed the icon is of 'time by altitude' while the text says 'time by azimuth'. Maybe that is a bug in the blindcontroller?

![image](https://user-images.githubusercontent.com/6908633/109377580-82ea8080-78cc-11eb-89d2-1d524dcea3c9.png)

**Comment by Hypnos3** [comment]
There seems to be a bug. Because there is an error in your screenshot. Normally in the description of the rule should be displayed the calculated time for today.

**Comment by dewebby** [comment]
I would like to control the blinds during azimuth 120° to 180° the altitude depending on the elevation of the sun. (deepl thanks ;-) )

**Comment by Hypnos3** [comment]
Ich hab mir das nochmal angesehen und bei mir kommt mit der neusten version der Node folgendes raus:
![image](https://user-images.githubusercontent.com/12692680/110383389-78628080-805c-11eb-92bd-c45b9f0d9431.png)

Das funktioniert auch.

**Comment by dewebby** [comment]
Danke, sieht mir so aus, dass ich auf jeden Fall ne andere Version habe, aber über hass.io wird kein update angezeigt ... habe mir jetzt was zurecht gepfuscht :-( 

![grafik](https://user-images.githubusercontent.com/79706481/110430838-3f9ec780-80ad-11eb-876a-28224af8b0d4.png)

**Comment by hvorragend** [comment]
Eine Frage in die Runde:
Ist es üblich, die Beschattung auf Basis der Sonnendaten (und vielleicht auch weitere Sensoren) über eigene Regeln umzusetzen? 

Oder nutzt man dafür eher das "Restrict sunlight" in Kombination mit Übersteuern/Oversteering?

**Comment by Hypnos3** [comment]
Is integrated in the 2.0.0-beta and can be installed and tested. See Releases Information on how to install the beta version.
