### ISSUE TITLE
SleepingMode Rolladen sollte geschlossen bleiben.

### ISSUE THREAD

**Issue by Dominik2000** [rdmtc/node-red-contrib-sun-position#256]
Hallo,

ich hätte aus meiner Sicht keine so schwere Anforderung kriege es aber mit den Regeln einfach nicht hin. Ich will, dass die Jalousien   bei Sonnenuntergang und aber spätestens um 20:00 Uhr schließen und dass die Jalousien bis Sonnenaufgang bzw. um 07:00 geöffnet werden. Soweit alles gut, weiters habe ich einen "SleepingMode", der angibt ob aktuell geschlafen wird oder nicht. Wenn der Flag auf true steht, darf die Jalousie nicht aufgehen. Mit der aktuellen Einstellung die ich habe, passiert das aber leider trotzdem. Es ist sicher nur eine Kleinigkeit nur finde ich sie nicht.

![image](https://user-images.githubusercontent.com/2236311/111970890-1560f700-8afc-11eb-8da9-82d999cba184.png)

Kann mir hier bitte jemand helfen? Vielen Dank!

Dominik

**Comment by Hypnos3** [comment]
Sollte so funktionieren.
Die Regeln kann man jedoch "überschreiben". Damit werden diese unwirksam.

**Comment by Dominik2000** [comment]
Aber wieso, ich habe jetzt sogar die 2te und 3te Regel auf sleepingMode is false limitiert, funktioniert trotzdem nicht.

Hier meine "Logik":
![image](https://user-images.githubusercontent.com/2236311/112475280-ec956780-8d70-11eb-82f5-d5a7bb854660.png)

Was brauchst du denn noch für Informationen? Damit ich sie nachreichen kann.

**Comment by Hypnos3** [comment]
Du fragst nach `global.SleepingMode`, aber wird das wirklich auf einen globalen Context geschrieben? Das scheint bei dir als Eingabe in die Blind node direkt reingehen und müsste dann `msg...` sein.

**Comment by Dominik2000** [comment]
It was the parsed data from mqtt which was not correct. Very silly error. Sorry for posting, and thank you very much!
