### ISSUE TITLE
Moon "set" time is showing to be 12 hours prior to "rise" time ?? 

### ISSUE THREAD

**Issue by GasTurbineMan** [rdmtc/node-red-contrib-sun-position#257]
**Describe the bug**
New user for your Sun-Position utility and mainly using it for tracking Moon Phases.  The current output is showing that the moon rises on 2021-03-29 00:50 and sets on 2021-03-28 12:34 ?? 

**Screenshots**
Screenshot attached showing json output.
![MoonTimes](https://user-images.githubusercontent.com/39521420/112761241-0aa4d700-8fc0-11eb-8bc7-87e6bbfe30dc.png)

**Expected behavior**
 Maybe I don't understand, but these times seem incorrect to me as I would think the rise time would be prior to the set time.

**System information (please complete the following information):**
 - Node Version [e.g. 0.4.7]   1.2.4
 - Node-Red Version              1.2.7

**Additional context**

**Comment by Hypnos3** [comment]
what is right and what is wrong depends on the point of view. For a day, the moon will be set in the morning and rise in the evening.
In the next version is a "timesNext" which contains the next times.

**Comment by Hypnos3** [comment]
Is integrated in the 2.0.0-beta and can be installed and tested. See Releases Information on how to install the beta version.
