### ISSUE TITLE
[FR] Altitude percent include nadir

### ISSUE THREAD

**Issue by ElGranLoky** [rdmtc/node-red-contrib-sun-position#259]
**Is your feature request related to a problem? Please describe.**
altitudepercent only get positive values (noon altitude), it can use negative values for nadir instead 0.

**Describe the solution you'd like**
Get negative values in altitudepercent for nadir.

![image](https://user-images.githubusercontent.com/2712200/112969390-7d8f8880-914d-11eb-8d5a-7a5997d488ce.png)

**Describe alternatives you've considered**
Use https://github.com/claytonjn/hass-circadian_lighting to get the values.

**Comment by Hypnos3** [comment]
will be in the next release (2.0.0 beta-3 or later)
