### ISSUE TITLE
Blind Controller schließt bei Astronomical-Dusk Vormittags

### ISSUE THREAD

**Issue by Hypnos3** [rdmtc/node-red-contrib-sun-position#26]
Issue an mich selbst. 
Blind Controller hat Rolladen unerwartet geschlossen. 

Astronomical-Dusk hatte am 8.6.2019 gegen 10 Uhr einen Wert von 12:...AM in 'From' Regel = close Blind. Erwartet war ein Wert von ~23 Uhr. Die 12Uhr AM sind vermutlich 0:..Uhr nächster Tag (Datum habe ich nicht gesehen). Blind Controller muss beim Zeitvergleich das Datum mit berücksichtigen. 

Ähnliches ist bei der Within Time Node zu prüfen, da beide die selbe Funktion zum Zeitvergleich haben ist dort der Fehler auch zu erwarten. 

Problem nachstellen im Testsystem.

**Comment by mivodu** [comment]
Ich glaube bei dem time inject node muss das bei den additional properties auch berücksichtigt werden. Ich gebe dort die on_time bis z.B. BlueHourDawnEnd mit. Sollte dies vor dem ausführungszeitpunkt liegen, dann wird hier der Wert bis zum BlueHourDawnEnd des nächsten Tages genommen. (Als Workaround prüfe ich ob der Wert größer als eine obere Grenze ist)

**Comment by Hypnos3** [comment]
für BlindControl fixed mit 0.3.2

@mivodu : Die Frage ist, wie sollte es denn sein?
Gedacht ist es so, dass die ON_TIME vom Inject bis zum nächsten Zeitpunkt wie eingestellt ausgegeben wird. Wenn die BlueHourDawnEnd jetzt am Aktuellen tag vorbei ist, ist die nächste am nächsten Tag und es wird die Differenz dazu ausgegeben. Alternativ könnte ich jetzt auch einen negativen Wert ausgeben, aber ist das besser?

**Comment by mivodu** [comment]
Vielleicht als feature für eine der nächsten Versionen? Man kann wählen, ob nur Zeitpunkte des gleichen Tages berücksichtigt werden sollen?
Oder gibt es eine einfache Lösung für die on_time von 07:00 - Sonnenaufgang? Das klappt im Winter ganz gut, im Sommer wird dann von 07:00 Uhr bis zum nächsten Tag Sonnenaufgang geschaltet (was so nicht gewünscht ist).

**Comment by Hypnos3** [comment]
Ich kann mal sehen ob ich noch eine Option eingebaut bekomme.

Ich denke, ich hab das auch erst vor kurzem eingebaut, das die zeit [zum nächsten Tag](https://homematic-forum.de/forum/viewtopic.php?f=77&t=50950) genommen wird.

Ich kann die aber schon sagen, das diese Option bedeutet, dass eine negative Zeitdifferenz ausgegeben werden wird, wenn der Vergleichs-Zeitpunkt (Bsp. Sonnenaufgang) vor dem Inject Zeitpunkt (Bsp. 7 Uhr) liegt.

Am Ende kommt es auf die Anforderung an und die kann ja sehr verschieden sein.

* negative Zeit ausgeben - kann ja gewollt sein
* keine zusätzliche zeit - ohne ON_TIME
* überhaupt kein Inject - es soll nicht geschaltet werden

Die Node sollen ja allgemein gültig für viele Nutzer und Anforderungen gültig sein und am Ende ist es nicht schlecht noch eine paar zusätzliche Nodes im Flow zu haben. Dadurch wird das ganze verständlicher.

**Comment by Hypnos3** [comment]
Ist jetzt mit Version 0.4.0 implementiert:
![image](https://user-images.githubusercontent.com/12692680/59639070-6939f180-915a-11e9-8cb0-dd048ae02848.png)
