### ISSUE TITLE
Blind Controller: errors.usingTempValue

### ISSUE THREAD

**Issue by holgerpieta** [rdmtc/node-red-contrib-sun-position#262]
**Describe the bug**
After configuring sun position oversteers using msg.temperature and msg.effective_cloud_cover as parameters and sending an appropriate message to the node, I get the following on the logs every time the node runs (automatically):
```
[info] [blind-control:Rollo3] errors.usingTempValue
[info] [blind-control:Rollo3] errors.usingTempValue
```
(Two lines each time the node executes.)

Currently I do not see any other malfunction of the node, but then none of the oversteers has triggered yet, so I do not know if they work.
But anyway, throwing error messages either indicates a problem or the error message itself is a bug.

I've tried to find the place in the code causing that, but the only matching place is timeControlHelper.js line 47 and that doesn't look exactly right to me.

While the controller was running in sun control mode, the node's context cache data looked correct to me, containing both msg.temperature and msg.effective_cloud_cover. But now, after it switched sun control off because of low sun altitude, it's actually empty and stays empty, even if I send a message. Not sure that's expected behavior, because it looks like it will ignore message data when the last message arrived before switching to active sun control mode.

**Expected behavior**
No error message.

**System information (please complete the following information):**
 - Node Version: As shipped with node-red Docker container.
 - Node-Red Version: v1.3.1

**Additional context**
If there is anything else you need to find the problem, let me know and I'll try to deliver.

**Comment by holgerpieta** [comment]
"No sun in window" also seems to reset and lock cacheData to {empty}.

**Comment by holgerpieta** [comment]
OK, I can confirm, when sun control is not overridden by normal rules, but not actually active because sun is not in window or below minimum altitude, cached data is discarded and ignored. So oversteers will only work after the first message arrives after the node switches to full sun control.

**Comment by holgerpieta** [comment]
Data caching just doesn't seem to be working reliably at all. Even if auto triggering just recalculates the current sun position (i.e. not mode change or anything) it occasionally forgets the cached data.
I tried to switch to pure manual triggering, but even switching off auto trigger doesn't seem to work.
Maybe nobody is using this node seriously, but it seems to be broken at a lot of places.

**Comment by Hypnos3** [comment]
Needs to be tested. It would be helpful to have an Example flow to test this.

**Comment by Hypnos3** [comment]
I have tested this and this is working.

The cached data is stored in the nodes context and can be shown there:
![image](https://user-images.githubusercontent.com/12692680/133820185-3d93e2b4-c883-469d-9091-2deff4c169a3.png)

**Comment by Hypnos3** [comment]
Maybe last beta is needed.

**Comment by holgerpieta** [comment]
Sorry for my late reply, I've been on vacation.
Anyway, I've stopped using the node because I noticed that it does not consider azimuth when calculating radiation incident on the window. So I've switched to using my own calculation.
So I cannot test it in the moment. As long as nobody complains, we can probably consider it fixed when it works for you.

**Comment by Hypnos3** [comment]
Maybe you can share your own calculations and I can see to what extent I can integrate this into the node.

Regardless of this, you can use the oversteer function in the node to store rules that the sun control is only active in certain azimuth ranges.
