### ISSUE TITLE
Blind Controller: Using lux-sensor in combination with blind-controller.

### ISSUE THREAD

**Issue by Chrischi-** [rdmtc/node-red-contrib-sun-position#263]
How can I use the Blind Controller in combination with my Lux Sensor.

When I create a rule then this rule is observed and executed but i still want smoothing, 
if it is only briefly cloudy and thus the lux value changes briefly.

Currently, after the rule execution, it directly aborts and the specified action 
is executed without considering the smoothing value.

Can someone give me a hint here? How did you implement something like this?

**Comment by Chrischi-** [comment]
i used "oversteer"

**Comment by Hypnos3** [comment]
that's exactly what it's for, among other things

**Comment by hvorragend** [comment]
But for me it looks like that oversteer does not consider the smoothing value. Refs #288
