### ISSUE TITLE
time as ECMA-262 formated string not being parsed

### ISSUE THREAD

**Issue by litinoveweedle** [rdmtc/node-red-contrib-sun-position#272]
**Describe the bug**
based on [documentation](https://github.com/rdmtc/node-red-contrib-sun-position/wiki/Base-Functions#input-parse-formats) I am trying to parse msg.payload containing time as string in ECMA-262 format like: YYYY-MM-DDTHH:mm:ss.sssZ Unfortunately node (in this case time-span) is failing with message:

"internal error time-span:Error "could not evaluate format of 2021-05-17T08:45:00.000Z (1)", could not evaluate msgPayload."

**Expected behavior**

As far as I understand documentation strings in ECMA-262 format like "2021-05-17T08:45:00.000Z" shall be parsed.

**System information (please complete the following information):**
 - Node Version 1.2.4
 - Node-Red Version 1.3.3

**Additional context**

<code>
[{"id":"9e9a1b57.0be7d8","type":"tab","label":"Flow 1","disabled":false,"info":""},{"id":"132a92bb.b271bd","type":"inject","z":"9e9a1b57.0be7d8","name":"","props":[{"p":"payload"}],"repeat":"","crontab":"","once":false,"onceDelay":0.1,"topic":"","payload":"2021-05-17T08:45:00.000Z","payloadType":"str","x":200,"y":440,"wires":[["1ddeb92e.1d5587"]]},{"id":"1ddeb92e.1d5587","type":"time-span","z":"9e9a1b57.0be7d8","outputs":2,"name":"","positionConfig":"58fa964e.c22b78","operand1":"","operand1Type":"msgPayload","operand1Format":"1","operand1Offset":0,"operand1OffsetType":"none","operand1OffsetMultiplier":60000,"operand2":"","operand2Type":"date","operand2Format":"0","operand2Offset":0,"operand2OffsetType":"none","operand2OffsetMultiplier":60000,"rules":[{"operator":"1","operatorText":"==     (equal)","operandType":"num","operandValue":"1","multiplier":"60000"}],"checkall":"true","result1":"","result1Type":"msgPayload","result1Value":"","result1ValueType":"timespan","result1TSFormat":1,"result1Format":0,"result1Offset":0,"result1OffsetType":"none","result1OffsetMultiplier":60000,"x":520,"y":440,"wires":[[],[]]},{"id":"58fa964e.c22b78","type":"position-config","name":"","isValide":"true","longitude":"0","latitude":"0","angleType":"deg","timeZoneOffset":"99","timeZoneDST":"0","stateTimeFormat":"3","stateDateFormat":"12"}]
</code>

**Comment by kadenbach** [comment]
Just can confirm this bug. I think it's based on definition of "T" which will fail:
- T | Uppercase, single-character time marker string: A or P.

**Comment by Hypnos3** [comment]
Is integrated in the 2.0.0-beta and can be installed and tested. See Releases Information on how to install the beta version.
