### ISSUE TITLE
Blind Controller bedingt steuern

### ISSUE THREAD

**Issue by RS208** [rdmtc/node-red-contrib-sun-position#280]
Hallo,
ich habe begonnen, meine Rollladen mit  Blind Controller zu steuern.
hier ein paar kurze Fragen.
Wie kann ich den Controller aktiv und inaktiv setzen.
Ich würde gerne eine Hand/Automatik einbauen, also bei Automatik steuert der Controller, bei Hand wird alles manuell geregelt.
Geht das? Welchen Befehl muss ich hierzu an den Controller schicken?

Kann man den Controller mit einem Helligkeitssensor koppeln, dass bei Regen oder bewölktem Wetter bestimmte Regeln nicht greifen? Wie kann man das am besten Lösen?
Gibts Empfehlungen für einen Helligkeitssensor?
Vielen Dank für Eure Hilfe!
RS208

**Comment by Hypnos3** [comment]
Hallo,

zur 1. Frage, das einfachste wäre es nach der Node einen Switch node, welche die Steuerbefehle nur im Automatikmodus durchlässt. Das ist auch am übersichtlichsten.

Alternative Möglichkeit:
Eine Regel am Anfang erstellen, die "im Manuellen modus" aktiv wird und eine feste Rollladenposition hat. Aktuell ist es so nicht möglich das komplett abzuschalten. Man kann damit die Regeln abschalten, so das nur das Überschreiben oder die Sonnensteuerung aktiv ist oder man kann damit eine minimale oder maximale Rollladenposition vorgeben:
![image](https://user-images.githubusercontent.com/12692680/121813922-a31d3000-cc6e-11eb-95e0-a193f8a69786.png)

Ich nehme es mal auf die ToDo, dort eine Möglichkeit für "mach überhaupt nix" zu haben.

Zur 2. Frage:
- Ja, den Controller kann man mit einem Helligkeitssensor koppeln. Beispielsweise die Helligkeit als Bedingung in den Regeln mit hinzugefügen.
- Alternativ kann der Helligkeitssensor in der Übersteuerung der Sonnenposition verwendet werden.
Wie man diesen einsetzt, kommt auf das gewünschte Verhalten an. Wenn man nur die Sonnensteuerung "Übersteuern" will, nimmt man das Übersteuern, so kann man das Schließen nach Sonnenposition abschalten, wenn es beispielsweise "zu dunkel" ist oder den Rollladen komplett schließen wenn es zu Hell ist:
![image](https://user-images.githubusercontent.com/12692680/121813854-39048b00-cc6e-11eb-88ba-eec100e861d1.png)

Setzt man die Helligkeit in den Regeln ein, kann man noch mehr überschreiben. Beispielsweise die Rollläden morgens später öffenen, wenn es draußen dunkel ist.

Der Phantasie sind keine Grenzen gesetzt.
