### ISSUE TITLE
Rollo fährt um 0:00 Uhr automatisch zu

### ISSUE THREAD

**Issue by hvorragend** [rdmtc/node-red-contrib-sun-position#281]
**Describe the bug**
Ich habe Türen, die mit dem blind-control ausschließlich geöffnet werden sollen.
Eine Fahrt nach unten soll darüber nicht ausgeführt werden.
Jedoch fährt das Rollo plötzlich um 00:0x Uhr eigenständig auf die Position 0 herunter.

**Expected behavior**
Das Rollo sollte eigentlich oben bleiben bis zur manuellen Schließung.

Kannst du einen Fehler erkennen?

**System information (please complete the following information):**
 - Node-Red Version 1.3.5 (in Home Assistant)

`[{"id":"ec29b187.57e99","type":"blind-control","z":"abeb29cc.4c9a78","name":"Küchentür","topic":"","positionConfig":"d9e9ca6a.952218","outputs":"1","autoTrigger":true,"autoTriggerTime":"600000","startDelayTime":"30000","storeName":"","blindIncrement":"0.01","blindOpenPos":"1","blindClosedPos":0,"blindPosReverse":false,"blindPosDefault":"open (max)","blindPosDefaultType":"levelFixed","overwriteExpire":"","rules":[{"index":0,"name":"zu bis 07:00","isValid":false,"valid":{},"timeValue":"07:00","timeType":"entered","timeOp":0,"timeOpText":"↥ bis","offsetValue":"","offsetType":"none","multiplier":60000,"timeDays":"*","timeMonths":"*","timeOnlyEvenDays":false,"timeOnlyOddDays":false,"timeDateStart":"","timeDateEnd":"","timeMinValue":"","timeMinType":"none","offsetMinValue":"","offsetMinType":"none","multiplierMin":60000,"timeMaxValue":"","timeMaxType":"none","offsetMaxValue":"","offsetMaxType":"none","multiplierMax":60000,"levelValue":"closed (min)","levelType":"levelFixed","levelOp":0,"levelOpText":"↕  Absolut","topic":"","importance":0,"resetOverwrite":true,"validOperandAValue":"","validOperandAType":"none","validOperator":"true","validOperatorText":"ist true","validOperandBValue":"","validOperandBType":"num","valid2LogOperator":0,"valid2LogOperatorText":"N/A","valid2OperandAValue":"","valid2OperandAType":"msg","valid2Operator":"true","valid2OperatorText":"ist true","valid2OperandBValue":"","valid2OperandBType":"num","description":"<div><i class=\"fa fa-clock-o\" aria-hidden=\"true\"></i> ↥ bis <var>07:00</var></div><div>↕  Absolut <var>geschlossen (min)</var><div class=\"indent-resetOverwrite-text\"> <span>manuelle Überschreibung verfällt wenn die Regel aktiv wird</span> </div></div>"},{"index":1,"name":"zu bis 07:30 WE / FT","isValid":false,"valid":{},"timeValue":"07:30","timeType":"entered","timeOp":0,"timeOpText":"↥ bis","offsetValue":"","offsetType":"none","multiplier":60000,"timeDays":"*","timeMonths":"*","timeOnlyEvenDays":false,"timeOnlyOddDays":false,"timeDateStart":"","timeDateEnd":"","timeMinValue":"","timeMinType":"none","offsetMinValue":"","offsetMinType":"none","multiplierMin":60000,"timeMaxValue":"","timeMaxType":"none","offsetMaxValue":"","offsetMaxType":"none","multiplierMax":60000,"levelValue":"closed (min)","levelType":"levelFixed","levelOp":0,"levelOpText":"↕  Absolut","topic":"","importance":0,"resetOverwrite":true,"validOperandAValue":"day.today.isWeekendOrHoliday","validOperandAType":"global","validOperator":"true","validOperatorText":"ist true","validOperandBValue":"","validOperandBType":"num","valid2LogOperator":0,"valid2LogOperatorText":"N/A","valid2OperandAValue":"","valid2OperandAType":"msg","valid2Operator":"true","valid2OperatorText":"ist true","valid2OperandBValue":"","valid2OperandBType":"num","description":"<div><i class=\"fa fa-code-fork\" aria-hidden=\"true\"></i> <var>global.day.today.isWeekendOrHoliday</var> ist true</div><div><i class=\"fa fa-clock-o\" aria-hidden=\"true\"></i> ↥ bis <var>07:30</var></div><div>↕  Absolut <var>geschlossen (min)</var><div class=\"indent-resetOverwrite-text\"> <span>manuelle Überschreibung verfällt wenn die Regel aktiv wird</span> </div></div>"}],"sunControlMode":"0","sunFloorLength":"90","sunMinAltitude":"33","sunMinDelta":"0.2","blindPosMin":"open (max)","blindPosMinType":"levelFixed","blindPosMax":"open (max)","blindPosMaxType":"levelFixed","smoothTime":"21600000","sunTopic":"","windowTop":"250","windowBottom":"150","windowAzimuthStart":"245","windowAzimuthEnd":"360","oversteerValue":"homeassistant.myHomeAssistant.states[\"sensor.lichtsensor_westen_statistik\"].state","oversteerValueType":"global","oversteerCompare":"gte","oversteerThreshold":"70000","oversteerThresholdType":"num","oversteerBlindPos":"50%","oversteerBlindPosType":"levelFixed","oversteer2Value":"","oversteer2ValueType":"none","oversteer2Compare":"gte","oversteer2Threshold":"80","oversteer2ThresholdType":"num","oversteer2BlindPos":"open (max)","oversteer2BlindPosType":"levelFixed","oversteer3Value":"","oversteer3ValueType":"none","oversteer3Compare":"gte","oversteer3Threshold":"","oversteer3ThresholdType":"num","oversteer3BlindPos":"open (max)","oversteer3BlindPosType":"levelFixed","oversteerTopic":"","x":620,"y":2040,"wires":[["cb82cd92.90c6","95dbbff4.0724e"]]},{"id":"d9e9ca6a.952218","type":"position-config","name":"myHome","isValide":"true","longitude":"","latitude":"","angleType":"deg","timeZoneOffset":99,"timeZoneDST":0,"stateTimeFormat":"3","stateDateFormat":"12"}]`

**Comment by Hypnos3** [comment]
maybe releated to #155

**Comment by hvorragend** [comment]
Is there something I can do?
Do you need a tester?

**Comment by hvorragend** [comment]
Am Rande: Der Fehler tritt bei mir auch auf, wenn ich die Regel 2 mit der Limitierung `day.today.isWeekendOrHoliday` entferne.
Ich habe deine Loop-Start/Stop-Funktion dazugeschaltet und habe die Debug-Ausgabe beobachtet.

**Comment by hvorragend** [comment]
Auch wenn ich die Regeln umdrehe und "auf ab 07:00 Uhr" darauf mache, so wird um 0:00 Uhr getriggert. Nur dann halt mit payload:1. 

`[{"id":"3b6ec4fa.6fddbc","type":"blind-control","z":"abeb29cc.4c9a78","name":"HWR Tür","topic":"","positionConfig":"d9e9ca6a.952218","outputs":"1","autoTrigger":true,"autoTriggerTime":"600000","startDelayTime":"30000","storeName":"","blindIncrement":"0.01","blindOpenPos":"1","blindClosedPos":0,"blindPosReverse":false,"blindPosDefault":"open (max)","blindPosDefaultType":"levelFixed","overwriteExpire":"","rules":[{"index":0,"name":"auf ab 07:00","isValid":false,"valid":{},"timeValue":"07:00","timeType":"entered","timeOp":1,"timeOpText":"↧ von","offsetValue":"","offsetType":"none","multiplier":60000,"timeDays":"*","timeMonths":"*","timeOnlyEvenDays":false,"timeOnlyOddDays":false,"timeDateStart":"","timeDateEnd":"","timeMinValue":"","timeMinType":"none","offsetMinValue":"","offsetMinType":"none","multiplierMin":60000,"timeMaxValue":"","timeMaxType":"none","offsetMaxValue":"","offsetMaxType":"none","multiplierMax":60000,"levelValue":"open (max)","levelType":"levelFixed","levelOp":0,"levelOpText":"↕  Absolut","topic":"","importance":0,"resetOverwrite":true,"validOperandAValue":"","validOperandAType":"none","validOperator":"true","validOperatorText":"ist true","validOperandBValue":"","validOperandBType":"num","valid2LogOperator":0,"valid2LogOperatorText":"N/A","valid2OperandAValue":"","valid2OperandAType":"msg","valid2Operator":"true","valid2OperatorText":"ist true","valid2OperandBValue":"","valid2OperandBType":"num","description":"<div><i class=\"fa fa-clock-o\" aria-hidden=\"true\"></i> ↧ von <var>07:00</var></div><div>↕  Absolut <var>offen (max)</var><div class=\"indent-resetOverwrite-text\"> <span>manuelle Überschreibung verfällt wenn die Regel aktiv wird</span> </div></div>"}],"sunControlMode":"0","sunFloorLength":"90","sunMinAltitude":"33","sunMinDelta":"0.2","blindPosMin":"open (max)","blindPosMinType":"levelFixed","blindPosMax":"open (max)","blindPosMaxType":"levelFixed","smoothTime":"21600000","sunTopic":"","windowTop":"250","windowBottom":"150","windowAzimuthStart":"245","windowAzimuthEnd":"360","oversteerValue":"homeassistant.myHomeAssistant.states[\"sensor.lichtsensor_westen_statistik\"].state","oversteerValueType":"global","oversteerCompare":"gte","oversteerThreshold":"70000","oversteerThresholdType":"num","oversteerBlindPos":"50%","oversteerBlindPosType":"levelFixed","oversteer2Value":"","oversteer2ValueType":"none","oversteer2Compare":"gte","oversteer2Threshold":"80","oversteer2ThresholdType":"num","oversteer2BlindPos":"open (max)","oversteer2BlindPosType":"levelFixed","oversteer3Value":"","oversteer3ValueType":"none","oversteer3Compare":"gte","oversteer3Threshold":"","oversteer3ThresholdType":"num","oversteer3BlindPos":"open (max)","oversteer3BlindPosType":"levelFixed","oversteerTopic":"","x":610,"y":1920,"wires":[["5cf8ec52.d6c404","94fa84cf.5518b8","7d324b42.0a8e24"]]},{"id":"d9e9ca6a.952218","type":"position-config","name":"MeinZuhause","isValide":"true","longitude":"","latitude":"","angleType":"deg","timeZoneOffset":"99","timeZoneDST":"0","stateTimeFormat":"3","stateDateFormat":"12"}]`

**Comment by hvorragend** [comment]
Als Workaround habe ich ein "time range"-Node eingefügt, der das Triggern um 0:00 Uhr (hart) verhindern.

**Comment by zygi79** [comment]
Diesen Bug habe ich in etwas anderer Form: Ich habe die Regel, dass wenn der Rolladen unten ist und ich das Fenster öffne, der Rolladen auf 10% gefahren werden soll. Das funktioniert auch soweit, aber um 0:00 fährt der Rolladen dann einmal auf 0% um dann direkt wieder auf 10% zu fahren. Ist auch nicht so prickelnd, wenn man schon geschlafen hat :-(.

**Comment by Hypnos3** [comment]
Die Regeln sind:
![image](https://user-images.githubusercontent.com/12692680/133897866-210fac87-af08-4468-a5d0-1761d0b5f0bd.png)
Das bedeutet:
0-7:00 Uhr = zu
7:00Uhr - 7:30Uhr = zu
ab 7:30Uhr bis 0 Uhr = default (offen)

hier arbeitet alles wie gewünscht.

**Comment by hvorragend** [comment]
Ich bin verwirrt. Meine Kollegen und ich hatten alle das Problem mit der Fahrt um 0:00 Uhr. 

Ich blockiere seitdem alle Fahrten um diese Zeit. 

Ich bin als einziger auf die 2.0.0 alpha 1 gewechselt und habe es nie weiter beobachtet, da ich ja den Workaround hatte. 

Kontrolliere ich jetzt aber meine Log-Ausgabe (vor dem Workaround-Node), so sehe ich auch keine Fahrten mehr um 0:00. Das ist mir nicht aufgefallen. Kann es sein, dass du das in der Alpha vielleicht schon gefixt hast. 😄

Danke aber fürs Prüfen.

**Comment by hvorragend** [comment]
Ich habe hier (https://github.com/rdmtc/node-red-contrib-sun-position/issues/300#issuecomment-922523459) gerade etwas geschrieben. 

Kann es sein, dass die Fahrten durch das Holiday-Node getriggert werden?
Um 0:00 Uhr wird global.day... neu berechnet.

**Comment by Hypnos3** [comment]
Durch globale variablen wird nix getriggert. Änderungen bekommt die Node erst bei neuem Trigger mit.

**Comment by Hypnos3** [comment]
Wir sind mittlerweile bei der beta-7 angekommen. Hier hat sich zur alpha auch noch viel geändert und viele Bugs sind beseitigt.
