### ISSUE TITLE
Nur Übersteuern im Azimutbereich möglich (ohne Fenster-Setup)

### ISSUE THREAD

**Issue by hvorragend** [rdmtc/node-red-contrib-sun-position#284]
**Describe the Problem**

Ich möchte mit dem blind-control-Node zusätzlich zu einigen einfachen Regeln in der Sommerzeit ausschließlich die Beschattung über externe Lichtsensoren nutzen.
Also habe ich Anfangs-und Endwinkel für die Sonne konfiguriert. Auch habe ich Fenster Ober- und Unterseite und die Länge auf dem Boden gesetzt. etc.

Ich möchte aber nicht, dass die Rollos sich ständig der Sonneneinstrahlung anpassen, sondern ausschließlich das Übersteuern nutzen. Und dann natürlich auch Berücksichtigung der Mindeständerung und Glättung.

Aus diesem Grund habe ich im Modus "Sonnenlicht beschränken" die minimale und maximale Position auf "offen (max)" gesetzt. Und nur über das Übersteuern wird das Rollo gesenkt.

**Expected behavior**
Wie kann ich blind-control konfigurieren, so dass NUR das Übersteuern inkl. Glättung, Mindeständerung und Azimut berücksichtigt wird? Ich will nur Änderungen wenn die Übersteuerungsregeln greifen. Keine Anpassung an die eintreffende Sonne durch das Fenster.

Das Node ist ansonsten einfach zu aktiv. :-)

**System information (please complete the following information):**

* Node version 1.2.4
* Node-Red Version 1.3.5 (Home Assistant)

**Additional context**
`[{"id":"56339980.c63b28","type":"blind-control","z":"abeb29cc.4c9a78","name":"Ankleide","topic":"","positionConfig":"d9e9ca6a.952218","outputs":"1","autoTrigger":true,"autoTriggerTime":"600000","startDelayTime":"30000","storeName":"","blindIncrement":"0.01","blindOpenPos":"1","blindClosedPos":0,"blindPosReverse":false,"blindPosDefault":"open (max)","blindPosDefaultType":"levelFixed","overwriteExpire":"","rules":[{"index":0,"name":"zu bis 08:00","isValid":false,"valid":{},"timeValue":"08:00","timeType":"entered","timeOp":0,"timeOpText":"↥ bis","offsetValue":"","offsetType":"none","multiplier":60000,"timeDays":"*","timeMonths":"*","timeOnlyEvenDays":false,"timeOnlyOddDays":false,"timeDateStart":"","timeDateEnd":"","timeMinValue":"","timeMinType":"none","offsetMinValue":"","offsetMinType":"none","multiplierMin":60000,"timeMaxValue":"","timeMaxType":"none","offsetMaxValue":"","offsetMaxType":"none","multiplierMax":60000,"levelValue":"closed (min)","levelType":"levelFixed","levelOp":0,"levelOpText":"↕  Absolut","topic":"","importance":0,"resetOverwrite":true,"validOperandAValue":"","validOperandAType":"none","validOperator":"true","validOperatorText":"ist true","validOperandBValue":"","validOperandBType":"num","valid2LogOperator":0,"valid2LogOperatorText":"N/A","valid2OperandAValue":"","valid2OperandAType":"msg","valid2Operator":"true","valid2OperatorText":"ist true","valid2OperandBValue":"","valid2OperandBType":"num","description":"<div><i class=\"fa fa-clock-o\" aria-hidden=\"true\"></i> ↥ bis <var>08:00</var></div><div>↕  Absolut <var>geschlossen (min)</var><div class=\"indent-resetOverwrite-text\"> <span>manuelle Überschreibung verfällt wenn die Regel aktiv wird</span> </div></div>"},{"index":1,"name":"zu bis 08:30 WE / FT","isValid":false,"valid":{},"timeValue":"08:30","timeType":"entered","timeOp":0,"timeOpText":"↥ bis","offsetValue":"","offsetType":"none","multiplier":60000,"timeDays":"*","timeMonths":"*","timeOnlyEvenDays":false,"timeOnlyOddDays":false,"timeDateStart":"","timeDateEnd":"","timeMinValue":"","timeMinType":"none","offsetMinValue":"","offsetMinType":"none","multiplierMin":60000,"timeMaxValue":"","timeMaxType":"none","offsetMaxValue":"","offsetMaxType":"none","multiplierMax":60000,"levelValue":"closed (min)","levelType":"levelFixed","levelOp":0,"levelOpText":"↕  Absolut","topic":"","importance":0,"resetOverwrite":true,"validOperandAValue":"day.today.isWeekendOrHoliday","validOperandAType":"global","validOperator":"true","validOperatorText":"ist true","validOperandBValue":"","validOperandBType":"num","valid2LogOperator":0,"valid2LogOperatorText":"N/A","valid2OperandAValue":"","valid2OperandAType":"msg","valid2Operator":"true","valid2OperatorText":"ist true","valid2OperandBValue":"","valid2OperandBType":"num","description":"<div><i class=\"fa fa-code-fork\" aria-hidden=\"true\"></i> <var>global.day.today.isWeekendOrHoliday</var> ist true</div><div><i class=\"fa fa-clock-o\" aria-hidden=\"true\"></i> ↥ bis <var>08:30</var></div><div>↕  Absolut <var>geschlossen (min)</var><div class=\"indent-resetOverwrite-text\"> <span>manuelle Überschreibung verfällt wenn die Regel aktiv wird</span> </div></div>"},{"index":2,"name":"zu bis Sonnenaufgang","isValid":true,"valid":{"validTimeReg":true,"validLevel":true,"validOperand1A":true},"timeValue":"sunriseStart","timeType":"pdsTime","timeOp":0,"timeOpText":"↥ bis","offsetValue":"","offsetType":"none","multiplier":60000,"timeDays":"*","timeMonths":"*","timeOnlyEvenDays":false,"timeOnlyOddDays":false,"timeDateStart":"","timeDateEnd":"","timeMinValue":"","timeMinType":"none","offsetMinValue":"","offsetMinType":"none","multiplierMin":60000,"timeMaxValue":"","timeMaxType":"none","offsetMaxValue":"","offsetMaxType":"none","multiplierMax":60000,"levelValue":"25%","levelType":"levelFixed","levelOp":0,"levelOpText":"↕  Absolut","topic":"","importance":0,"resetOverwrite":true,"validOperandAValue":"","validOperandAType":"none","validOperator":"true","validOperatorText":"ist true","validOperandBValue":"","validOperandBType":"num","valid2LogOperator":0,"valid2LogOperatorText":"N/A","valid2OperandAValue":"","valid2OperandAType":"msg","valid2Operator":"true","valid2OperatorText":"ist true","valid2OperandBValue":"","valid2OperandBType":"num","description":"<div><i class=\"fa fa-clock-o\" aria-hidden=\"true\"></i> ↥ bis <var>Sonnenaufgang Begin</var></div><div>↕  Absolut <var>25%</var><div class=\"indent-resetOverwrite-text\"> <span>manuelle Überschreibung verfällt wenn die Regel aktiv wird</span> </div></div>"},{"index":3,"name":"zu nach Sonnenuntergang | 20:00 bis 22:00 ","isValid":true,"valid":{"validTimeReg":60000,"validLevel":true,"validOperand1A":true},"timeValue":"sunsetStart","timeType":"pdsTime","timeOp":1,"timeOpText":"↧ von","offsetValue":"","offsetType":"none","multiplier":60000,"timeDays":"*","timeMonths":"*","timeOnlyEvenDays":false,"timeOnlyOddDays":false,"timeDateStart":"","timeDateEnd":"","timeMinValue":"20:00","timeMinType":"entered","offsetMinValue":"","offsetMinType":"none","multiplierMin":60000,"timeMaxValue":"22:00","timeMaxType":"entered","offsetMaxValue":"","offsetMaxType":"none","multiplierMax":60000,"levelValue":"25%","levelType":"levelFixed","levelOp":0,"levelOpText":"↕  Absolut","topic":"","importance":0,"resetOverwrite":true,"validOperandAValue":"","validOperandAType":"none","validOperator":"true","validOperatorText":"ist true","validOperandBValue":"","validOperandBType":"num","valid2LogOperator":0,"valid2LogOperatorText":"N/A","valid2OperandAValue":"","valid2OperandAType":"msg","valid2Operator":"true","valid2OperatorText":"ist true","valid2OperandBValue":"","valid2OperandBType":"num","description":"<div><i class=\"fa fa-clock-o\" aria-hidden=\"true\"></i> ↧ von <var>Sonnenuntergang Begin</var><div class=\"indent-time-text\"><i class=\"fa fa-step-backward\" aria-hidden=\"true\"></i> <span>frühestens (min)</span> <var>20:00</var></div><div class=\"indent-time-text\"><i class=\"fa fa-step-forward\" aria-hidden=\"true\"></i> <span>spätestens (max)</span> <var>22:00</var></div></div><div>↕  Absolut <var>25%</var><div class=\"indent-resetOverwrite-text\"> <span>manuelle Überschreibung verfällt wenn die Regel aktiv wird</span> </div></div>"}],"sunControlMode":"2","sunFloorLength":"90","sunMinAltitude":"33","sunMinDelta":"0.2","blindPosMin":"open (max)","blindPosMinType":"levelFixed","blindPosMax":"open (max)","blindPosMaxType":"levelFixed","smoothTime":"21600000","sunTopic":"","windowTop":"600","windowBottom":"500","windowAzimuthStart":"55","windowAzimuthEnd":"275","oversteerValue":"homeassistant.myHomeAssistant.states[\"sensor.lichtsensor_sueden_statistik\"].state","oversteerValueType":"global","oversteerCompare":"gte","oversteerThreshold":"50000","oversteerThresholdType":"num","oversteerBlindPos":"10%","oversteerBlindPosType":"levelFixed","oversteer2Value":"","oversteer2ValueType":"none","oversteer2Compare":"gte","oversteer2Threshold":"80","oversteer2ThresholdType":"num","oversteer2BlindPos":"open (max)","oversteer2BlindPosType":"levelFixed","oversteer3Value":"","oversteer3ValueType":"none","oversteer3Compare":"gte","oversteer3Threshold":"","oversteer3ThresholdType":"num","oversteer3BlindPos":"open (max)","oversteer3BlindPosType":"levelFixed","oversteerTopic":"","x":620,"y":280,"wires":[["4847e96c.e9a8c8","88b8131b.53413","a3aac831.c2f168"]]},{"id":"d9e9ca6a.952218","type":"position-config","name":"MeinZuhause","isValide":"true","longitude":"","latitude":"","angleType":"deg","timeZoneOffset":"99","timeZoneDST":"0","stateTimeFormat":"3","stateDateFormat":"12"}]`

**Comment by Hypnos3** [comment]
>  Keine Anpassung an die eintreffende Sonne durch das Fenster.

Wenn ich den Wunsch so lese, frag ich mich ob die Node dafür geeignet ist, weil das der Haupteinsatzzweck der Node ist.

Für reine Zeitsteuerung ist die [Timer Node](https://github.com/rdmtc/node-red-contrib-sun-position/wiki/clock-timer) besser. Für reine Azimuth Steuerung ist die [sun-position](https://github.com/rdmtc/node-red-contrib-sun-position/wiki/sun-position) node die richtigte. --> Hier kann man verschiedene untere und obere Limits setzen. Da gibt es für jeden dann einen Ausgang.

Bevor es im Paket die blind-control node (und auch die timer node) gab, hab ich genau so meine Rollladensteuerung aufgebaut gehabt. Also zu bestimmten azimuth die Rollläden geschlossen und bei anderen dahinter verschiedene switch nodes, die bei bestimmten Bedingungen (Lichtsensoren) einfach eine Position (mittels change nodes) vorgegeben haben.
Über Trigger Nodes kann man beispielsweise verhindern, das zu oft eine Änderung "durchschlägt".

Die [Timer Node](https://github.com/rdmtc/node-red-contrib-sun-position/wiki/clock-timer) ist eine "abgespeckte" Version der Rollladensteuerungs-Node, ohne die ganze Sonnensteuerung. Hier kann man auch Zeiten anhand des Azimuth definieren und damit ist diese wahrscheinlich sogar mittlerweile der [sun-position](https://github.com/rdmtc/node-red-contrib-sun-position/wiki/sun-position) node überlegen.

Für das "Glättung und Mindeständerung" gibt es bistimmt auch andere Nodes (node-red-node-smooth), welche das können.

Zum eigentlichen Problem:
Ich könnte zu den Modi (Sommer + Winter) für die Sonnensteuerung noch einen weiteren Modus wie "immer offen" hinzufügen. Damit sollte das möglich sein.

**Comment by hvorragend** [comment]
Zuerst bin ich dir sehr dankbar für deine Ausführungen. Sehr anschaulich und gut beschrieben. Danke. 

Dann bin ich auch froh, dass du mich verstanden hast und sogar eine Verbesserung vorgeschlagen hast. Danke noch einmal. 

Ich habe nach der Erstellung des Issues die 2.0.0 alpha1 getestet. Damit könnte ich ein Großteil erschlagen, da ich nun in den Regeln mehr Möglichkeiten habe. 
Nur die Glättung etc. nicht. Aber dafür habe ich ja #301 aufgemacht. 

Ich bin echt gespannt.

**Comment by Hypnos3** [comment]
Wenn nur noch die Glättung fehlt, mach ich das issue mal zu.
