### ISSUE TITLE
Use of absolut Position

### ISSUE THREAD

**Issue by gerribaldi** [rdmtc/node-red-contrib-sun-position#286]
Hi,

i´m using the blind control for some of my blinds. Most of it i move via absolut position to the end or top position. But on some of it i want to put it to different position e.g. 85% or 56%. Is there a way to get this value in a rule or is it only posibel to move it to values which are inside?

Thanks+Regards
gerribaldi

**Comment by gerribaldi** [comment]
OK, found it... ;-)

Could be closed

**Comment by hvorragend** [comment]
Could you please explain how?
Perhaps a screenshot of this setting?

Is it similar to this?
https://github.com/rdmtc/node-red-contrib-sun-position/issues/282#issuecomment-860232715

**Comment by gerribaldi** [comment]
I didn't recognized, that i can put different value to "Rolladenposition" and only see position with the pre-definit values

**Comment by hvorragend** [comment]
Oh, okay. I've misread your question. Got it.
