### ISSUE TITLE
Do you support passing a time object to this node ? 

### ISSUE THREAD

**Issue by craigcurtin-dev** [rdmtc/node-red-contrib-sun-position#287]
I have a flow in NR that is using this node - basically it calculates what the current electricity tarriff that is in effect (which varies based on day, time, day of week, month of year etc.

This node works beautifully for this need and has tidied up my flow fantastically.

However what i now need/want to do - is project forwards - so in effect see what tarriff will be in effect 12 hours from now - if it was possible to pass this node a time object as an optional parameter that would address this for me.

Currently i call the node every minute with a standard inject and then act on the ouput - my idea would be that i could (optionally) inject a certain time in the future and the node would utilise this.

Does this make sense ?

Craig

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by Hypnos3** [comment]
Hallo, can you say which node you mean?

This package has severan Nodes:
sun-position
moon-position
time-inject
within-time
time-comp
time-span
blind-control
clock-timer
