### ISSUE TITLE
Beschattung via Oversteer optional nicht wieder rückgängig machen?

### ISSUE THREAD

**Issue by hvorragend** [rdmtc/node-red-contrib-sun-position#289]
**Is your feature request related to a problem? Please describe.**
Hallo, ich hatte es in #288 bereits ansatzweise angefragt: 
Könnte man es implementieren, dass die Beschattung, die bspw. morgens aufgrund zu heller Sonneneinstrahlung durchgeführt wird, nicht vom Node wieder rückgängig gemacht wird?
Also nur optional?

**Describe the solution you'd like**
Mir reicht es eigentlich, wenn ich weiß, dass die Sonne auf die Fenster "brennt" und dann würde ich über Oversteer nur einmal beschatten und die Rollos bis zu nächsten Regel wieder normal fahren.

**Describe alternatives you've considered**
none

**Additional context**
sorry, none.

**Comment by hvorragend** [comment]
Hmm, mal kurz nachgedacht: 
Wäre ich damit nicht besser in einer eigene Regel aufgehoben anstatt dem Oversteer-Feature? Damit sollte es doch eigentlich möglich sein, oder?

**Comment by Hypnos3** [comment]
Ich denke das sollte mit einer bedingten Regel anstelle Oversteer umgesetzt werden. Oversteer ist nur dazu gedacht die Sonnensteuerung zu beeinflussen und daher ist das nur solange aktiv wie diese auch wirkt.

Natürlich "wirkt" eine Bedingte Regel auch nicht mehr, wenn die Bedingung nicht mehr zutrifft. Das könnte man dadurch lösen, indem man das "übersteuern" durch eine Nachricht an den Eingang mit einer bestimmten Topic sendet und die Regel darauf steuert (Payload=true if topic contais).
Diese einkommende Nachricht wird dann intern "gecached" mit dem Wert der letzten Nachricht. Damit bleibt der Payload true solange erhalten, bis man eine Nachricht mit der selben Topic und dem Payload false sendet.

**Comment by hvorragend** [comment]
Hmm. Ansatzweise habe ich das verstanden. Danke für deinen Vorschlag. 

Man würde die Beschattungslogik dann in ein function-Node auslagern oder wie meinst du das?

**Comment by Hypnos3** [comment]
Ich weiß nicht ob man dafür eine extra funktion node benötigt. Mit der neusten version kann man beliebig viele Bedingungen in eine Regel packen und damit sollte das nicht mehr nötig sein.

**Comment by hvorragend** [comment]
Absolute Zustimmung. 
Damals kannte ich die 2.0.0 alpha noch nicht. 😄
