### ISSUE TITLE
FR for within-time-switch: Configurable properties for output

### ISSUE THREAD

**Issue by DamianosS** [rdmtc/node-red-contrib-sun-position#292]
In addition to the existing way of passing the ingoing message to the node's outputs it would be great to have configurable properties for within-time and out-of-time.

Ideally dropdowns for text/number/boolean/{} but for the start simple text would be ok. As an example, that way lights could be controlled with "turn_on""turn_off" text.

**Comment by Hypnos3** [comment]
seems reasonable

**Comment by Hypnos3** [comment]
I'm only going to build in a configurable payload.
To have all the properties customizable would go beyond the configuration dialog and would no longer be understandable.

**Comment by Hypnos3** [comment]
available from 2.0.0 beta-3
