### ISSUE TITLE
Overwrite bei "manuelle Überschreibung verfällt wenn die Regel aktiv wird"

### ISSUE THREAD

**Issue by Rincewind0** [rdmtc/node-red-contrib-sun-position#293]
**Describe the Problem**
Hallo,
ich habe eine Frage zur Funktion "manuelle Überschreibung verfällt wenn die Regel aktiv wird" innerhalb der Regeln:
Ich habe den genannten Haken gesetzt, um eine manuell eingestellte Rolladenposition zu resetten, sobald eine Regel aktiv wird.
Das funktioniert soweit auch.
Im umgekehrten Fall, also wenn bereits eine dieser Regeln aktiv ist und ich die Rolladenposition manuell mit einem Overwrite verändere, funktioniert der Overwrite nur jedes 2. Mal. Mit dem angehängten vereinfachten Flow kann man das ganz gut testen. z.B.:
1. Overwrite: 20%: Rolladenposition wird überschrieben
2. Overwrite: 60%: Rolladenposition wird zurückgesetzt und Regel greift
3. Overwrite: 40%: Rolladenposition wird überschrieben
4. Overwrite: 60%: Rolladenposition wird zurückgesetzt und Regel greift
usw.
(Die Uhrzeiten der Regeln im Flow sind nur deshalb so gewählt, um den ganzen Tag über testen zu können)

**Expected behavior**
Ich hätte erwartet, dass auch beim 2. Overwrite, die manuell eingestellte Position übernommen wird.
Habe ich da einen grundsätzlichen Denkfehler? Oder müsste ich das anders lösen?
(Das Verhalten ist auch gleich, wenn ich statt mit msg.level z.B. mit msg.topic=levelOverwrite arbeite)

**Screenshots**
![image](https://user-images.githubusercontent.com/86548134/123536470-c47c2280-d72a-11eb-9301-edaefd82ba03.png)

**System information (please complete the following information):**

* Node v1.2.4
* Node-Red v1.3.4

**Additional context**
`[
    {
        "id": "95eb64d7.348248",
        "type": "tab",
        "label": "Flow 1",
        "disabled": false,
        "info": ""
    },
    {
        "id": "21753740.7d6e58",
        "type": "inject",
        "z": "95eb64d7.348248",
        "name": "100%",
        "props": [
            {
                "p": "payload"
            }
        ],
        "repeat": "",
        "crontab": "",
        "once": false,
        "onceDelay": 0.1,
        "topic": "",
        "payload": "100",
        "payloadType": "num",
        "x": 90,
        "y": 80,
        "wires": [
            [
                "3a772643.f4967a"
            ]
        ]
    },
    {
        "id": "3a772643.f4967a",
        "type": "change",
        "z": "95eb64d7.348248",
        "name": "Add Overwrite",
        "rules": [
            {
                "t": "set",
                "p": "importance",
                "pt": "msg",
                "to": "10",
                "tot": "num"
            },
            {
                "t": "set",
                "p": "level",
                "pt": "msg",
                "to": "payload",
                "tot": "msg"
            }
        ],
        "action": "",
        "property": "",
        "from": "",
        "to": "",
        "reg": false,
        "x": 320,
        "y": 200,
        "wires": [
            [
                "ef6233e8.d0fc"
            ]
        ]
    },
    {
        "id": "ef6233e8.d0fc",
        "type": "blind-control",
        "z": "95eb64d7.348248",
        "name": "SZ",
        "topic": "",
        "positionConfig": "a92fc70c.136878",
        "outputs": "1",
        "autoTrigger": true,
        "autoTriggerTime": 3600000,
        "startDelayTime": "0",
        "storeName": "",
        "blindIncrement": "5",
        "blindOpenPos": "100",
        "blindClosedPos": 0,
        "blindPosReverse": false,
        "blindPosDefault": "open (max)",
        "blindPosDefaultType": "levelFixed",
        "overwriteExpire": "",
        "rules": [
            {
                "index": 0,
                "name": "Öffnen",
                "isValid": false,
                "valid": {},
                "timeValue": "07:59",
                "timeType": "entered",
                "timeOp": 0,
                "timeOpText": "↥ bis",
                "offsetValue": "",
                "offsetType": "none",
                "multiplier": 60000,
                "timeDays": "*",
                "timeMonths": "*",
                "timeOnlyEvenDays": false,
                "timeOnlyOddDays": false,
                "timeDateStart": "",
                "timeDateEnd": "",
                "timeMinValue": "",
                "timeMinType": "none",
                "offsetMinValue": "",
                "offsetMinType": "none",
                "multiplierMin": 60000,
                "timeMaxValue": "",
                "timeMaxType": "none",
                "offsetMaxValue": "",
                "offsetMaxType": "none",
                "multiplierMax": 60000,
                "levelValue": "25%",
                "levelType": "levelFixed",
                "levelOp": 0,
                "levelOpText": "↕  Absolut",
                "topic": "",
                "importance": 0,
                "resetOverwrite": true,
                "validOperandAValue": "",
                "validOperandAType": "none",
                "validOperator": "true",
                "validOperatorText": "ist true",
                "validOperandBValue": "",
                "validOperandBType": "num",
                "valid2LogOperator": 0,
                "valid2LogOperatorText": "N/A",
                "valid2OperandAValue": "",
                "valid2OperandAType": "msg",
                "valid2Operator": "true",
                "valid2OperatorText": "ist true",
                "valid2OperandBValue": "",
                "valid2OperandBType": "num",
                "description": "<div><i class=\"fa fa-clock-o\" aria-hidden=\"true\"></i> ↥ bis <var>07:59</var></div><div>↕  Absolut <var>25%</var><div class=\"indent-resetOverwrite-text\"> <span>manuelle Überschreibung verfällt wenn die Regel aktiv wird</span> </div></div>"
            },
            {
                "index": 1,
                "name": "Schließen",
                "isValid": false,
                "valid": {},
                "timeValue": "08:00",
                "timeType": "entered",
                "timeOp": 1,
                "timeOpText": "↧ von",
                "offsetValue": "",
                "offsetType": "none",
                "multiplier": 60000,
                "timeDays": "*",
                "timeMonths": "*",
                "timeOnlyEvenDays": false,
                "timeOnlyOddDays": false,
                "timeDateStart": "",
                "timeDateEnd": "",
                "timeMinValue": "",
                "timeMinType": "none",
                "offsetMinValue": "",
                "offsetMinType": "none",
                "multiplierMin": 60000,
                "timeMaxValue": "",
                "timeMaxType": "none",
                "offsetMaxValue": "",
                "offsetMaxType": "none",
                "multiplierMax": 60000,
                "levelValue": "50%",
                "levelType": "levelFixed",
                "levelOp": 0,
                "levelOpText": "↕  Absolut",
                "topic": "",
                "importance": 0,
                "resetOverwrite": true,
                "validOperandAValue": "",
                "validOperandAType": "none",
                "validOperator": "true",
                "validOperatorText": "ist true",
                "validOperandBValue": "",
                "validOperandBType": "num",
                "valid2LogOperator": 0,
                "valid2LogOperatorText": "N/A",
                "valid2OperandAValue": "",
                "valid2OperandAType": "msg",
                "valid2Operator": "true",
                "valid2OperatorText": "ist true",
                "valid2OperandBValue": "",
                "valid2OperandBType": "num",
                "description": "<div><i class=\"fa fa-clock-o\" aria-hidden=\"true\"></i> ↧ von <var>08:00</var></div><div>↕  Absolut <var>50%</var><div class=\"indent-resetOverwrite-text\"> <span>manuelle Überschreibung verfällt wenn die Regel aktiv wird</span> </div></div>"
            }
        ],
        "sunControlMode": "0",
        "sunFloorLength": "",
        "sunMinAltitude": "",
        "sunMinDelta": "",
        "blindPosMin": "closed (min)",
        "blindPosMinType": "levelFixed",
        "blindPosMax": "open (max)",
        "blindPosMaxType": "levelFixed",
        "smoothTime": "",
        "sunTopic": "",
        "windowTop": "",
        "windowBottom": "",
        "windowAzimuthStart": "",
        "windowAzimuthEnd": "",
        "oversteerValue": "",
        "oversteerValueType": "none",
        "oversteerCompare": "gte",
        "oversteerThreshold": "",
        "oversteerThresholdType": "num",
        "oversteerBlindPos": "open (max)",
        "oversteerBlindPosType": "levelFixed",
        "oversteer2Value": "",
        "oversteer2ValueType": "none",
        "oversteer2Compare": "gte",
        "oversteer2Threshold": "",
        "oversteer2ThresholdType": "num",
        "oversteer2BlindPos": "open (max)",
        "oversteer2BlindPosType": "levelFixed",
        "oversteer3Value": "",
        "oversteer3ValueType": "none",
        "oversteer3Compare": "gte",
        "oversteer3Threshold": "",
        "oversteer3ThresholdType": "num",
        "oversteer3BlindPos": "open (max)",
        "oversteer3BlindPosType": "levelFixed",
        "oversteerTopic": "",
        "x": 490,
        "y": 200,
        "wires": [
            [
                "2563703b.3471d"
            ]
        ]
    },
    {
        "id": "d329160c.a5a908",
        "type": "debug",
        "z": "95eb64d7.348248",
        "name": "test",
        "active": true,
        "tosidebar": true,
        "console": false,
        "tostatus": false,
        "complete": "true",
        "targetType": "full",
        "statusVal": "",
        "statusType": "auto",
        "x": 900,
        "y": 20,
        "wires": []
    },
    {
        "id": "2563703b.3471d",
        "type": "debug",
        "z": "95eb64d7.348248",
        "name": "Rolladen",
        "active": true,
        "tosidebar": true,
        "console": false,
        "tostatus": false,
        "complete": "true",
        "targetType": "full",
        "statusVal": "",
        "statusType": "auto",
        "x": 670,
        "y": 200,
        "wires": []
    },
    {
        "id": "1dd3d9ef.f6ef06",
        "type": "inject",
        "z": "95eb64d7.348248",
        "name": "60%",
        "props": [
            {
                "p": "payload"
            }
        ],
        "repeat": "",
        "crontab": "",
        "once": false,
        "onceDelay": 0.1,
        "topic": "",
        "payload": "60",
        "payloadType": "num",
        "x": 90,
        "y": 140,
        "wires": [
            [
                "3a772643.f4967a"
            ]
        ]
    },
    {
        "id": "b3f3a393.0071b",
        "type": "inject",
        "z": "95eb64d7.348248",
        "name": "40%",
        "props": [
            {
                "p": "payload"
            }
        ],
        "repeat": "",
        "crontab": "",
        "once": false,
        "onceDelay": 0.1,
        "topic": "",
        "payload": "40",
        "payloadType": "num",
        "x": 90,
        "y": 200,
        "wires": [
            [
                "3a772643.f4967a"
            ]
        ]
    },
    {
        "id": "f1869abf.5be958",
        "type": "inject",
        "z": "95eb64d7.348248",
        "name": "20%",
        "props": [
            {
                "p": "payload"
            }
        ],
        "repeat": "",
        "crontab": "",
        "once": false,
        "onceDelay": 0.1,
        "topic": "",
        "payload": "20",
        "payloadType": "num",
        "x": 90,
        "y": 260,
        "wires": [
            [
                "3a772643.f4967a"
            ]
        ]
    },
    {
        "id": "37e844ec.02d13c",
        "type": "inject",
        "z": "95eb64d7.348248",
        "name": "0%",
        "props": [
            {
                "p": "payload"
            }
        ],
        "repeat": "",
        "crontab": "",
        "once": false,
        "onceDelay": 0.1,
        "topic": "",
        "payload": "0",
        "payloadType": "num",
        "x": 90,
        "y": 320,
        "wires": [
            [
                "3a772643.f4967a"
            ]
        ]
    },
    {
        "id": "a92fc70c.136878",
        "type": "position-config",
        "name": "Test",
        "isValide": "true",
        "longitude": "0",
        "latitude": "0",
        "angleType": "deg",
        "timeZoneOffset": "99",
        "timeZoneDST": "0",
        "stateTimeFormat": "3",
        "stateDateFormat": "12"
    }
]`

**Comment by Hypnos3** [comment]
Muss ich mir ansehen, mir fehlt leider aktuell die Zeit.
Info an mich selbst: In dem Zuge auch noch mit zu betrachten: https://homematic-forum.de/forum/posting.php?mode=reply&f=77&t=60058#pr671381

**Comment by Rincewind0** [comment]
Danke schon mal für die Rückmeldung!

**Comment by Hypnos3** [comment]
Problem ist ab Version 2.0.0 beta-4 gelöst.
