### ISSUE TITLE
Zufallswert wird gelöscht

### ISSUE THREAD

**Issue by hvorragend** [rdmtc/node-red-contrib-sun-position#299]
**Describe the bug**
In der Version 2.0.0 alpha1 werden Zufallswerte bei den Regeln zwar gespeichert, aber nach dem erneuten Aufruf der Regeln werden diese nicht mehr angezeigt. Beim Verlassen des Dialogs wird der Wert dann auch gelöscht. 

**Expected behavior**
Zufallswert sollte beibehalten werden. 

**System information (please complete the following information):**
 - Node Version 2.0.0 alpha1

**Comment by Hypnos3** [comment]
Is integrated in the 2.0.0-beta and can be installed and tested. See Releases Information on how to install the beta version.
