### ISSUE TITLE
Wie Overwrite nach Deploy beibehalten?

### ISSUE THREAD

**Issue by hvorragend** [rdmtc/node-red-contrib-sun-position#300]
**Describe the Problem**
Nach einem Deploy des Flows werden die Blind-Nodes neu gestartet. Somit verlassen die Rollos teilweise die aktive Beschattung oder ein Overwrite wird entfernt. 

**Expected behavior**
Weiß jemand wie man den Flow so aufbaut, dass die Blind-Control deploy-persistent bleiben? Geht das?

* Version 2.0.0 alpha 1

**Comment by Hypnos3** [comment]
info for me:
- switch from internal data structure to use of node context
- allow configuration of the used context-store to be allowing to use a persistent context

**Comment by Hypnos3** [comment]
Das ist in der aktuellen beta enthalten. Ich bin aber noch nicht dazu gekommen das zu testen.

**Comment by Hypnos3** [comment]
Tested with 2.0.0 beta-3 and is working

**Comment by FunkOdyssey2001** [comment]
Frage am Rande: Gibt es eigentlich auch eine Möglichkeit, dass die Nodes nicht alle nach einem Neustart von NodeRed ausgelöst werden?

Ich habe den Auto-Trigger auf 10min und die Verzögerung auf 30sec.

Und dennoch werden alle Blind-Nodes kurz nach einem Neustart ausgeführt.

Oder kann es sein, dass die Node durch global-Variablen getriggert werden? Dann  hätte ich glaube auch, den Bug gefunden, warum damals bei mir um 0:00 Uhr gefahren wurde. :-)

![screen](https://user-images.githubusercontent.com/68234624/133940208-b4cffda8-3714-4368-afa4-84edf46a9d22.png)

**Comment by hvorragend** [comment]
Frage am Rande: Gibt es eigentlich auch eine Möglichkeit, dass die Nodes nicht alle nach einem Neustart von NodeRed ausgelöst werden?

Ich habe den Auto-Trigger auf 10min und die Verzögerung auf 30sec.

Und dennoch werden alle Blind-Nodes kurz nach einem Neustart ausgeführt.

Oder kann es sein, dass die Node durch global-Variablen getriggert werden? Dann hätte ich glaube auch, den Bug gefunden, warum damals bei mir um 0:00 Uhr gefahren wurde. :-)
![screen](https://user-images.githubusercontent.com/343705/133940268-f02d4050-914d-40cb-87e1-f88b8b7f13c4.png)

**Comment by Hypnos3** [comment]
Um welche Nodes geht es? - Rollladen und Zeit Schaltuhr?

Durch globale variablen wird nix getriggert. 

Bei der Rollladen und Zeit Schaltuhr node gibt es die Einstellnung "Ausgabe bei Start verzögern":
![image](https://user-images.githubusercontent.com/12692680/133945703-c1ade90e-b265-421f-b771-c0bafa9c8915.png)
Damit lässt sich einstellen, wie lange die node bei einem Start nix machen soll. Das ist gedacht, damit alle anderen Dinge (wie globale Variablen, etc...) auch gesetzt werden können.

Die Node komplett bei einem Start nicht zu triggern, wäre blöd, weil dann das Autotrigger nicht funktioniert.

**Comment by Hypnos3** [comment]
Ich hab nochmal in den code geguckt. Wenn "Ausgabe bei Start verzögern" den Wert `0` hat, wird bei deploy und Node-Red Start die node nicht selbst getriggert. Das bedeutet bei "automatisch triggern" wird der nächste Termin auch nicht berechnet und die Node würde dort nicht getriggert.

Die Berechnung wird in diesem Falle erst mit der nächsten eintreffenden Nachricht erfolgen.

**Comment by hvorragend** [comment]
Danke für deine Hilfe.

Mir fehlt noch ein wenig die Langzeiterfahrung mit NodeRed. 
Verschiebt sich das Problem nicht einfach nur, wenn ich den Trigger auf einen externen Inject-Node verschiebe und diesen zyklisch alle 10 Minuten auslösen lasse?

**Comment by Hypnos3** [comment]
Ja, das verschiebt sich nur. Da kann man bei "automatisch triggern" den Haken reinmachen und "dynamisch aber aller" auf 10 Minuten setzen. Das hat den selben Effekt wie eine externe Inject node, welche aller 10 Minuten triggert.
