### ISSUE TITLE
[FR] Glättung/Mindeständerung auch bei Regeln?

### ISSUE THREAD

**Issue by hvorragend** [rdmtc/node-red-contrib-sun-position#301]
**Is your feature request related to a problem? 
Please describe.**

Bei der Sommer- und Wintersteuerung gibt es die Möglichkeit der Glättung und der Angabe von einem Mindeständerungswert, so dass die Rollo-Aktoren nicht zu häufig laufen. 

Seit v2.0.0 alpha1 kann man Azimuth und Elevation wie auch eigene Bedingungen (bspw. Lichtintensität) in den Regeln eingeben und  somit die Beschattung darüber umsetzen. 

Die verwendeten Sensoren müsste man vermutlich außerhalb von Blind-Control per Median oder ähnlich glätten. Wobei so etwas wie Threshold/Hysterese auch in deinem Node schon ein geniales Feature wäre. 

**Describe the solution you'd like**
- Glättung ... x Stunden
- Mindestäbderungsachwelle
... in den Regeln.

**Comment by Hypnos3** [comment]
Ich sehe hier Schwieigkeiten bei der Umsetzung des Wunsches. Die bestehende Mindeständerungswert ist speziell für die Sonnenstandsberechnung und dort macht das Sinn. Umgekehrt sind diese EInstellmöglichkeiten nicht zu sehen, wenn ich die Sonnenstandsregelung nicht nutze.

Für den Wunsch das auch noch für die Regeln zu haben, ist das schwieriger. Ich will vielleicht Regeln haben, die immer zuschlagen (Rauchmelder, etc...). Hier wäre es blöd, wenn das dann nicht greift, weil eine andere Änderung innerhalb der Mindeständerung das verhindert. Damit bin ich dann sehr schnell bei Einstellungen pro Regel.

Ich kann mir aktuell nicht vorstellen, wie ich ein zusätzlich in das GUI und die vielen Möglichkeiten intrgrieren kann, so das es noch verständlich ist.

Auch macht es einfach ab einem bestimmten Punkt mehr Sinn etwas außerhalb der node mit den Node-Red Bordmitteln zu konfigurieren. Also entweder die Sensordaten als Eingang glätten oder die Ausgabe der Nodhe zu glätten, bevor diese an eine ausgabe gesendet werden.
Damit wird das verständlicher und lässt sich auch einfacher nachvollziehen.

**Comment by hvorragend** [comment]
Alles klar. Danke dennoch. Ich kann das nachvollziehen.
