### ISSUE TITLE
Conflict random offset and restrict sunlight (summer)

### ISSUE THREAD

**Issue by hvorragend** [rdmtc/node-red-contrib-sun-position#302]
**Describe the bug**
Ich habe in der 2.0.0 alpha 1 eine ganz einfache Regel, dass beim Ende des Sonnenaufgangs zwischen 07:00 und 08:30 Uhr die Rollos fahren sollen. 
Aktuell ist das immer zum frühesten Zeitpunkt und somit 07:00 Uhr. 

Alle Zeiten haben einen Zufallsoffset von 5min. 

Die Rollos fahren innerhalb dieser 5 Minuten wild hoch und runter. 

```
Kueche Westen wechselte zu 100 - overwritten [imp&#x3D;0] (Code: 2) 
7:06:52 

Kueche Westen wechselte zu 0 - overwritten [imp&#x3D;0] (Code: 2) 
7:05:42 

Kueche Westen wechselte zu 100 - no sun in window (Code: 8)
7:05:41 

Kueche Westen wechselte zu 0 - ↥ bis 7:05:41 AM + cond [1] Morgens (Code: 4)
7:04:28 - 

Kueche Westen wechselte zu 100 - no sun in window (Code: 8)
7:03:16 
```

Es gibt für das Rollo auch eine Oversteer-Sommer-Konfiguration. Diese trifft um 07:00 Uhr aber nicht zu. Deswegen wird vermutlich auch immer wieder auf 100 (offen) gefahren. 

**Expected behavior**
Ich bin davon ausgegangen, dass nur einmal zum Zufallszeitpunkt gefahren wird. Ich denke, dass der Sommermodus sich mit dem Zufallswert in Konflikt kommt. 

Entferne ich das Offset aus der Regel, so wird nur einmal gefahren. 

**System information (please complete the following information):**
 - Node Version 2.0.0 alpha 1

**Comment by Hypnos3** [comment]
Hmmm, das Problem mit dem Zufallswert, sit das dieser eben zufällig ist. Das bedeutet, das bei jedem ausführend er Regel ein anderer Zufallswert genommen wird und daher das mal in der Zeit und mal nicht innerhalb der Zeit ist.

**Comment by hvorragend** [comment]
Mir fällt auch leider keine Lösung ein. Außer vielleicht nicht zur Laufzeit berechnen. Aber das ist vermutlich nicht möglich. 
Auch Regel-intern ist das schwierig aufzufangen. Somit ist die Zufallsfunktion eigentlich zu riskant/fehleranfällig, oder?

**Comment by Hypnos3** [comment]
Der zufallswert sollte mit der nächsten version nur noch einmal pro Tag neu berechnet werden.

**Comment by hvorragend** [comment]
Ich freue mich, dass du wieder aktiv bist und eine Lösung gefunden hast. Vielen Dank.

**Comment by Hypnos3** [comment]
Das ist in der aktuellen beta enthalten. Ich bin aber noch nicht dazu gekommen das zu testen.

**Comment by Hypnos3** [comment]
Ab 2.0.0 beta-4 ist das integriert. (In den vorherigen Versionen gibt es noch ein Problem.) Ich mach das issue mal zu um den Überblick zu behalten.

**Comment by hvorragend** [comment]
Danke fürs Testen und Fixen. 
Ich hätte wohl geholfen; wäre aber vermutlich gescheitert.

**Comment by hvorragend** [comment]
Ich denke, dass wir das Ticket wieder öffnen müssen. Mir ist aufgefallen, dass alle Nodes mit exakt dem gleichen Zufallswert ausgelöst werden. 

Das Entzerren über Zufall ist damit - Node-intern - leider nicht möglich.

**Comment by hvorragend** [comment]
Wenn ich mir den Code anschaue, so könnte das gewollt sein, oder?
Der Zufallswert (für den Tag) wird nicht für jedes Node festgelegt, gelle?

**Comment by hvorragend** [comment]
@Hypnos3 Hast du das hier gesehen? Vielen Dank.

**Comment by hvorragend** [comment]
Es ist aber richtig, dass es auch in der v2.0.3 keine Möglichkeit gibt, den Zufalls-Offset Node-individuell zu steuern, oder?
Das Offset ist und bleibt also bei allen aktiven Blind-Nodes identisch, gelle?

**Comment by Hypnos3** [comment]
Der Zufallswert wird für jede Node getrennt festgelegt und lässt sich über den Context der Node auch einsehen. Nur innerhalb einer Node ist dieser für ein Limit gleich (also auch rule übergreifend).
Wenn man dort verschiedene Zufallswerte möchte muss man verschiedene Limits wählen, dabei kann auch eine Stelle nach dem Komma unterschiedlich sein.
