### ISSUE TITLE
Moon set Date wrong 

### ISSUE THREAD

**Issue by syswombat** [rdmtc/node-red-contrib-sun-position#307]
doing a node Red request i got this Date/time

times: object
rise: "2021-07-24T20:01:51.805Z"
set: "2021-07-24T04:00:00.897Z"
alwaysUp: false
alwaysDown: false

But the Date for set should be the next day not back in time

node-red-contrib-sun-position 1.2.4
node-red 1.3.5

have a nice day
vinc

**Comment by Hypnos3** [comment]
The is more a desired behavior.

The "Mone-position" node indicates the rising and setting of the moon for the current day.

I will add an additional property `timesNext` for the next day in the next version:
![image](https://user-images.githubusercontent.com/12692680/133150191-01470472-824a-4be7-b858-4909a803b869.png)

Additionally the mon set / rise times can be get by the enhances Inject node. There is a configuration option to always get the next time:
![image](https://user-images.githubusercontent.com/12692680/133150356-3b48f2ac-cbdb-42c3-ba88-fa78475dcd97.png)

**Comment by Hypnos3** [comment]
Is integrated in the 2.0.0-beta and can be installed, see Releases Information.
