### ISSUE TITLE
Rollladen knoten bearbeiten hat einen Fehler.

### ISSUE THREAD

**Issue by ThomasLoeffel** [rdmtc/node-red-contrib-sun-position#31]
Im unteren Bereich gibt es einen Link: Dokumentation und Beispiele.

Hier der nicht funktionierende Link
https: //github.com/rdmtc/node-red-contrib-sun-position/blob/HEAD/blind_control.md

So geht der Link bei mir:
https://github.com/rdmtc/node-red-contrib-sun-position/blob/HEAD/blind_control.md

Scheint ein Leerzeichen zu viel zu sein.
Gruß Thomas

**Comment by Hypnos3** [comment]
Danke!
ist im nächsten releade gefixed!

**Comment by ThomasLoeffel** [comment]
Jop bestätigt, geht!

Gruß Thomas
