### ISSUE TITLE
Rollladen node Beispiel hat einen Bug

### ISSUE THREAD

**Issue by ThomasLoeffel** [rdmtc/node-red-contrib-sun-position#32]
Hallo Zusammen,

ich habe zwei Sachen bei dem Beispiel mit der Funktion "test" gefunden.
1) Wenn man mehr als 24h laufen lässt verstrubelt sich die node total. Mache ich was falsch? Das bedeutet sie fängt nicht mehr mit der Regel 1 an.
2) Wenn man in der Funktion "test" vom Zyklus 30 min auf 1h wechselt fasst die Bedingung 06:30 Uhr nicht mehr. Soll das so sein?

Gruß Thomas

**Comment by Hypnos3** [comment]
Hallo,

zu 1.) ja, das kann ich nachvollziehen.
Die test-node addiert einfach immer die Zeit. Nach Mitternacht ist dann der nächste Tag.

Die Rollladen Node vergleicht die Zeit mit den Rule Zeiten. Diese haben als Basis immer die aktuelle Zeit und nicht die von der test-node vorgegebene und damit immer den aktuellen Tag. Damit liegt die Vergleichszeit immer nach der Zeit der letzten Rule.

Muss ich anpassen.

zu 2.) Kann ich nicht nachvollziehen.
Wenn ich den Zyklus auf 60 (=60 Minuten) ändere, und erneut start/stop betätige läuft es mit until 6:30 wieder los.

Man muss noch beachten welche Zahl man mit dem inject Node vorgibt. Das ist die Stunde, ab der es los läuft. Also wenn man da eine 7 hat, geht das ab 7 Uhr los und damit ist man bereits nach 6:30 Uhr.

Gruß


Gruß

**Comment by ThomasLoeffel** [comment]
Hi,

ggf. habe ich mich auch falsch ausgedrückt. Wenn Du in 30 min Schritten zählst greift Rule 1 = Rollladen auf "1". Wenn Du in 60 Minuten Schritten zählst greift Regel 1 nicht mehr. Soll das so sein?

Gruß Thomas

**Comment by Hypnos3** [comment]
So ganz verstehe ich es leider noch nicht, aber ich habe folgendes beobachtet:

Bis 6:30 Uhr, geht die Regel 1 aktiv und der Rolladen ist geschlossen.
Regel 2 geht nur am Wochenende aktiv.
Regel 3 nur bis "civilDawn". Das ist im Sommer gegen 4 Uhr, also vor Regel 1 und damit nie. Das ist erst im Winter.

Nach 6:30 ist also in der Woche keine Regel aktiv. Es gibt mit der Voreinstellung einen kurzen Bereich, wo die Sonne nicht in das Fenster scheint und der Rolladen öffnet.
untere Node:
![image](https://user-images.githubusercontent.com/12692680/59939925-9e478c00-9459-11e9-8790-726f2dc2ba01.png)

Danach scheint die Sonne in das Fenster (bei mir ist das 7 Uhr) und die Sonnensteuerung geht aktiv:
![image](https://user-images.githubusercontent.com/12692680/59940124-29c11d00-945a-11e9-8022-7acf698654e5.png)

Wenn man das stündlich anstelle halbstündlich macht (oberer Zweig), wird ja gleich von 6:30 Uhr auf 7 Uhr gesprungen und damit diese Zeit dazwischen übersprungen. Daher sieht mand as da nicht.

Ob das Verhalten bei dir genauso ist, kommt aber auch darauf an welche Koordinaten man eingegeben hat (wo man wohnt).

**Comment by ThomasLoeffel** [comment]
Hallo hypnos,

super erklärt. Genau das ist passiert. 

Ich habe einmal folgendes getestet:
Regel 1: Endet um 06:30 Uhr mit 0%
Regel 2: Startet um 06:30 Uhr mit 25%
Regel 3 Endet um 09:00 Uhr mit 25%
Sonst Standardposition 100%

Mit 1h Schritten durchlaufen und es klappt. Somit hattest Du völlig Recht, dass nur die Regel im Beispiel übersprungen wird, da die Zeit weiter fortgeschritten war als die Regel Gültigkeit hatte. Somit war sie in der Ausgabe auch nicht sichtbar (genau das war mir aufgefallen). Also alles läuft richtig :-.

Danke Dir !
Gruß Thomas

**Comment by ThomasLoeffel** [comment]
Jop bestätigt, geht!

Gruß Thomas
