### ISSUE TITLE
Visually indication of the current mode (Summer / Winter) when modes is changed via msg

### ISSUE THREAD

**Issue by jonferreira** [rdmtc/node-red-contrib-sun-position#321]
We currently have the "sun" and "snowmen?" icons showing the mode the node is is. However if the mode is changed via msg the icon doesn't change accordingly. AFAIK there's no visual way to quickly tell which mode a specific node is in?

**Describe the solution you'd like**
Change the icons according to the current mode the node is in

**Describe alternatives you've considered**
Add mode to the node.state

**Comment by Hypnos3** [comment]
Maybe I can add the current mode to the node-status as well.

**Comment by jonferreira** [comment]
that would be golden!

**Comment by jonferreira** [comment]
Just put together a quick fix for this, not really worth a PR since it's probably not the "best" way to do it anyway:

`this.setState = blindCtrl => {
            let code = node.reason.code;
            let shape = 'ring';
            let fill = 'yellow';
            if (code === 10 && node.previousData) { // smooth;
                code = node.previousData.reasonCode;
            }

            if (blindCtrl.level === node.nodeData.levelTop) {
                shape = 'dot';
            }
            if (isNaN(code)) {
                fill = 'red'; // block
                shape = 'dot';
            } else if (code <= 3) {
                fill = 'blue'; // override
            } else if (code === 4 || code === 15 || code === 16) {
                fill = 'grey'; // rule
            } else if (code === 1 || code === 8) {
                fill = 'green'; // not in window or oversteerExceeded
            }
			
			let mode = '';
			
			if (node.sunData.mode === 1){
				mode = '❆';
				//mode = 'Winter ';
			} else if (node.sunData.mode === 2) {
				mode = '☼';
				//mode = 'Summer ';
			}

            node.reason.stateComplete = mode + ((isNaN(blindCtrl.level)) ? node.reason.state : blindCtrl.level.toString() + ' - ' + node.reason.state);
            node.status({
                fill,
                shape,
                text: node.reason.stateComplete
            });
        };`

**Comment by Hypnos3** [comment]
Is integrated in the 2.0.0-beta and can be installed, see Releases Information.
