### ISSUE TITLE
The jsonata function getSunTimeByName isn't usable with the node "inject enhanced"

### ISSUE THREAD

**Issue by Bjo-Frei** [rdmtc/node-red-contrib-sun-position#326]
**Describe the bug**
By using the node "inject enhanced" with the jsonata function getSunTimeByName an error is thrown:
"Could not evaluate jsonata.$getSunTimeByName("nadir"). - Maybe settings outdated (open and save again)!"

**Screenshots**
![grafik](https://user-images.githubusercontent.com/2911251/133941403-d1e4a8a5-f7dd-48b1-8997-b5136925d5f6.png)

**Expected behavior**

**System information (please complete the following information):**
 - Node Version 14.17.6 
 - Node-Red Version 2.0.6

**Comment by Hypnos3** [comment]
fixed with node-red-contrib-sun-position@2.0.0-beta-7
