### ISSUE TITLE
Rollladen node, Prio Auswertung

### ISSUE THREAD

**Issue by ThomasLoeffel** [rdmtc/node-red-contrib-sun-position#33]
Hallo hypnos,

ich habe gerade die Input Prio-Steuerung getestet. Mir ist aufgefallen das Prio 1 niedriger in der Bewertung als Prio 2 ist. In meinem Sprachgebrauch hätte ich eher erwartet, wenn ich Prio 1 sage das dieses am höchsten ist. Ansonsten echt super node :-).

Lieben Gruß Thomas

**Comment by Hypnos3** [comment]
:-)
Ich werde es in der Doku noch verbessern. - Hier was zu ändern könnte bei Nutzern welche die Node bereits Nutzen zu Problemen führen.

**Comment by ThomasLoeffel** [comment]
Ok Danke :-).

Gruß Thomas
