### ISSUE TITLE
Coordinates cannot be saved

### ISSUE THREAD

**Issue by DerLoco** [rdmtc/node-red-contrib-sun-position#337]
I would like to use the node "within time-switch" but I am not able to save the coordinates of my position. To be consistent and to avoid any differences, I evaluated the coordinates via Openstreetmap.

When I save the coordinates, everything seems to be fine. After deploying the changes, an error occurs:

Error: Koordinaten für den Breitengrad und Längengrad ist falsch!

**Comment by DerLoco** [comment]
Any updates here?

**Comment by Hypnos3** [comment]
I have not been able to reproduce the error in this form so far. Since I am now using the 2.0.0 version myself and I am not aware of any new bugs, I will release this version.

**Comment by Hypnos3** [comment]
Can you please test this with Version 2.0.1?

**Comment by DerLoco** [comment]
Sorry for late reply, the last version I´ve updated to now 2.0.5. Now the error message does not occur anymore :)

**Comment by DerLoco** [comment]
so
