### ISSUE TITLE
Next occurrence bei Vergleich

### ISSUE THREAD

**Issue by klfa** [rdmtc/node-red-contrib-sun-position#339]
Hallo,

zunächst vielen Dank für die tolle Arbeit. Ich nutze den compare-node zum Vergleich zwischen einer vorgegebenen Uhrzeit und dem Sonnenstand. Der Sonnenstand wird beim Vergleich allerdings immer auf den aktuellen Tag bezogen. Gibt es hier eine Möglichkeit next occurrence einzustellen wie beim output?

Viele Grüße

**Comment by Hypnos3** [comment]
Hallo,

die compare-node benötigt mal ein update. Da kann ich mal schauen ob ich das dort mit einbauen kann.

Gruß
