### ISSUE TITLE
Fehler in der Abarbeitung der blind-Node von ca. "00:00:01 am" bis ca. "01:59:59 am"

### ISSUE THREAD

**Issue by ThomasLoeffel** [rdmtc/node-red-contrib-sun-position#34]
Hallo hypnos,

ich habe durch Zufall festgestellt das im Zeitraum „00:00:01 am“ bis ca. „01:59:59 am“ die blind-Node völlig aus dem Ruder kommt. 

Was passiert:
Als ich mit Deinem Beispiel so experimentierte kam der Tageswechsel. Ich bemerkte dann das in der Node die Regel 1, Regel 2 und Regel 3 nicht mehr angesprochen wurde und nur die Regel 4 stehen blieb. Egal was ich auch machte. "start/stop", Neustart von Redmatic, Neustart der CCU. Dann spielte ich an der Zeit in der CCU rum und stellte mal auf „02:01:00 am“ und es funktionierte wieder wie gehabt. Danach stellte ich wieder zurück auf Ortszeit und es funktionierte nicht mehr. Keine Ahnung ob das zu anderen Zeitfenstern auch so ist. Der gleiche Fehler tritt auf, wenn ich anstatt des „start/stop“ eine normale „inject-node“ mit Zeitstempel nehme.

Gruß Thomas

**Comment by Hypnos3** [comment]
Der Fehler tritt auf, weil die Node intern mit UTC rechnet und da ist es bis 2 Uhr aktuell noch der Tag vorher.
Das Problem sit mir bekannt und dich hab an der Stelle bereits einiges in der aktuell in Entwicklung befindlichen Version geändert.

**Comment by Hypnos3** [comment]
Ich bin nicht ganz sicher ob das Problem schon vollständig mit 0.4.2 behoben wurde und würde mich daher um Rückmeldung freuen.

**Comment by ThomasLoeffel** [comment]
Hallo hypnos,

ich habe die Systemzeit auf 00:00:00 gestellt und es geht jetzt. Versuche die Tage mal real 00:00 Uhr werden zu lassen. 

Danke und Gruß Thomas
