### ISSUE TITLE
Regeln und Lamellenposition 

### ISSUE THREAD

**Issue by webman2030** [rdmtc/node-red-contrib-sun-position#345]
Hi,

ich würde gerne die Lamellen meiner Raffstores bei "Fenster" Öffnung drehen.
Ich wollte dabei so vorgehen wie du unter [https://github.com/rdmtc/RedMatic/wiki/Rollladen-und-Jalousiesteuerung#wie-die-regelauswertung-funktioniert](https://github.com/rdmtc/RedMatic/wiki/Rollladen-und-Jalousiesteuerung#wie-die-regelauswertung-funktioniert) beschrieben hast.

Leider lässt sich die Lamellenpostion nicht einstellen wenn man Min oder Max bei der Rollladenpostion auswählt.
Im Grunde möchte ich, das wenn der Raffstore in der **Nacht** **geschlossen** ist, das sich die Lamellen nach %-Eingabe öffnen/drehen.

Wenn ich Absolut auswähle und der Raffstore ist offen, schließt er ihn und dreht dann die Lamelle ... natürlich sinnfrei ...

Stehe ich auf dem Schlauch oder ist das tatsächlich nicht möglich.

EDIT:  wenn ich es vorerst so lösen möchte wie in dem Beispiel mit dem Rollo, dann sendet er auch noch ein slat:0, was die Lamelle nach dem hoch fahren wieder komplett schließt

Grüße aus der nähe von München!
Flo

**Comment by Hypnos3** [comment]
Hallo,

ich hab selbst keine Lamellen. Da die Anforderung für die lamellensteuerung mehrfach aufkam, hab ich diese ab der Version 2.0.0 der node als ein zusätzlicher Parameter mit aufgenommen. Das ist aber nur zusätzlich und nicht wirklich in die Steuerung integriert. Damit geht das min und max nur mit der Rolladenposition und es ist auch nicht möglich nur die Lamellenposition zu verändern.

Deine Anforderung lässt sich aktuell nicht so einfach umsetzen. Du könntest eine Bedingte Regel erstellen, welche eine feste Rollladenposition vorgibt, bei der die Lamellen geöffnet sind, aber das verändert unter umständen die Rollladenposition.

Ich nehme das mal als Wunsch mit auf, vielleicht fällt mir eine Idee ein, wie man das integrieren kann.

Gruß

**Comment by Hypnos3** [comment]
In der Version 2.0.1 hab ich die Möglichkeit eingebaut eine Regel aufzusetzen, welche nur die Lamellenposition überschreibt. Damit sollte sich das umsetzen lassen.

Ich hab dass aber nicht wirklich getestet. Daher die Bitte das mal zu testen und mir zu berichten ob es geht.

**Comment by webman2030** [comment]
Funktioniert wunderbar, danke dir!
