### ISSUE TITLE
Clock-Timer: disabling a rule by unselecting all weekdays reenables all weekdays

### ISSUE THREAD

**Issue by lumpidu** [rdmtc/node-red-contrib-sun-position#349]
**Describe the bug**
Disabling a rule by unselecting all weekdays reenables all weekdays.

**Expected behavior**
The rule should be disabled.

**System information (please complete the following information):**
 - Node Version 1.2.4
 - Node-Red Version: 2.3.1

**Additional context**
As a workaround to debug a rule, I need to uncomment the current month

**Comment by Hypnos3** [comment]
This is not a common way for disabling a rule.
It is a consciously wanted behavior that is chosen every day.

One way for disabling rules will be to add a condition which will never be true.

I will think about an other way for disable rules.

**Comment by Hypnos3** [comment]
implemented rule enable/disable in 2.0.3
