### ISSUE TITLE
clock-timer: can't get to work day/night object

### ISSUE THREAD

**Issue by lumpidu** [rdmtc/node-red-contrib-sun-position#350]
**Describe the bug**
I try to get my head around the rules used for the clock-timer module. I try to implement a day/night object, that I send over to the KNX Bus.

The implementation should send `true` for the daytime and `false` for the nighttime. I created two clock-time modules: one for the work week, and one for the weekend. See the attached screenshots.

Let' refer only to the weekend rule:

Daytime: Sunset - 01:59 in the night
Night: 02:00 - Sunset

But it seems, that even now at 11:33 the night rule is active, instead of the day rule and although the night has a Until Time set to Sunset.

```
{
  topic: 'autoTrigger/triggerOnly/start',
  payload: false,
  triggerOnly: true,
  timeCtrl: {
    autoTrigger: { defaultTime: '600000', time: '600000', type: 0 },
    lastEvaluated: { ruleId: 2, ruleTopic: '', payload: false, topic: '' },
    name: 'Wochenende',
    id: '0ce0108392933434',
    rule: {
      id: 2,
      name: 'Nacht',
      importance: 0,
      resetOverwrite: false,
      code: 4,
      topic: '',
      active: true,
      outputValue: undefined,
      outputType: undefined,
      conditional: false,
      timeLimited: true,
      payloadData: {
        type: 'bool',
        value: 'false',
        format: '',
        offsetType: 'none',
        offset: '',
        multiplier: 60000,
        next: true
      },
      time: {
        value: 2021-11-07T02:00:00.000Z,
        error: null,
        fix: true,
        source: 'Default',
        ts: 1636250400000,
        dayId: 752122,
        timeLocal: '02:00:00',
        timeLocalDate: '07/11/2021',
        dateISO: '2021-11-07T02:00:00.000Z',
        dateUTC: 'Sun, 07 Nov 2021 02:00:00 GMT'
      },
      state: '↧ von 02:00:00 [2] Nacht',
      description: 'position by time - rule ↧ von 02:00:00 [2] Nacht'
    },
    reason: {
      code: 4,
      state: '↧ von 02:00:00 [2] Nacht',
      description: 'position by time - rule ↧ von 02:00:00 [2] Nacht',
      stateComplete: 'false - ↧ von 02:00:00 [2] Nacht'
    },
    timeClock: {
      payloadDefault: '',
      payloadDefaultType: 'none',
      payloadDefaultTimeFormat: 0,
      payloadDefaultOffset: 0,
      payloadDefaultOffsetType: 'none',
      payloadDefaultOffsetMultiplier: 60000,
      topic: '',
      overwrite: { active: false, expireDuration: NaN, importance: 0 }
    }
  },
  _msgid: '8bbfdcdc6dbee3be'
}
```
**Screenshots**

![grafik](https://user-images.githubusercontent.com/734966/140643068-0a39be0a-1bd0-4341-98c6-c9895ab70196.png)
![grafik](https://user-images.githubusercontent.com/734966/140643257-66df8524-4d77-4a95-8043-e436ee95e0d1.png)
![grafik](https://user-images.githubusercontent.com/734966/140643282-35444ab3-b7dc-4310-87b9-b2784fae456b.png)
![grafik](https://user-images.githubusercontent.com/734966/140643384-09fe784d-c0df-4483-bef6-012e8d98f2dd.png)

**Expected behavior**
There should be day at 11:33 :)

**System information (please complete the following information):**
 - Node Version 1.2.4
 - Node-Red Version: 2.3.1

**Comment by Hypnos3** [comment]
see https://github.com/rdmtc/node-red-contrib-sun-position/wiki/clock-timer#rules-execution-in-detail
- you have onle "from" rules, so the second is applied
  - If no rule was found of type **until**, the system evaluates the rules in descending order from the last rule.
    - Rules whose condition does not apply will be skipped.
    - The first rule, which has no time constraint or whose time is smaller than the current time, is chosen.
    - Further rules are not evaluated, even if they have no time constraint.

So your "day" rule will be never become active.

In your case I would set the default payload to day,
- one rule day as "until" sunrise which says night
- one rule day as "from" sunset which says night

**Comment by lumpidu** [comment]
Do I need to trigger the clock-timer module additionally via auto-timer or would it always trigger itself at least once per day ?

**Comment by Hypnos3** [comment]
It should trigger itself if Autotrigger is active in the advanced settings (default for new Nodes from version 2.0.0, for earlier nodes it is deactivated by default and needs to be activated).
The maximum interval could be configured as well and it should be 20min per default.

I would recommend that you update to the latest version as you are using a version below 2 and activate the auto triggering. This is available a long time and no problems where reported. Additional to Autotrigger it can be triggered manually.

**Comment by lumpidu** [comment]
Hmm, it seem the logic here is quite specific to something I am not used to. What I am used to is the term "One-Shot", "Alarm" and "Recurring" timer.

I would expect, that for a module that is called "Clock-Timer" I'd get the functionality of a specific alarm time that can be triggered as if you would set a normal alarm clock. If you have to autotrigger, that means the module is triggered with the current time of the autotrigger time to be evaluated against the given rules. One can of course do that, but why ? The node has already all info to know when it should be triggered.

The module should just evaluate the rules, set the specific time and activates the payload at the specified time. It even already does this time evaluation at the bottom of the rule editor. If there are interval dates (weekdays, months) given, then it should rearm itself to the next valid time of that interval. No need for auto-trigger that just delays the exact trigger time and is unnecessarily triggering for unwanted times.

Now coming to the rules: **from**, **until**: what do they really mean and why there is additionally earliest, latest ?
To my understanding, if I want e.g. to control my blinds, I'd like to say: at sunrise, but not earlier than 09:00 and no later than 10:00. So my **from** would be 09:00, my **until** 10:00 and my aimed time is whenever sunrise is in between. Here in Iceland, sunrise however can be at 02:00 in the morning, so I definetely don't want the blinds to go up then, so 09:00 should then be triggered. As well in December, sunrise is in the ballpark of 11:00, so I want the blinds to go up at 10:00 - my until rule.
What I miss is an "At" rule. How can I achieve that ? If there was an "At" rule, it would be possible to add multiple of those rules to one clock-timer node, where all these would be triggered at specified time with specified payload, which removes the necessity to add multiple clock-timer nodes for the same device.

**Comment by Hypnos3** [comment]
The logic is a little bit specific, but you can use one clock-timer node for the same device. Your mistake in thinking is that a rule does not specify a fixed point in time, but a time range. It can go from midnight, from a previous rule, to a subsequent rule, or until midnight.

The easiest setup is with 2 Rules:
 - You define a default payload which is when no rule is active.
 - Then you define a rule with a payload as "until" which should be active from midnight to the given time.
 - Then you define a rule with a payload as "from" which should be active from the given time until midnight.

So you have 3 time frames where you can define different payload. - That is all.

For each of the points in time, you can choose a fixed time or a flexible one depending on the sun control. But because you do not want to have these as a fixed value or later as a fixed value with the dynamic points in time, there is the possibility of defining the min and max.

This Example could be enhanced by more rules. In the wiki are any examples. So you could define rules only active on weekdays or on weekends, holidays, vacations,... (with different times) . In the end you have only one clock-timer node with lots of rules which will work in all circumstances. 

With the newer versions and active autotrigger, the idea is that node will send out the payload at the time of a change and internally also calculate the next time automatically. But there are situations where that doesn't work.  For example, if you use values ​​from contexts because the node does not know when the value changes.

**Comment by Hypnos3** [comment]
Another discussion gave rise to an idea that could simplify the rules as a whole.
That might help with this discussion too.
#357
