### ISSUE TITLE
[FR] Selectable context store

### ISSUE THREAD

**Issue by Hypnos3** [rdmtc/node-red-contrib-sun-position#351]
Allow to select context store for node contexts.

Maybe configurable in the Konfiguration node with overwrite Posibiliity in blind and clock timer.

**Comment by Hypnos3** [comment]
implemented in 2.0.2

**Comment by hvorragend** [comment]
Ist das korrekt, dass ich in hier nur die Werte "none" und "memory" habe?

**Comment by Hypnos3** [comment]
Das hängt von deiner Node-RED Konfiguration ab. Du scheinst nur einen Context Store konfiguriert zu haben, der nicht persistent ist (bedeutend ist beim Neustart weg). 
Bei None wird der default gewählt, was bei dir gleich memory ist, da du nur einen hast. 

Wenn du RedMatic nutzt kannst du einen zusätzlichen "file" Context Store in den RedMatic Einstellungen aktivieren (über die CCU WebUI).
Wenn du ein normales Node-RED benutzt kann man über die settings.json beliebige weitere Context Stores sich einrichten. Hierzu würde ich auf die Node-RED Dokumentation verweisen.
