### ISSUE TITLE
[FR] Selectable range for random number

### ISSUE THREAD

**Issue by Hypnos3** [rdmtc/node-red-contrib-sun-position#352]
For Random number allow also to define lower limit.
Maybe as range of the form 10.34-30.123

**Comment by Hypnos3** [comment]
implemented in 2.0.2

**Comment by hvorragend** [comment]
Really great. So I can remove my delay nodes.

**Comment by hvorragend** [comment]
I've found the following regex: `^(?:[1-9]|-0\.|0\.|-)\d*(?:\.\d+)?([\/|](?:[1-9]|-0\.|0\.|-)\d*(?:\.\d+)?)?$`
But could you please tell me which syntax I have to use?

**Comment by Hypnos3** [comment]
I have documented this already in the wiki.

The Regex allows
- one number
    - 20
    - -30
    - 20.123
    - -45.123
- two numbers separated by / or |
    - I plan to allow Komma and semicolon later to add. Originally I want to have a dash, but this collide with minus if the second number is negative.
