### ISSUE TITLE
Error: could not evaluate pdsTime.sunriseEnd

### ISSUE THREAD

**Issue by hvorragend** [rdmtc/node-red-contrib-sun-position#353]
**Describe the bug**

There was something wrong with my node packages and I have to reinstall your node collection again and manually. 
After that all my blind node have this error:
`internal error: Error "could not read property 5 of undefined", could not evaluate pdsTime.sunriseEnd`

**Screenshots**
![image](https://user-images.githubusercontent.com/343705/140647190-590bae83-9b44-45c2-b51f-e5f164ed7aa0.png)

**Expected behavior**
No errors

**System information (please complete the following information):**
 - Node Version 2.0.1
 - Node-Red Version: 10.0.1

**Comment by hvorragend** [comment]
Hmm, seems to be related with the latest random number fix.
I will try to re-configure all blind node with random offsets.

**Comment by hvorragend** [comment]
So it is. After my jumps from 2.0.0-beta-14 to 2.0.1 I have to reconfigure all rules again.

**Comment by Hypnos3** [comment]
Es gibt noch mehr Probleme...

**Comment by Hypnos3** [comment]
There was a problem with the random configuration. You need to reconfigure all rules which uses the random numbers.
