### ISSUE TITLE
blind-control node, message with setBlindSettingsBottom set to 0 does not work

### ISSUE THREAD

**Issue by waynethomas69** [rdmtc/node-red-contrib-sun-position#359]
**Describe the bug**
I modify the minimum setting of a blind-control node based upon a window sensor. If the window is closed, the blind can close fully, but if the window is open it can only close 50%. I set the blind default closed position to 0% in the node, then modify this value using a message.
![image](https://user-images.githubusercontent.com/22013674/141529932-250b7ccc-fedd-474b-84e2-0fb6287db7fc.png)
When the window is opened a function creates a message which is sent to modify the minimum level to 50%
`var minMsg = { topic: "setBlindSettingsBottom",payload: 50};`
`node.send(minMsg);`
When the window is closed the same function changes the minimum back to 0%
`var minMsg = { topic: "setBlindSettingsBottom",payload: 0};`
`node.send(minMsg);`
The 50% message clearly works, since the blind only closes to half way when the sun is in the window, or when the blinds are commanded to close after sunset. This can be seen in the level and levelInverse values of the second output of the blind-control node:
![image](https://user-images.githubusercontent.com/22013674/141531293-e261f9b1-4068-4a0b-9c14-05b1492eb384.png)
The message to change the minimum back to 0% does nothing however, and the minimum remains stuck at 50% until the node is restarted. This is confirmed by checking the second output of the node which shows the levelInverse is still stuck at 50 (message also shown to prove that 0 was sent):
![image](https://user-images.githubusercontent.com/22013674/141531469-fd2d6832-6239-4914-99a3-d47c092e6a81.png)
As a work around, I send a minimum value of 1 when the window is closed (rather than 0). This does work, so clearly the issue is the node is ignoring setBlindSettingsBottom when the value == 0.
`var minMsg = { topic: "setBlindSettingsBottom",payload: 1};`
`node.send(minMsg);`
![image](https://user-images.githubusercontent.com/22013674/141531851-cc80b330-a435-486e-b015-e2e5051e3813.png)

**Expected behavior**
When a message with topic setBlindSettingsBottom is received with a payload of 0 the minimum allowed blind setting will be set to 0.

**System information (please complete the following information):**
 - Node Version 2.0.4
 - Node-Red Version 1.0.6

**Comment by Hypnos3** [comment]
yes, javascript is sometimes tricky

**Comment by Hypnos3** [comment]
should be fixed with 2.0.5
