### ISSUE TITLE
Idee zur Verbesserung blind node, Regenschliessung und Nachtöffnung

### ISSUE THREAD

**Issue by ThomasLoeffel** [rdmtc/node-red-contrib-sun-position#36]
Hallo hypnos,

folgenden Fall möchte ich realisieren. Wenn nachts das Fenster offen steht soll der Rollladen in eine Öffnung 10% gehen. Dabei öffnen sich bei mir die Lamellen zwischen den Elementen.

Nun versuche ich dieses zu realisieren. Ich habe festgestellt das ich die Regeln benutzen muss. Aber ich kann nur eine Bedingung jeweils verwenden. Beispiel: Es ist Wochenende (Bedingung siehe Beispiel), aber dazu noch Fenster offen. Wenn ich dieses realisieren möchte muss ich im Vorfeld alles in einer Funktion hinterlegen und den Kontext abspeichern. Ggf. ist es einfacher den Fensterzustand mit anzuwählen bei der die Bedingung gilt.

Weiterhin versuche ich die Rollladen bei Regen zu schließen (auf 50%, dann hängen diese vor dem geöffneten Fenster) um zu verhindern das es reinregnet. Hierfür benutze ich derzeit die Übersteuerung. Ggf. kann dieses ja auch die node abarbeiten :-). Bedingung: Fenster offen, es regnet und der Rollladen ist mehr als (in diesem Fall) 50% geöffnet.

Lieben Gruß und danke für die super Arbeit!
Thomas

**Comment by Hypnos3** [comment]
Über so etwas hab ich auch schon nachgedacht. Leider ist die Node schon sehr komplex und damit würde das nochmals eine Stufe komplexer. (Soll ja noch verständlich sein.)
Muss ich mir noch mal eine Lösung überlegen.

Eine weitere Möglichkeit aktuell ist es dass damit zu realisieren, indem man nach der node noch weitere Logik hat. Dazu wird sehr detailliert der Status mitgesendet (zugeschlagene Regel, status-code, override aktiv, ...). Damit kann man sehr einfach zusätzliche Bedingungen (wenn rule x oder y aktiv, dann Behanghöhe z) mit switch und change nodes realisieren. Wenn man die Node auf 2 Ausgänge umstellt wird auf dem 2. Ausgang dann auch bei jeder Eingangsnachricht eine Ausgangsnachricht erzeugt.

**Comment by Hypnos3** [comment]
In der neuen Version (0.4.4-beta) gibt es ein neues Beispiel mit min/max Regeln.
Damit kann man den Wunsch auch umsetzen.
