### ISSUE TITLE
within - time, ivalid properties

### ISSUE THREAD

**Issue by damiensky** [rdmtc/node-red-contrib-sun-position#363]
Hello,

the node "within -time" signals invalid properties for -withinTimeValue -outofTimeValue if there is "msg.payload of the input message" is selected.
Version 2.0.5

![1](https://user-images.githubusercontent.com/94381971/141807050-73cfe2d6-c88a-4be8-bddc-4eea8b285fd8.jpg)

![2](https://user-images.githubusercontent.com/94381971/141807168-e297daa1-0657-4ed4-a941-5411d70c184b.JPG)

**Comment by Hypnos3** [comment]
Can you please export the node and send it to me?

I think this is because of properties which are not correctly migrated.

**Comment by damiensky** [comment]
Hi Hypnos3,

follwing the exported json of the node.

[
    {
        "id": "1ea7ce8e.05a261",
        "type": "within-time-switch",
        "z": "dd9bf63a.efa68",
        "name": "",
        "nameInt": "",
        "positionConfig": "6ef5f158.34acd8",
        "startTime": "23:50",
        "startTimeType": "entered",
        "startOffset": 0,
        "startOffsetType": "none",
        "startOffsetMultiplier": 60000,
        "endTime": "00:05",
        "endTimeType": "entered",
        "endOffset": 0,
        "endOffsetType": "none",
        "endOffsetMultiplier": 60000,
        "timeRestrictions": 0,
        "timeRestrictionsType": "none",
        "timeDays": "*",
        "timeOnlyOddDays": false,
        "timeOnlyEvenDays": false,
        "timeOnlyOddWeeks": false,
        "timeOnlyEvenWeeks": false,
        "timeMonths": "*",
        "timedatestart": "",
        "timedateend": "",
        "propertyStart": "",
        "propertyStartType": "none",
        "propertyStartCompare": "true",
        "propertyStartThreshold": "",
        "propertyStartThresholdType": "num",
        "startTimeAlt": "",
        "startTimeAltType": "entered",
        "startOffsetAlt": 0,
        "startOffsetAltType": "none",
        "startOffsetAltMultiplier": 60000,
        "propertyEnd": "",
        "propertyEndType": "none",
        "propertyEndCompare": "true",
        "propertyEndThreshold": "",
        "propertyEndThresholdType": "num",
        "endTimeAlt": "",
        "endTimeAltType": "entered",
        "endOffsetAlt": 0,
        "endOffsetAltType": "none",
        "endOffsetAltMultiplier": 60000,
        "withinTimeValue": "",
        "withinTimeValueType": "input",
        "outOfTimeValue": "",
        "outOfTimeValueType": "input",
        "tsCompare": "0",
        "x": 320,
        "y": 120,
        "wires": [
            [],
            [
                "2972a8f9.0275"
            ]
        ]
    },
    {
        "id": "6ef5f158.34acd8",
        "type": "position-config",
        "name": "Time_New",
        "isValide": "true",
        "longitude": "0",
        "latitude": "0",
        "angleType": "deg",
        "timeZoneOffset": "99",
        "timeZoneDST": "0",
        "stateTimeFormat": "3",
        "stateDateFormat": "12",
        "contextStore": "memory"
    }
]

**Comment by bluebook1** [comment]
Same problem with me, exactly after updating the node.

**Comment by Hypnos3** [comment]
fixed with 2.0.6
