### ISSUE TITLE
inject enhanced False DATE

### ISSUE THREAD

**Issue by Rezcue** [rdmtc/node-red-contrib-sun-position#364]
**Describe the bug**
node-red-contrib-sun-position for NodeRED

Inject enhanced gives out the wrong date. Take a look at the screenshot.

**Screenshots**
![asdadnt](https://user-images.githubusercontent.com/79769809/141841809-36b50a71-7637-4cbd-a73d-e1c705f654fe.PNG)

![Unbenanasdasdasdnt](https://user-images.githubusercontent.com/79769809/141842517-74a8bb8a-59a0-4204-a299-3a30634265dc.PNG)

If i take the "timestamp"-option from this node is gives out the right date.

![Unbeaasasasasnannt](https://user-images.githubusercontent.com/79769809/141842731-8c16fa9d-3aa5-4656-a134-a0e67f0be20e.PNG)

**System information (please complete the following information):**
 - Node Version v14.17.5
 - Node-Red Version v2.1.3

**Additional context**
Found out something interesting: check this out.
Configs: 
![sdasdasdasnnt](https://user-images.githubusercontent.com/79769809/141845158-ac1a95c0-f111-4a3b-952d-0b2809215d19.PNG)

When i use that extra option it give out the right date sometimes :D 
I injected serveral times in row.

If you add 1 sec it gives out the right one every time.
Any idea why that happens :D? The conifg is on my timezone.

**Comment by Hypnos3** [comment]
fixed with 2.0.6
