### ISSUE TITLE
Advanced overwrite by incoming message not working for setSunDataFloorLength, and setSunDataMinAltitude

### ISSUE THREAD

**Issue by mglaabde** [rdmtc/node-red-contrib-sun-position#367]
**Describe the bug**
It is not possible to set SunData.FloorLength or SunData.MinAltitude by incoming message.
There's a switch case for msg.topic 'setSunDataTopic' that uses the msg.payload as node.sunData.topic. But with this, no payload in terms of actual numbers for FloorLength or MinAltitude can be provided
https://github.com/rdmtc/node-red-contrib-sun-position/blob/23285eb2525d60ea1ff520b21a3cb1e4aa99a6b3/nodes/blind-control.js#L1108

**Screenshots**
N/A

**Expected behavior**
Properties SunData.FloorLength or SunData.MinAltitude should be able to overwrite by incoming message with topic setSunDataFloorLength or setSunDataMinAltitude and respective number in msg.payload.
see https://github.com/rdmtc/node-red-contrib-sun-position/wiki/blind-control#sun-control-data

**System information (please complete the following information):**
 - Node Version 2.0.5
 - Node-Red Version 2.1.3

**Additional context**
N/A

**Comment by Hypnos3** [comment]
I can implement this for `setSunDataFloorLength`.

With `setSunDataMinAltitude` it is more difficult because this setting no longer exists in the current version. That is now mapped as an oversteer. For oversteers it is also possible to set it up in such a way that it can be influenced from outside.

**Comment by Hypnos3** [comment]
`setSunDataFloorLength` implemented in 2.0.6
