### ISSUE TITLE
Probleme mit der Blindversion 0.4.2

### ISSUE THREAD

**Issue by ThomasLoeffel** [rdmtc/node-red-contrib-sun-position#37]
Hallo hypnos,

ich teste immer noch mit Deinem Beispiel über 24h. Mir ist aufgefallen das zwei Sachen nicht mehr funktionieren. Dein Beispiel ist dabei direkt von der Seite kopiert: "https://github.com/rdmtc/node-red-contrib-sun-position/blob/HEAD/blind_control.md"

1)  Nach der „bis“ Regel wird „Die Sonne schein nicht ins Fenster“... angezeigt und er rechnet nicht mehr.
2) Bei der "von" Regel funktioniert die Möglichkeit mit "Wochenende&Feiertag" nicht mehr. Er wendet die Regel zwar an, aber nach der Regel 22:35 Uhr. Er sollte bei "von" Regel ja immer von unten nach oben schauen, oder? Somit kommt 22:35 mit „0“ und dann noch einmal 23:15 mit „0“.

Ich habe beides auf meinem iobroker mit der Version 0.4.1 getestet. Da geht Fall 1, Fall 2 auch nicht. 

Gruß Thomas

**Comment by Hypnos3** [comment]
Das Beispiel hat auch noch ein Problem.
Die Limitierung soll bei der 21:25 Regel sein, mit Vergleich auf `false` und nicht bei der 23 mit Vergleich auf `true`:
![image](https://user-images.githubusercontent.com/12692680/60348992-f6820f00-99c0-11e9-8d07-4611f3fd606e.png)

Ich hab jetzt eine neue Version Released und hoffe die Probleme beseitigt zu haben. Die Doku ist angepasst.
