### ISSUE TITLE
sun-position does not output any values

### ISSUE THREAD

**Issue by Nutti85** [rdmtc/node-red-contrib-sun-position#378]
**Describe the bug**
I'm using the node in a flow in Home Assistant to adjust lights based on the sun position.
Lately the sun-position node stopped outputting values and the lights stopped adjusting

**Expected behavior**
Node to output values

**System information (please complete the following information):**
 - Node Version: Unsure, guessing the latest version
 - Node-Red Version: 2.1.4

**Additional context**
```16 Dec 17:46:42 - [info] [position-config:Redacted] getSunCalc, time difference since last output to low, do no calculation
16 Dec 17:46:42 - [info] [position-config:Redacted] getSunCalc, time difference since last output to low, do no calculation
16 Dec 17:46:42 - [info] [position-config:Redacted] getSunCalc, time difference since last output to low, do no calculation
16 Dec 17:46:42 - [info] [position-config:Redacted4] getSunCalc, time difference since last output to low, do no calculation
16 Dec 17:46:42 - [info] [position-config:Redacted] getSunCalc, time difference since last output to low, do no calculation
16 Dec 17:46:42 - [info] [position-config:Redacted] getSunCalc, time difference since last output to low, do no calculation
16 Dec 17:46:42 - [debug] [api-call-service:Yttergang på (circadian)] Calling Service: light:turn_on -- {"transition":"5","kelvin":2000,"brightness_pct":86}
16 Dec 17:46:42 - [debug] [api-call-service:Innergang på (circadian)] Calling Service: light:turn_on -- {"transition":"5","kelvin":2000,"brightness_pct":86}
16 Dec 17:46:42 - [debug] [api-call-service:Spisestuebord på (circadian)] Calling Service: light:turn_on -- {"kelvin":2000,"brightness_pct":86}
16 Dec 17:46:42 - [debug] [api-call-service:Vindulys på (circadian)] Calling Service: light:turn_on -- {"kelvin":2000,"brightness_pct":86}
16 Dec 17:46:42 - [debug] [api-call-service:Takspot på (circadian)] Calling Service: light:turn_on -- {"kelvin":2000,"brightness_pct":86}
16 Dec 17:46:42 - [debug] [api-call-service:Cove pð￙� (circadian)] Calling Service: light:turn_on -- {"kelvin":2000,"brightness_pct":86}
16 Dec 17:46:42 - [debug] [api-call-service:Lounge på (circadian)] Calling Service: light:turn_on -- {"kelvin":2000,"brightness_pct":86}```

**Comment by Hypnos3** [comment]
I can' reproduce this:
![image](https://user-images.githubusercontent.com/12692680/149616797-7b0aee46-9068-4954-999f-5163c76573f0.png)

Flow:
```[{"id":"53ccca2f.a074c4","type":"inject","z":"3d1e98b3.641318","name":"","repeat":"","crontab":"","once":false,"onceDelay":0.1,"topic":"","payload":"","payloadType":"date","x":120,"y":300,"wires":[["5a9207f7.f92968"]]},{"id":"82e78222.0bc7e","type":"debug","z":"3d1e98b3.641318","name":"","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"payload","x":590,"y":300,"wires":[]},{"id":"5a9207f7.f92968","type":"sun-position","z":"3d1e98b3.641318","name":"","positionConfig":"14613f77.c25991","rules":[{"valueLow":"10","valueLowType":"num","valueHigh":"100","valueHighType":"num"}],"onlyOnChange":"true","topic":"","outputs":2,"start":"","startType":"none","startOffset":0,"startOffsetType":"num","startOffsetMultiplier":60000,"end":"","endType":"none","endOffset":0,"endOffsetType":"num","endOffsetMultiplier":60000,"x":330,"y":300,"wires":[["82e78222.0bc7e","6353563b.d0a118","50d2d4e9.ff28bc"],["35275fb2.9fbd3"]]},{"id":"6353563b.d0a118","type":"change","z":"3d1e98b3.641318","name":"azimuth","rules":[{"t":"set","p":"payload","pt":"msg","to":"payload.azimuth","tot":"msg"}],"action":"","property":"","from":"","to":"","reg":false,"x":580,"y":340,"wires":[["2794cce4.4822c4"]]},{"id":"50d2d4e9.ff28bc","type":"change","z":"3d1e98b3.641318","name":"altitude","rules":[{"t":"set","p":"payload","pt":"msg","to":"payload.altitude","tot":"msg"}],"action":"","property":"","from":"","to":"","reg":false,"x":580,"y":380,"wires":[["4e1c2aba.114544"]]},{"id":"35275fb2.9fbd3","type":"debug","z":"3d1e98b3.641318","name":"","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"true","x":570,"y":420,"wires":[]},{"id":"2794cce4.4822c4","type":"debug","z":"3d1e98b3.641318","name":"","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"payload","x":770,"y":340,"wires":[]},{"id":"4e1c2aba.114544","type":"debug","z":"3d1e98b3.641318","name":"","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"payload","x":770,"y":380,"wires":[]},{"id":"14613f77.c25991","type":"position-config","name":"zuHause","isValide":"true","longitude":"0","latitude":"0","angleType":"deg","timeZoneOffset":99,"timeZoneDST":0,"stateTimeFormat":"3","stateDateFormat":"12"}]```

Output:
```json
[{
		"id": "53ccca2f.a074c4",
		"type": "inject",
		"z": "3d1e98b3.641318",
		"name": "",
		"repeat": "",
		"crontab": "",
		"once": false,
		"onceDelay": 0.1,
		"topic": "",
		"payload": "",
		"payloadType": "date",
		"x": 120,
		"y": 300,
		"wires": [["5a9207f7.f92968"]]
	}, {
		"id": "82e78222.0bc7e",
		"type": "debug",
		"z": "3d1e98b3.641318",
		"name": "",
		"active": true,
		"tosidebar": true,
		"console": false,
		"tostatus": false,
		"complete": "payload",
		"x": 590,
		"y": 300,
		"wires": []
	}, {
		"id": "5a9207f7.f92968",
		"type": "sun-position",
		"z": "3d1e98b3.641318",
		"name": "",
		"positionConfig": "14613f77.c25991",
		"rules": [{
				"valueLow": "10",
				"valueLowType": "num",
				"valueHigh": "100",
				"valueHighType": "num"
			}
		],
		"onlyOnChange": "true",
		"topic": "",
		"outputs": 2,
		"start": "",
		"startType": "none",
		"startOffset": 0,
		"startOffsetType": "num",
		"startOffsetMultiplier": 60000,
		"end": "",
		"endType": "none",
		"endOffset": 0,
		"endOffsetType": "num",
		"endOffsetMultiplier": 60000,
		"x": 330,
		"y": 300,
		"wires": [["82e78222.0bc7e", "6353563b.d0a118", "50d2d4e9.ff28bc"], ["35275fb2.9fbd3"]]
	}, {
		"id": "6353563b.d0a118",
		"type": "change",
		"z": "3d1e98b3.641318",
		"name": "azimuth",
		"rules": [{
				"t": "set",
				"p": "payload",
				"pt": "msg",
				"to": "payload.azimuth",
				"tot": "msg"
			}
		],
		"action": "",
		"property": "",
		"from": "",
		"to": "",
		"reg": false,
		"x": 580,
		"y": 340,
		"wires": [["2794cce4.4822c4"]]
	}, {
		"id": "50d2d4e9.ff28bc",
		"type": "change",
		"z": "3d1e98b3.641318",
		"name": "altitude",
		"rules": [{
				"t": "set",
				"p": "payload",
				"pt": "msg",
				"to": "payload.altitude",
				"tot": "msg"
			}
		],
		"action": "",
		"property": "",
		"from": "",
		"to": "",
		"reg": false,
		"x": 580,
		"y": 380,
		"wires": [["4e1c2aba.114544"]]
	}, {
		"id": "35275fb2.9fbd3",
		"type": "debug",
		"z": "3d1e98b3.641318",
		"name": "",
		"active": true,
		"tosidebar": true,
		"console": false,
		"tostatus": false,
		"complete": "true",
		"x": 570,
		"y": 420,
		"wires": []
	}, {
		"id": "2794cce4.4822c4",
		"type": "debug",
		"z": "3d1e98b3.641318",
		"name": "",
		"active": true,
		"tosidebar": true,
		"console": false,
		"tostatus": false,
		"complete": "payload",
		"x": 770,
		"y": 340,
		"wires": []
	}, {
		"id": "4e1c2aba.114544",
		"type": "debug",
		"z": "3d1e98b3.641318",
		"name": "",
		"active": true,
		"tosidebar": true,
		"console": false,
		"tostatus": false,
		"complete": "payload",
		"x": 770,
		"y": 380,
		"wires": []
	}, {
		"id": "14613f77.c25991",
		"type": "position-config",
		"name": "zuHause",
		"isValide": "true",
		"longitude": "0",
		"latitude": "0",
		"angleType": "deg",
		"timeZoneOffset": 99,
		"timeZoneDST": 0,
		"stateTimeFormat": "3",
		"stateDateFormat": "12"
	}
]
```

**Comment by Hypnos3** [comment]
Maybe you could export your Flow?
