### ISSUE TITLE
blind control - manual override with -1 value is not working

### ISSUE THREAD

**Issue by 89Amaterasu** [rdmtc/node-red-contrib-sun-position#387]
Manual override using the level -1 is not working as expected.

**Expected behavior:**
When a manual override expires, the node is expected to revert back to the automatic calculated level, e.g. the cover closes again after it has been manually opened.

**Issue:**
When sending -1 as the manual override level, the override is activated and expires as expected, but the cover does not revert back to the expected level, e.g. the cover does not close again after it has been manually opened.

Using levels other than -1, the manual override is working as expected and the cover reverts back to the expected level, e.g. closes again after it has been manually opened.

Does somebody have the same issue?

**Comment by Hypnos3** [comment]
It is working for me.
Under the node should be the time when the manual override expires:
![image](https://user-images.githubusercontent.com/12692680/149617333-d9268a40-7a3d-4128-9f39-a005eb2530dc.png)

This time will be changed if another override arrives.

Do you sending the `-1` continuously?

**Comment by 89Amaterasu** [comment]
The issue is not the override not expiring, but rather that the level is not adjusted upon expiration.

If the default level is 100 and the cover level is manually changed to a certain unknown level (-1), the cover stays at the manually set level after expiration. I would expect the cover to revert back to 100.

Everything works fine and as expected for manual levels between 0 and 100 but not in case of -1. I hope that makes it more clear :)

In case of a -1 level override, the node just stays with the previous level and just adds a override to that. Since the node level does not change upon expiration, the node does not fire.

A quick fix would be the node firing after a -1 expiration. 

Manual -1 override:
100 --> 100(override) --> 100
Manual 50 override:
100 --> 50 (override) --> 100

**Comment by Hypnos3** [comment]
Ok I got it and was able to reproduce it. Will be fixed with the next release.

**Comment by 89Amaterasu** [comment]
Awesome, thanks!
