### ISSUE TITLE
Rules for specific days of week nog working as expected

### ISSUE THREAD

**Issue by mvandenabeele** [rdmtc/node-red-contrib-sun-position#389]
**Describe the bug**
I have a rule to open blinds at 7am on weekdays, and another rule to open blinds at 9am in the weekend. On weekdays, the blinds open at 9am too, as if it was Saturday or Sunday. 

**Screenshots**
![image](https://user-images.githubusercontent.com/6908633/148524749-a1004117-6b0f-4996-af51-0441709de871.png)

**Expected behavior**
Open at 7am from Monday until Friday, and at 9am in the weekend

The configuration of this node is:

`[{"id":"937a84ba.56a8c8","type":"blind-control","z":"35095591.36341a","name":"","topic":"","addIdType":"none","addId":"","positionConfig":"23787bb9.ec4374","autoTrigger":false,"autoTriggerTime":"600000","startDelayTime":"15000","contextStore":"","results":[{"p":"","pt":"msgTopic","v":"","vt":"topic"},{"p":"","pt":"msgPayload","v":"","vt":"level"},{"p":"slat","pt":"msg","v":"","vt":"slat"},{"p":"blindCtrl","pt":"msg","v":"","vt":"ctrlObj"}],"blindIncrement":"1","blindOpenPos":"100","blindClosedPos":"0","blindPosReverse":false,"blindPosDefault":"open (max)","blindPosDefaultType":"levelFixed","slatPosDefault":"","slatPosDefaultType":"none","overwriteExpire":"7200000","rules":[{"index":0,"name":"open on civilDawn, but not before 7","version":3,"enabled":true,"isValid":true,"conditions":[],"level":{"type":"levelFixed","value":"closed (min)","operator":0,"operatorText":"↕ absolute"},"slat":{"type":"none","value":""},"topic":"","resetOverwrite":false,"importance":0,"time":{"type":"pdsTime","value":"sunriseEnd","operator":0,"operatorText":"↥ until","offsetType":"none","offset":"1","multiplier":1,"days":"1,2,3,4,5","months":"*"},"timeMin":{"type":"entered","value":"7:00","offsetType":"none","offset":"1","multiplier":60000},"description":"<div><i class=\"fa fa-clock-o\" aria-hidden=\"true\"></i> ↥ until <var>sunrise end</var><div class=\"indent-time-text\"><i class=\"fa fa-step-backward\" aria-hidden=\"true\"></i> <span>at the earliest (min)</span> <var>7:00</var></div><div class=\"indent-time-days\"><i class=\"fa fa-calendar-o\" aria-hidden=\"true\"></i> <span>only on day</span> <var>Mon-Fri</var></div></div><div><div class=\"indent-level-text\"> <i class=\"fa fa-angle-down\" aria-hidden=\"true\"></i><span>blind position: </span> ↕ absolute <var>closed (min)</var></div></div>"},{"index":1,"name":"open on civilDawn, but not before 8","version":3,"enabled":true,"isValid":true,"conditions":[],"level":{"type":"levelFixed","value":"closed (min)","operator":0,"operatorText":"↕ absolute"},"slat":{"type":"none","value":""},"topic":"","resetOverwrite":false,"importance":0,"time":{"type":"pdsTime","value":"sunriseEnd","operator":0,"operatorText":"↥ until","offsetType":"none","offset":"1","multiplier":1,"days":"6,0","months":"*"},"timeMin":{"type":"entered","value":"9:00","offsetType":"none","offset":"1","multiplier":60000},"description":"<div><i class=\"fa fa-clock-o\" aria-hidden=\"true\"></i> ↥ until <var>sunrise end</var><div class=\"indent-time-text\"><i class=\"fa fa-step-backward\" aria-hidden=\"true\"></i> <span>at the earliest (min)</span> <var>9:00</var></div><div class=\"indent-time-days\"><i class=\"fa fa-calendar-o\" aria-hidden=\"true\"></i> <span>only on day</span> <var>Sat and Sun</var></div></div><div><div class=\"indent-level-text\"> <i class=\"fa fa-angle-down\" aria-hidden=\"true\"></i><span>blind position: </span> ↕ absolute <var>closed (min)</var></div></div>"},{"index":2,"name":"close at blue hour, but not later than 21:00","version":3,"enabled":true,"isValid":true,"conditions":[],"level":{"type":"levelFixed","value":"closed (min)","operator":0,"operatorText":"↕ absolute"},"slat":{"type":"none","value":""},"topic":"","resetOverwrite":false,"importance":0,"time":{"type":"pdsTime","value":"goldenHourDuskEnd","operator":1,"operatorText":"↧ from","offsetType":"none","offset":"1","multiplier":1,"days":"*","months":"*"},"timeMax":{"type":"entered","value":"21:00","offsetType":"none","offset":"1","multiplier":60000},"description":"<div><i class=\"fa fa-clock-o\" aria-hidden=\"true\"></i> ↧ from <var>golden hour dusk end</var><div class=\"indent-time-text\"><i class=\"fa fa-step-forward\" aria-hidden=\"true\"></i> <span>no later than (max)</span> <var>21:00</var></div></div><div><div class=\"indent-level-text\"> <i class=\"fa fa-angle-down\" aria-hidden=\"true\"></i><span>blind position: </span> ↕ absolute <var>closed (min)</var></div></div>"}],"sunControlMode":16,"sunFloorLengthType":"num","sunFloorLength":"","sunMinDelta":"","blindPosMin":"40","blindPosMinType":"num","blindPosMax":"open (max)","blindPosMaxType":"levelFixed","sunSlat":"","sunSlatType":"none","smoothTime":"","sunTopic":"","windowTopType":"num","windowTop":"239","windowBottomType":"num","windowBottom":"80","windowAzimuthStartType":"numAzimuth","windowAzimuthStart":"120","windowAzimuthEndType":"numAzimuth","windowAzimuthEnd":"288","oversteers":[],"oversteerTopic":"","x":950,"y":220,"wires":[["739f415b.0f413"],[]]},{"id":"23787bb9.ec4374","type":"position-config","name":"Thuis","isValide":"true","longitude":"0","latitude":"0","angleType":"deg","timeZoneOffset":99,"timeZoneDST":0,"stateTimeFormat":"3","stateDateFormat":"12"}]`

**Comment by Hypnos3** [comment]
I don't really understand the problem:
_On weekdays, the blinds open at 9am too, as if it was Saturday or Sunday._

In your rules the blinds oben on "sunrise end" on weekdays and on weekends.
 - If the "sunrise end" is before 7 on weekdays it will open at 7.
 - If the "sunrise end" is before 9 on weekends it will open at 9.
 - If the "sunrise end" is at 9 on weekdays it will open on 9 also on weekdays, as if it was Saturday or Sunday.

**Comment by mvandenabeele** [comment]
Hmm, I think it wasn't like that in an earlier version, but after having a look at the rules again, I might have been wrong indeed. It didn't help that it's not dark anymore at 8 am here in Belgium, so I expected sunrise end to be earlier. Sorry for the noise.

**Comment by Hypnos3** [comment]
I tried to reproduce this as a test case, it worked for me. I would now close the issue. If there are still problems it can be reopened.
