### ISSUE TITLE
Probleme mit der Blindversion 0.4.3

### ISSUE THREAD

**Issue by ThomasLoeffel** [rdmtc/node-red-contrib-sun-position#39]
Hallo hypnos,

leider habe ich die gleichen Probleme mit der Version 0.4.3.

Fall: Ich benutze dein Beispiel "flow" von Dir mit keinen Änderungen.
Es wird weder der Modus "Sonnenlichtbeschränken" ausgeführt, oder die richtige Regel "von" richtig angewendet. Wie in dem Issue "#37". Auf meinem iobroker läuft noch 0.4.1 da scheint der Modus noch zu funktionieren, aber die richtige Abarbeitung der Regel "von" nicht mehr. Bei mir führt er Regel 6 beim "Wochenende & Feiertag/Morgen" nicht aus.

Gruß Thomas

**Comment by Hypnos3** [comment]
Da ist irgendwas komplett schief.  Das muss ich mir noch mal in Ruhe ansehen (am besten wenn es kühler ist).

**Comment by ThomasLoeffel** [comment]
Kann ich Dir helfen? Brauchst Du noch was für die Fehlersuche?
Gruß Thomas

**Comment by Hypnos3** [comment]
Danke für das Angebot. Ich denke den Fehler gefunden zu haben. Ich muss aber noch weitere Tests machen und werde auch erstmal eine Beta-Version releasen.

**Comment by ThomasLoeffel** [comment]
Soll ich beim Testen helfen? Wie komme ich an die beta?
Gruß Thomas

PS. Danke für Deine super Arbeit!

**Comment by Hypnos3** [comment]
Ich hoffe die Probleme mit 0.4.4 behoben zu haben.

**Comment by ThomasLoeffel** [comment]
Hallo hypnos,

mein System findet über die Palette die Version 0.4.4 noch nicht. Bin schon gespannt. Oder muss ich die anderes laden, oder einfach nur warten :-)?

Gruß Thomas

**Comment by Hypnos3** [comment]
Einfach nur warten. Das kann bis zu ein paar Stunden dauern

**Comment by ThomasLoeffel** [comment]
Hallo hypnos,

jetzt konnte ich die Version 0.4.4 beta herunterladen. Ich habe Dein aktuelles Beispiel 3 herunter kopiert. Nun funktioniert die Berechnung der Beschattung super. Aber nicht alle "von" Bedingungen funktionieren. Die bürgerliche Abenddämmerung setzt um 05:01:00 PM ein und überspielt alle folgenden Bedingungen. Ist das so gewollt? Ich teste nun voller Spannung das Beispiel 4 :-).

Nur am Rande: Bei mir zerknittern immer die Auswahlfelder beim Öffnen. Sobald ich nach links oder rechts das Fenster ziehe ist das wieder ok. Liegt das am Browser?

Danke für Deine super Arbeit.
Thomas


![grafik](https://user-images.githubusercontent.com/44590735/60354744-33540300-99cd-11e9-9637-c68756fb9651.png)

![grafik](https://user-images.githubusercontent.com/44590735/60354369-5cc05f00-99cc-11e9-99c9-49a143c0092c.png)

![grafik](https://user-images.githubusercontent.com/44590735/60354422-782b6a00-99cc-11e9-87aa-515ecf1cf5c1.png)

![grafik](https://user-images.githubusercontent.com/44590735/60354926-aa899700-99cd-11e9-8047-fe91e57be40b.png)

**Comment by ThomasLoeffel** [comment]
Hallo hypnos,

ich habe einmal Beispiel 4 getestet. Danke für die großartigen Anregungen. 

Folgendes ist mir Aufgefallen:
- Fenster zu, Regen true -> dann braucht kann die Übersteuerung der Beschattung greifen und Rollladen hoch "1". Habe ich mal eingestellt funktioniert super.
- Fenster offen, Regen false -> dieses soll eine Nachtöffnung zur Belüftung werden. Am Tag braucht die nicht aktiv zu sein. Ich versuche das mal anzupassen. Derzeit übersteuert diese Regel alles :-).
- Fenster offen, Regen true -> hier soll tatsächlich immer der Rollladen herunterfahren damit es nicht reinregnet. Ich versuche mich mal an dieser Regel.

Lieben Gruß Thomas

**Comment by Hypnos3** [comment]
Bei mir ist die bürgerliche Abenddämmerung gegen 22 Uhr. Wenn ich mit einer anderen Zeit (Bsp Sonnenuntergang, bei mir ab 21:25 Uhr) teste,  kommt ab dieser Zeit die Regel 4, ab 21:45 die Regel 5 und ab 23;15 die Regel 6:
![image](https://user-images.githubusercontent.com/12692680/60367377-5b079300-99ee-11e9-9df1-aabc0865c3a3.png)

Bei dir ist es aber doch auch so:
ab 5:30 PM - wird Regel 4 -  bürgerliche Abenddämmerung sein
ab 9:30 PM - wird Regel 5 -  Woche ab 21:25
ab 11:30 PM - wird Regel 6 -  ab 23:15

Also ich sehe hier erstmal kein Problem.
------

Das "zerknittern" ist bekannt. Ich habe auch schon versucht den Grund zu finden. Es tritt leider bei mir nicht reproduzierbar immer auf.
Hier muss ich noch weiter untersuchen. Das hatte ich erstmal hinten angestellt um das Problem mit der Sonnenstand/Zeitberechnung zu beseitigen.

------

Die Regeln mit den Minimum/Maximum sind nicht einfach erklärt.
Also, wenn die keine Zeiteinschränkung haben gelten die immer. Wenn diese nur Nachts gelten sollen,  muss man die Zeit einschränken. Hier gibt es aber noch Probleme wo ich noch mehr Zeit brauche.

**Comment by ThomasLoeffel** [comment]
Hallo hypnos,

wenn ich die 24h Simualtion nehme passiert es mit den "von" Regeln genau wie beschrieben.
Egal ob nun Wochenende "true" oder "false" ist.

- ab 05:30 PM schliesst der Rollladen ("0")
- ab 09:30 PM schliesst der Rollladen erneut (also kommt erneut "0")
- ab 11:30 PM schliesst der Rollladen erneut (also kommt erneut "0")
......warum dieses auch immer passiert.....
Aber wenn ich Realzeit verwende und von Hand die Zeit in der CCU verändere ist alles "ok". Also kann ich anfangen die node produktiv zu setzen.

Vielen Dank für Deinen ständigen Einsatz und die schnellen Antworten und Anpassungen!

Lieben Gruß Thomas

**Comment by ThomasLoeffel** [comment]
Sorry verklickt :-)

**Comment by ThomasLoeffel** [comment]
Sorry verklickt :-)

**Comment by ThomasLoeffel** [comment]
Es scheint im Normalbetrieb alles zu laufen.

Danke !!
