### ISSUE TITLE
Rollladen Konfiguration 

### ISSUE THREAD

**Issue by SpaceRichard** [rdmtc/node-red-contrib-sun-position#397]
Hallo,

ich habe mich an der Rollladensteuerung versucht, leider stehe ich auf dem Schlauch.

Meine Idee bzw. Erwartungshaltung war das ich der Steuerung die aktuelle Position gebe und diese dann je nach Sonnenstand auf eine Wert fährt und diesen weiter steuert. 
Zu Testzwecken hatte ich versucht die Regeln noch außen vor zu lassen, bzw. hatte nur 2 bzgl Sonnenauf/untergang definiert.
Aktuell erhalte ich über den Ersten Ausgang aber kaum oder nur sehr selten eine Position und wenn dann nur 100 oder 0 

In dem Test hatte ich die Maße und Ausrichtung von 2 Fenster definiert, einmal nach Süden und einmal nach Westen.
Beide verhalten sich jedoch identisch und auch bei direktem Sonnenlicht bleiben die bei 100 (offen) oder gehen auf 0 um sollen somit komplett geschlossen sein.

Wo habe ich den Denkfehler?

* Version 2.0.8
* Node-Red Version 2.1.4

Hier mal der Node von einem Fenster nach Westen
`[
    {
        "id": "cdd44e3db52b0668",
        "type": "blind-control",
        "z": "eb3b6622877c1d1b",
        "name": "Esszimmer",
        "topic": "",
        "addIdType": "none",
        "addId": "",
        "positionConfig": "a8a878862d1b296f",
        "autoTrigger": true,
        "autoTriggerTime": "60000",
        "startDelayTime": "5000",
        "contextStore": "",
        "results": [
            {
                "p": "",
                "pt": "msgPayload",
                "v": "",
                "vt": "level"
            }
        ],
        "blindIncrement": "1",
        "blindOpenPos": "100",
        "blindClosedPos": 0,
        "blindPosReverse": false,
        "blindPosDefault": "open (max)",
        "blindPosDefaultType": "levelFixed",
        "slatPosDefault": "",
        "slatPosDefaultType": "none",
        "overwriteExpire": "10000",
        "rules": [
            {
                "index": 0,
                "name": "",
                "version": 3,
                "enabled": true,
                "isValid": true,
                "conditions": [],
                "level": {
                    "operator": 9,
                    "operatorText": "✋ nichts senden"
                },
                "time": {
                    "type": "pdsTime",
                    "value": "sunriseEnd",
                    "operator": 0,
                    "operatorText": "↥ bis",
                    "offsetType": "none",
                    "offset": "1",
                    "multiplier": 60000,
                    "days": "*",
                    "months": "*"
                },
                "description": "<div><i class=\"fa fa-clock-o\" aria-hidden=\"true\"></i> ↥ bis <var>Sonnenaufgang Ende</var></div><div>✋ nichts senden</div>",
                "importance": 0,
                "slat": {
                    "type": "none",
                    "value": ""
                }
            },
            {
                "index": 1,
                "name": "",
                "version": 3,
                "enabled": true,
                "isValid": true,
                "conditions": [],
                "level": {
                    "operator": 9,
                    "operatorText": "✋ nichts senden"
                },
                "time": {
                    "type": "pdsTime",
                    "value": "sunsetEnd",
                    "operator": 1,
                    "operatorText": "↧ von",
                    "offsetType": "none",
                    "offset": "1",
                    "multiplier": 60000,
                    "days": "*",
                    "months": "*"
                },
                "description": "<div><i class=\"fa fa-clock-o\" aria-hidden=\"true\"></i> ↧ von <var>Sonnenuntergang Ende</var></div><div>✋ nichts senden</div>",
                "importance": 0,
                "slat": {
                    "type": "none",
                    "value": ""
                }
            }
        ],
        "sunControlMode": "16",
        "sunFloorLengthType": "none",
        "sunFloorLength": "250",
        "sunMinDelta": "5",
        "blindPosMin": "open (max)",
        "blindPosMinType": "levelFixed",
        "blindPosMax": "closed (min)",
        "blindPosMaxType": "levelFixed",
        "blindOpenPosOffset": "",
        "blindClosedPosOffset": "",
        "sunSlat": "",
        "sunSlatType": "none",
        "smoothTime": "30000",
        "sunTopic": "",
        "windowTopType": "num",
        "windowTop": "195",
        "windowBottomType": "num",
        "windowBottom": "15",
        "windowAzimuthStartType": "numAzimuth",
        "windowAzimuthStart": "167",
        "windowAzimuthEndType": "numAzimuth",
        "windowAzimuthEnd": "347",
        "oversteers": [],
        "oversteerTopic": "",
        "x": 650,
        "y": 2220,
        "wires": [
            [
                "b136c5b5e6bafbc3"
            ],
            [
                "d55a263455e50063"
            ]
        ]
    },
    {
        "id": "b136c5b5e6bafbc3",
        "type": "debug",
        "z": "eb3b6622877c1d1b",
        "name": "Out Esszimmer",
        "active": true,
        "tosidebar": true,
        "console": false,
        "tostatus": false,
        "complete": "payload",
        "targetType": "msg",
        "statusVal": "",
        "statusType": "auto",
        "x": 1000,
        "y": 2200,
        "wires": []
    },
    {
        "id": "d55a263455e50063",
        "type": "debug",
        "z": "eb3b6622877c1d1b",
        "name": "Out 2",
        "active": true,
        "tosidebar": true,
        "console": false,
        "tostatus": false,
        "complete": "payload",
        "targetType": "msg",
        "statusVal": "",
        "statusType": "auto",
        "x": 970,
        "y": 2240,
        "wires": []
    },
    {
        "id": "a8a878862d1b296f",
        "type": "position-config",
        "name": "HausNeo",
        "isValide": "true",
        "longitude": "0",
        "latitude": "0",
        "angleType": "deg",
        "timeZoneOffset": 99,
        "timeZoneDST": 0,
        "stateTimeFormat": "3",
        "stateDateFormat": "12",
        "contextStore": ""
    }
]`

**Comment by Hypnos3** [comment]
Hallo,

Das klappt, wenn 2 Dinge geändert werden.
erstens anstelle:
![image](https://user-images.githubusercontent.com/12692680/152036005-c391e3c1-507d-4c95-b18f-bcb6aa5b25a3.png)
muss es so sein:
![image](https://user-images.githubusercontent.com/12692680/152036113-a527c7dd-0e05-4951-8de8-0142a0ed84ef.png)

und dann hab ich einen Bug gefunden:
![image](https://user-images.githubusercontent.com/12692680/152036190-5ba7c273-cce0-485b-bad1-e370e9ab7602.png)
Das muss so sein (in dem Drop down davor auf number umstellen):
![image](https://user-images.githubusercontent.com/12692680/152036301-226bcfff-c566-4971-95d6-3050236ff278.png)
![image](https://user-images.githubusercontent.com/12692680/152036316-ba09ca9e-7c09-4551-a9da-4f6203ef71ed.png)


Gruß

**Comment by Hypnos3** [comment]
should be fixed with version 2.0.12
