### ISSUE TITLE
1st attempt

### ISSUE THREAD

**Issue by lobocobra** [rdmtc/node-red-contrib-sun-position#40]
Hallo zusammen

Mir gefällt das add-on, weil ich eigne rules einfügen kann. Ich habe das Beispiel hier...
https://github.com/rdmtc/node-red-contrib-sun-position/blob/master/blind_control.md
installiert und komme trotz lesen nicht weiter.
=> kann mir jemand helfen? blind-controller habe ich zum laufen gebracht, hat aber keine rules

**Fragen**
- open/max closed/min
Das ist sehr verwirrend für mich, dass Open=1 und Closed=0 ist. Ich hätte gedacht ich kann einfach die Werte ändern dort auf Open=0 und Closed=100, aber das geht nicht. Ich will ja bei Closed die Storen 100% zu und das sieht meine Store auch so :-)
- Ich habe die Azimut eingegeben und die gehen auch bei dem anderen blind-controller tipptopp. Wenn ich die Werte aber hier eingebe und dann die Simulation starte, gehen die Storen von ganz-auf auf ganz-zu.  obwohl ich eingegeben habe, dass die Sonne 5m reinkommen kann.  Während der Blind-controller die Storen schön %-weise fährt, kann ich hier nur digital AUF/ZU erreichen.

Hier meine Einstellungen.
- alles standard wie im Beispiel ausser....
- 170 - 281 Azimut (https://www.sunearthtools.com/dp/tools/pos_sun.php?lang=de)
- Fenster 2.1 hoch 0 von Boden 3m Sonne im WZ

**Comment by mivodu** [comment]
Das Thema Open/Closed kommt aus der Homematik-Welt. Der Rolladenaktor dort versteht 100% als 100% des Fensters ist 'sichtbar/frei'. Ich glaube nicht, dass Du min/max einfach vertauschen kannst. Vermutlich muss Du für Deine Steuerung den 'invers' Wert nehmen, der sollte dann für Deinen Store passen.

**Comment by lobocobra** [comment]
Vielen Dank. Ich habe auch Homematic in Betrieb, aber die Aktoren für die Storen mist Shelly2.5 ausgewechselt.
=> Da ich mit Node-Red arbeite, kann ich leicht die Zahlen vertauschen, jedoch schaffe ich es nicht, dass hier andere Werte als 100 / 0 rausgegeben werden. 

Gehen bei Dir die Storen auch nur 100% rauf oder runter? Oder habe ich ein Einstellungsproblem? Die Azimute von meinem Haus stimmen, sonst würde die andere NODE ja auch Fehler rausgeben.

**Comment by mivodu** [comment]
Kenne den Shelly nicht. Hast Du es mal mit Werten zwischen 0 und 1 versucht (anstatt 0 und 100)? Bei Homematic arbeite ich mit 0 und 1 (und 0.01 Schrittweite). Da kann ich alle Positionen anfahren. Habe es aber noch nicht mit "restrict sunlight" versucht, ob der auch zwischenschritte anfährt.

**Comment by lobocobra** [comment]
Gute Idee! Ich versuche es mal mit Werten 1 - 0 und berichte dann hier weiter. Vielleicht hilft es ja dann auch mal jemandem

**Comment by Hypnos3** [comment]
Welche Version nutzt du?
Die Version 0.4.3 ist zurückgezogen, weil da ein böser Bug mit der Sonnensteuerung drin ist.

Wenn du Open=100 einstellst und Closed=0, kannst du den `levelInverse` nutzen um dann damit entsprechend deine Shelly zu steuern.

Ich nehme es mal als Enhancement mit auf, das man Open=0 und Closed=100 einstellen kann.

**Comment by Hypnos3** [comment]
sollte mittlerweile implementiert sein.
