### ISSUE TITLE
Blind control, rule, Elevation of sun

### ISSUE THREAD

**Issue by DaddelLinux** [rdmtc/node-red-contrib-sun-position#413]
I'm trying to automate my shutter control with 'node-red-contrib-sun-position'. The following problem has arisen: before the roller shutters open completely, the slats should first open (20%). This only makes sense if the sun has already risen. So I defined a rule:
Elevation of sun > -1.0
(Elevation of sun' > -1.0 [ 20.174 > -1.0]
↥ until 15:00 [ 15:00:00 (2022-02-15T14:00:00.000Z)]
blind position: ↕ absolute 20).
However, this rule is not taken into account.
Debug Message: position is set to default position because no other rule matches
If I enter positive values ​​for the elevation, the rule is taken into account. Is it wanted like that. And if so, why is that?
The sun-position node returns negative elevation angles at night. Version 1.x delivered the desired result.

 - Node Version: 2.1.1
 - Node-Red Version: 2.1.6

**Comment by Hypnos3** [comment]
Is a screenshot or an export of the node possible?

**Comment by DaddelLinux** [comment]
Hi,
thank you for the feedback. Unfortunately all instances of the node have been deleted for some time and I only have an old backup left. Since the function is very important to me, I switched to 'node red contrib cron plus'. The concept seems to me to fit better with NR. So I won't switch back.
I can well imagine how much enthusiasm it takes to keep a project like this alive. The more specific nodes are really great. But for knots like 'clock-timer' or 'blind' a lot of know-how relevant only for these nodes is necessary to get a reasonable result (keyword: own syntax and semantics, no specific debug tools). Errors or side effects in the sources are therefore particularly difficult to find.
