### ISSUE TITLE
Eine kleine Anmerkung zum Thema: Changelog

### ISSUE THREAD

**Issue by ThomasLoeffel** [rdmtc/node-red-contrib-sun-position#43]
Hallo hypnos,

ich stelle fest das "ich" nicht schnell herausfinden kann was zwischen den Versionen so geändert wurde. Ggf. finde ich es nicht, oder Du kann über eine kleine Anpassung (siehe Beispiel) nachdenken :-). Ansonsten wie immer "super Job gemacht" :-).

Gruß Thomas

### Beispiel:
![grafik](https://user-images.githubusercontent.com/44590735/61068499-77ea9000-a40a-11e9-8cf6-a091d9e39c5a.png)

![grafik](https://user-images.githubusercontent.com/44590735/61068516-820c8e80-a40a-11e9-89c7-22c03bebdf66.png)

**Comment by Hypnos3** [comment]
OK, ich muss das vorhandene changelog mal besser in die Readme mit aufnehmen.

Zur Erklärung: 
Aktuell mach ich zu jedem Publish auf npm ein [release](https://github.com/rdmtc/node-red-contrib-sun-position/releases) auf und kopiere die zugehörigen Änderungen rein.

Das lässt sich im Github unter dem entsprechenden Menüpunkt aufrufen:
![image](https://user-images.githubusercontent.com/12692680/61080466-6bbffc00-a425-11e9-9547-406a0aac463f.png)


Die Quelle von dem dort geposteten Änderungen ist die Datei [CHANGELOG.md](https://github.com/rdmtc/node-red-contrib-sun-position/blob/HEAD/CHANGELOG.md) im repository. Diese enthält das komplette Changelog. Leider ist diese im Master branch nicht immer aktuell. Aktuell ist diese immer im [dev](https://github.com/rdmtc/node-red-contrib-sun-position/blob/dev/CHANGELOG.md) branch. Hier sind dann auch schon die Änderungen der Version, an der ich aktuell arbeite und welche noch nicht released ist enthalten.

Ein nettes feature ist, dass man im [RedMatic Slack](https://join.slack.com/t/homematicuser/shared_invite/enQtNDgyNDM2OTkyMDA2LWY1YjY0NTE0NmY0OWM3YWUzMzAzMTgxYmRjMTMyOWE3NjkxNDdlMDY5ZjlhYzM5Nzg2N2U2YjdmNzNlYWNhNTU) im _notification_ channel bei jeder neuen Version eine Benachrichtigung erhält:

![image](https://user-images.githubusercontent.com/12692680/61080051-79c14d00-a424-11e9-807e-fedb4108a2f9.png)

**Comment by Hypnos3** [comment]
readme mit 0.4.6 erweitert
