### ISSUE TITLE
Frage/Probleme zur Version 0.4.7 mit der blind node

### ISSUE THREAD

**Issue by ThomasLoeffel** [rdmtc/node-red-contrib-sun-position#46]
Hallo hypnos,

in der Version 0.4.7 ist mir folgendes aufgefallen. 
Ich nutze das Öffnen, oder das Schließen der Fenster als Trigger. Wenn nun ein HMIP-SRH Aktor "0" meldet dann interpretiert das die Node als "bitte Rollladen "0.0" steuern. Ist das so gewollt? Irgendwie war das bei der Version 0.4.6 anders.

Bitte um schnelle Rückmeldung. Denn meine Steuerung spielt verrückt :-(. Ggf. mache ich seit der Version 0.4.6 auch was falsch…..

Gruß Thomas

**Comment by ThomasLoeffel** [comment]
Hallo hypnos,

bitte alles vergessen.... jetzt ist alles wieder anders....
Ich teste noch ein bisschen und melde mich dann.

Gruß Thomas

**Comment by Hypnos3** [comment]
An der Blind node hat sich zwischen 0.4.6 und 0.4.7 nichts geändert.
Woran lag es denn?
