### ISSUE TITLE
Probleme (ggf Bedienerfehler) Blind node

### ISSUE THREAD

**Issue by ThomasLoeffel** [rdmtc/node-red-contrib-sun-position#48]
Hallo hypnos,

mir ist folgendes aufgefallen. Dieses passiert meistens bei einem Deploy, oder Restart.
Ich bereite meine Daten auf, damit die auf diverse Einflüsse reagieren kann. Einer davon ist der HMIP-SRH-Fenstersensor. Dieser liefert drei Zustände: 0,1,2 (0: Fenster zu, 1: Fenster gekippt, 2: Fenster offen). Nun liefert dieser halt den "payload = 1" in die node. Wollte eigentlich nur zum triggern benutzen. Aber der Rollladen fährt dann tatsächlich in Position "1", obwohl er in die Position "0", oder bei offenem Fenster "0.1" fahren sollte. 

Was mache ich beim Triggern falsch? Muss der Trigger ein besonderes Format haben? Oder darf er eben ein besonderes Format nicht haben?

Gruß Thomas

Grafik 1:
![grafik](https://user-images.githubusercontent.com/44590735/61189520-c6a85c00-a68e-11e9-89d3-c5583f8cbd16.png)

Grafik 2:
![grafik](https://user-images.githubusercontent.com/44590735/61189496-906adc80-a68e-11e9-8882-8237b5d2814e.png)

Grafik 3:
![grafik](https://user-images.githubusercontent.com/44590735/61189490-74ffd180-a68e-11e9-9e07-fbdddacf3f84.png)

**Comment by Hypnos3** [comment]
Die Trigger Nachricht darf im Topic keines der folgenden Wörter enthalten:
`resetOverwrite`
`prio`
`alarm`
`manual`
`levelOverwrite`
`expire`
`mode`
`ignoreSameValue`

Die Trigger Nachricht darf auch keine Eigenschaft enthalten die folgendes enthält:
`reset`
`prio`
`priority`
`blindPosition`
`position`
`level`
`blindLevel`
`expire`
`setMode`

**Comment by Hypnos3** [comment]
Mach mal eine Debug Node am Eingang und setze diese auf komplettes Nachrichtenobjekt.

**Comment by ThomasLoeffel** [comment]
Wie gewünscht. 

E = im Eingang der Node "BAD".

Zeittrigger:
![grafik](https://user-images.githubusercontent.com/44590735/61250308-aabcbd00-a757-11e9-945c-a977b92448c4.png)

Trigger SRH:
![grafik](https://user-images.githubusercontent.com/44590735/61250397-dcce1f00-a757-11e9-883c-089d9309f1f9.png)


![grafik](https://user-images.githubusercontent.com/44590735/61250247-84971d00-a757-11e9-88e4-a10cbdbc10ea.png)

**Comment by Hypnos3** [comment]
Das kann ich leider nicht nachvollziehen. Ich habe ebenfalls einen Fenstersensor als trigger (einen HM-Sec-RHS).

Sicher, das es zu einem override führt und nicht eine rule getriggert wird, welche das Fenster öffnet?

Wenn du den debug-knoten "Blind Status Bad" auf "volles Nachrichtenobjekt" stellst, steht da der Grund für das öffnen.
```json
{
	"reason": {
		"code": 4,
		"state": "...-RF.LEQ0081500:1.STATE = [rule 1]",
		"description": "Position durch bedingte Regel global.ccu-localhost.values['BidCos-RF.LEQ0000000:1.STATE'].value = [rule 1]",
	},
	"blind": {
		"levelTop": 1,
		"levelBottom": 0,
		"increment": 0.01,
		"levelDefault": 1,
		"levelMin": 0.33,
		"levelMax": 1,
		"overwrite": {
			"active": false,
			"expireDuration": 14400000,
			"priority": 0
		}
	},
	"rule": {
		"hasMinimum": false,
		"hasMaximum": false,
		"id": 1,
		"active": true,
		"level": 1,
		"conditional": true,
		"timeLimited": false,
		"conditon": { }
	},
	"level": 1,
}
```
interessant ist dabei: "overwrite": { "active": false,

Ich hab mal mit aufgenommen, das in der nächsten Version ein topic mit `triggerOnly` einen override verhindert.

**Comment by ThomasLoeffel** [comment]
Hallo hypnos,

habe einmal eine "function node" vorgeschaltet.  Nun geht es.
Also wertet die "blind node" etwas meines HMIP-SRH aus (siehe Trigger SRH).

Gruß Thomas

![grafik](https://user-images.githubusercontent.com/44590735/61411927-cc4cae80-a8e7-11e9-95a9-8853ce6e85f8.png)


![grafik](https://user-images.githubusercontent.com/44590735/61411612-09647100-a8e7-11e9-8425-b5e5915d16ee.png)
