### ISSUE TITLE
Fehler in der Version 0.4.7 erkannt. Dokufehler und "bis" Aktionen

### ISSUE THREAD

**Issue by ThomasLoeffel** [rdmtc/node-red-contrib-sun-position#49]
Hallo hypnos,

ich habe die Version 0.4.7 installiert. Mir sind nun folgende Fehler aufgefallen.
1) In der Doku von Dir wird "day.today....." angezogen aber "dayinfo.today" gespeichert. Das Gleiche bei „day.tomorrow“.
2) Sowohl in Deinem Beispiel, als auch bei mir läuft er nie in die Regel 9, er springt immer in die Regel 7 (bürgerliche Abenddämmerung). Was kann ich machen?

Gruß Thomas

![grafik](https://user-images.githubusercontent.com/44590735/61583933-89851380-ab3f-11e9-8143-b80998384022.png)

![grafik](https://user-images.githubusercontent.com/44590735/61583985-542cf580-ab40-11e9-92dd-031ea79d295a.png)

![grafik](https://user-images.githubusercontent.com/44590735/61583997-935b4680-ab40-11e9-85e9-775078a2891e.png)

**Comment by ThomasLoeffel** [comment]
Hallo hypnos,

danke für die super Doku. Nun ist alles klarer! Kein Fehler, Userfehler :-).

Gruß Thomas

**Comment by Hypnos3** [comment]
Wenn das noch jemand anders liest, um die Frage wegen der 9. Regel zu beantworten:
Wenn die Zeit für die Bürgerlichen Dämmerung vor der Zeit bei Regel 9 ist (wie in deinem Bild der Fall), dann tritt Regel 9 natürlich nie in Kraft. Das ist stark davon abhängig wo du wohnst.

Die Idee dahinter ist folgende:
Im Winter wenn es zeitig dunkel wird, die Rollläden schließen, wenn es draußen dunkel ist und im Sommer, wenn es draußen sehr lange hell ist, einen spätesten Zeitpunkt zu haben, wann geschlossen wird.

**Comment by ThomasLoeffel** [comment]
Danke Dir. Die Logik hat sich mir erst jetzt erschlossen :-)
Super node, sehr mächtig!
