### ISSUE TITLE
Raffstore/Jalousie

### ISSUE THREAD

**Issue by overdrive69** [rdmtc/node-red-contrib-sun-position#50]
Hi,
could this node also work to controll raffstores?
Because with Raffstores there is the possiblity to close it eg. to 50% and than change the angle of the ləmelə.

**Comment by Hypnos3** [comment]
Unfortunately I do not have Raffstore/Jalousie, so I can not test it and develop it.

The blind height should be adjustable with the node easily. Via additional logic after the node you can then change the angle and other additional settings.

The node additionally provides a lot of information about the reason for a blind position at an output. This information can be used for additional control.

**Comment by Hypnos3** [comment]
no plan for implementation,

Pull Requests are welcome.
