### ISSUE TITLE
Messages sent without blind level changing when in override

### ISSUE THREAD

**Issue by eggman0131** [rdmtc/node-red-contrib-sun-position#53]
Hi, loving this node, although it's a bit complicated to work out :-)

One problem though, I have it set to a single output.  I inject a message every 5 minutes to recalculate.  When the blind position doesn't change there is no outbound message.  This is good.

Except if I have an override set, then every 5 minutes I get an outbound message, even though the position has not changed.  Is this by design?  It seem at odds with the documentation:

> If the output is set to single, an object property msg.blindCtrl will be attached to the message and forwarded to the first output. If the node is configured with two outputs this object is set as the msg.payload property of the message that is send to the second output. The difference is also, that the second output will give this object every time a recalculation will is triggered, where the first output only send a message on blind position change.

I expect I can suppress that message with a small effort but it would be good if it wasn't sent.

**Comment by Hypnos3** [comment]
Thank you for your Bug report!
