### ISSUE TITLE
Gezieltes Rücksetzen mit "resetOverwrite" ist mir nicht möglich

### ISSUE THREAD

**Issue by ThomasLoeffel** [rdmtc/node-red-contrib-sun-position#54]
Hallo Hypnos,

danke für die super Node!

Bei folgendem Fall ist mir aufgefallen das ich ein Problem habe.

### Fall:
Wenn ich das Haus verlasse sezte ich {"position":0.0,"prio":4} und wenn ich wieder komme dann "resetOverwrite" soweit alles ok. Nun habe ich eine Terrasentür mit Rollladen dran. Somit wollte ich dort nur dann wenn die Tür offen ist {"position":1.0,"prio":3} und wenn die Tür wieder zu ist "resetOverwrite" setzen. Allerdings ist mir heute aufgefallen das wenn ich gehe und mit und der
 {"position":0.0,"prio":4} alle Rollladen in eine Prio setze kann leider der Befehl "resetOverwrite" von der Terrassentür = geschlossen diesen Rollladen wieder zurücksetzen und dann öffnen (wie in den Rules hinterlegt.

### Frage:
Wie setze ich eine bestimmte Prio wieder zurück?

Lieben Gruß Thomas

![grafik](https://user-images.githubusercontent.com/44590735/65542657-dd312600-df0f-11e9-8892-9b2157d0d368.png)

**Comment by Hypnos3** [comment]
resetOverwrite funktioniert nur, wenn die prop <= der Priorität des Override ist oder wenn keine prio mitgegeben wird ohne eine EInschränkung.

Will man also bestimmte prios zurücksetzen, muss man also immer mit resetOverwrite eine prio mitgeben und das entsprechend staffeln.

Du kannst das resetOverwrite  auch bedingt mit Logik im Flow vorher senden.

**Comment by ThomasLoeffel** [comment]
Hallo Hypnos,

danke für die schnelle Antwort. Habe verstanden was Du gesagt hast, leider komme ich in der Umsetzung an meine Grenzen. In Deinem guten Beispiel habe ich den unten angefügten Fall verwendet. Wie soltle ich nun genau eine Prio3 (und auch nur diese) zurück setzen? Also wie sehen denn die Nutzdaten aus, wenn nicht "true", wie im Beispiel?

Vielen Dank für Deine Hilfe.

Gruß Thomas


![grafik](https://user-images.githubusercontent.com/44590735/65640228-25247b80-dfea-11e9-8f6a-edf8ce798700.png)

![grafik](https://user-images.githubusercontent.com/44590735/65640256-340b2e00-dfea-11e9-9780-354e141ffdee.png)

**Comment by Hypnos3** [comment]
Aktuell kannst du nicht "nur" eine prio zurücksetzen.
Bei einem "resetOverwrite" mit einer prio wird immer alles mit selber oder niedriger prio (Zahl kleiner) zurückgesetzt.

Ich werde in einer nächsten Version noch was einbauen, das man eine bestimmte Prio zurücksetzen kann.

**Comment by ThomasLoeffel** [comment]
Hallo Hypnos,

danke für die schnelle Antwort. Ich wollte nur die Syntax wissen.

So geht es nun wie von Dir beschrieben:
![grafik](https://user-images.githubusercontent.com/44590735/65732228-29739600-e0c9-11e9-8592-7123ab4f055c.png)

Meintest Du es auch so?

Gruß Thomas

**Comment by Hypnos3** [comment]
sorry für die späte Antwort.


also folgendes müsste gehen:
so wie bei dir im Topic "resetOverwrite" und im Payload "prio":
![image](https://user-images.githubusercontent.com/12692680/65908802-7dcb8e00-e3c7-11e9-851f-24429b2cc7b2.png)
oder "priority":
![image](https://user-images.githubusercontent.com/12692680/65908900-abb0d280-e3c7-11e9-8035-fa8846804c72.png)

oder im topic  "resetOverwrite" und "priority" und als payload die prio als Zahl:
![image](https://user-images.githubusercontent.com/12692680/65908964-c97e3780-e3c7-11e9-819a-73eeef02b494.png)

**Comment by Hypnos3** [comment]
oder im payload reset mit true und prio
![image](https://user-images.githubusercontent.com/12692680/65909033-f3375e80-e3c7-11e9-946c-0d7ad84b70ce.png)
