### ISSUE TITLE
Sun events incorrect time

### ISSUE THREAD

**Issue by mrdarrengriffin** [rdmtc/node-red-contrib-sun-position#55]
**Describe the bug**
When using the sunrise / sunset, the times in the gate are wrong.

**Expected behavior**
They should be closer to the times provided by google.

**Screenshots**
![node](https://user-images.githubusercontent.com/6920899/65545381-2764d800-df0d-11e9-98f8-ba4aad4e6647.PNG)
![google sunrise](https://user-images.githubusercontent.com/6920899/65545378-26cc4180-df0d-11e9-95ac-c7dd8a266f25.PNG)
![google sunset](https://user-images.githubusercontent.com/6920899/65545379-2764d800-df0d-11e9-9100-bef06ff4549d.PNG)

**System information (please complete the following information):**
 - Version 0.4.8
 - Node-Red v0.20.8
 - Raspberry Pi 3

**Comment by Hypnos3** [comment]
In my systems are the times are similar:
![image](https://user-images.githubusercontent.com/12692680/65546706-57fe3f00-df18-11e9-9b84-33271dffd87e.png)

![image](https://user-images.githubusercontent.com/12692680/65546760-6e0bff80-df18-11e9-87b9-599a0c1333c4.png)

https://www.timeanddate.com/sun/ gives similar times:
![image](https://user-images.githubusercontent.com/12692680/65547091-1752f580-df19-11e9-9401-8ddf8f69459a.png)

I have already investigated the difference of the times. The calculation is an approximation and there are different types of calculation.

In your case it seems more a difference in the used time zone. The nodes uses the timezone of the system where you have installed it.

Which timezone you have setup in your system?

**Comment by mrdarrengriffin** [comment]
It's is disabled, using the OS Timezone which is UTC+1 which is correct

**Comment by Hypnos3** [comment]
It is difficult for ma to find any problem. No other user has reported a problem before.

There is a tooltip to the time available which additional shows the time as UTC:
![image](https://user-images.githubusercontent.com/12692680/65551830-11621200-df23-11e9-801a-f127b8d4eb49.png)

The times depending on the setting of the node:
![image](https://user-images.githubusercontent.com/12692680/65552031-9b11df80-df23-11e9-8f73-5584103c8525.png)
There is currently only the operating system time zone supported.

If you using node-red in docker, then [this](https://github.com/rdmtc/node-red-contrib-sun-position/issues/8#issuecomment-472009717) is may also interesting.

**Comment by mrdarrengriffin** [comment]
Yeah, tooltip giving me the same result. It's very weird indeed.

![sunrise tooltip](https://user-images.githubusercontent.com/6920899/65625839-80437780-dfc4-11e9-9f99-2c431f500bf6.png)

Also, I am not using docker, but I appreciate the info

**Comment by Ordsu72** [comment]
My flow had a same strange behaviour before I noticed that I entered the latitude and longitude in a wrong order. After swapping the two value my sunset and sunrise times show the correct value.
BTW: in the position-config node the two properties are also displayed in strange order. Everywhere I have seen these two values are in the latitude, longitude order.

**Comment by Hypnos3** [comment]
It is no problem to switch latitude, longitude order in the config node.

It will be switched in the nexed release:
![image](https://user-images.githubusercontent.com/12692680/67801301-2e8d8180-fa89-11e9-81e0-7717630a938d.png)

**Comment by vlturner** [comment]
I want to pass openweather LAT and LON into node-red-contrib-sun-position. How can I do this?

payload: object
lon: -120.68
lat: 38.2
city: "San Andreas"
country: "US"
_msgid: "8d406753.79f9c8"

**Comment by Hypnos3** [comment]
This is currently not possible. the Latitude and Longitude must be added in the config.

I can check if it can be added to the `sun position`  and to the moon position to also have thin in the incomming message.

**Comment by taoyx** [comment]
I have experienced the same issue: the sunset events is triggered early morning after it running properly for many days:
Note: the screen cut is made at early morning 6:08AM

![Sunset node configuration1](https://user-images.githubusercontent.com/23740365/111734001-77f69080-8879-11eb-9850-b6ba3dbefa8f.png)
![Sunset node configuration2](https://user-images.githubusercontent.com/23740365/111734006-7b8a1780-8879-11eb-9b43-0e3083d6166c.png)
![sunset wrong time](https://user-images.githubusercontent.com/23740365/111734012-7f1d9e80-8879-11eb-8f02-acba6827e5cd.png)

**Comment by Hypnos3** [comment]
you refering to an other node,
