### ISSUE TITLE
Internal Error

### ISSUE THREAD

**Issue by Feldman01** [rdmtc/node-red-contrib-sun-position#57]
After Update Version 0.4.9 i have an internal error:
internal error time-inject:Cannot read property 'length' of undefined"
there is a solution to this error?

Ich habe heute auf die Verion 0.4.9 aktualisiert und die Node Time-Inject spuckt nun einen internen Fehler aus, siehe oben. Ein Neustart hat nicht geholfen, auch eine neue Konfiguration der Node nicht. Die anderen Node wie Sun-Position bringen ebenfalls den gleichen Fehler.

Hoffe ihr könnt mir helfen!

**Comment by ThomasPoett** [comment]
Dito, habe das gleiche Problem...

Error:
_9/26/2019, 7:27:30 AMnode: 5:45-8:00
msg : string[76]
"internal error within-time-switch:Cannot read property 'length' of undefined"_

**Comment by Hypnos3** [comment]
Which Version of Node-Red do you use?
Welche Version von Node-red Nutzt ihr?

**Comment by ThomasPoett** [comment]
Hi 
I'm running Node Red on RaspMatic: Ver: 4.7.1 / 0.20.5
and tnx for your fast response :)

hier mal die Liste aller Module:
{
   "ccu": {
      "VERSION": "3.47.10.20190713",
      "PRODUCT": "raspmatic_rpi3",
      "PLATFORM": "rpi3"
   },
   "redmatic": "4.7.1",
   "nodejs": "10.15.3",
   "ain2": "3.0.0",
   "node-red": "0.20.5",
   "node-red-contrib-mysensors": "3.3.0",
   "node-red-node-serialport": "0.8.3",
   "npm": "6.9.0",
   "redmatic-homekit": "2.3.3",
   "node-red-contrib-alexa-home-skill": "0.1.17",
   "node-red-contrib-alexa-remote2": "3.2.5",
   "node-red-contrib-bigtimer": "2.2.5",
   "node-red-contrib-ccu": "2.1.5",
   "node-red-contrib-combine": "1.8.1",
   "node-red-contrib-dwd": "0.9.0",
   "node-red-contrib-german-holidays": "0.1.12",
   "node-red-contrib-huemagic": "2.0.2",
   "node-red-contrib-later": "0.0.5",
   "node-red-contrib-moment": "3.0.3",
   "node-red-contrib-samsung-tv-mk": "0.1.2",
   "node-red-contrib-simpletime": "2.7.0",
   "node-red-contrib-sun-position": "0.4.9",
   "node-red-dashboard": "2.16.3",
   "node-red-node-email": "1.7.0",
   "node-red-node-openweathermap": "0.2.1",
   "node-red-node-rbe": "0.2.5",
   "node-red-node-sentiment": "0.1.4",
   "node-red-node-tail": "0.0.3",
   "redmatic-led": "1.1.0",
   "redmatic-webapp": "0.3.1"

**Comment by Feldman01** [comment]
Ich nutze die gleiche Version wie Thomas hier gepostet hat.

**Comment by Hypnos3** [comment]
I have found a problem with the code I have [prepared](https://nodered.org/blog/2019/09/20/node-done) for Node-Red 1.0. The recommend way for be backward compatible doesn't work. This was also confirmed by @knolleary. See [discussion](https://discourse.nodered.org/t/knowing-when-a-node-is-done-new-node-api/15737/9) in the Node-Red forum.

My Problem is that I does not get the same error `Cannot read property 'length' of undefined` as you get.

**Comment by Hypnos3** [comment]
Ich habe jetzt auch Node-Red 0.20.5 auf meinem Testsystem installiert. Leider bekomme ich noch immer nicht die selbe Fehlermeldung.

**Comment by Hypnos3** [comment]
Ich habe jetzt Version 0.4.10 released und hoffe das behebt auch dieses Problem.

Bitte um Rückmeldung!

**Comment by Feldman01** [comment]
Hallo Hypnos3,
sehe das Update noch nicht in NodeRed über die Pallette, worüber ich es installieren müsste.
Hast du es dafür schon freigegeben?

**Comment by Hypnos3** [comment]
Die Version 0.4.10 ist jetzt auch bei Node-red angekommen https://flows.nodered.org/node/node-red-contrib-sun-position.

Ich weiß aber nicht in welchen Abständen sich die Pallette im Node-Red aktualisiert. Eventuell hilft ein Node-Red Neustart.

**Comment by ThomasPoett** [comment]
ist jetzt in der Palette verfügbar :) Danke dir. Ich test fix

**Comment by Feldman01** [comment]
So, Update ist sichtbar und installiert und.... yes it works!!!

Danke für deine schnelle Hilfe, jetzt habe ich heute Abend wieder Licht 😂

**Comment by ThomasPoett** [comment]
ok confired. "undevined " solved ! Tnx mate

**Comment by Hypnos3** [comment]
Danke für das Testen und das schnelle Melden des Fehlers!
