### ISSUE TITLE
internal error within-time-switch:this.metric is not a function

### ISSUE THREAD

**Issue by dehsgr** [rdmtc/node-red-contrib-sun-position#58]
After latest Update (v0.4.9) I get the error above.

nodered log says:
`Sep 26 08:08:57 homematic daemon.info node-red[1110]: [within-time-switch:Sunset to Sunrise] this.metric is not a function
Sep 26 08:08:57 homematic daemon.info node-red[1110]: [within-time-switch:Sunset to Sunrise] TypeError: this.metric is not a function
Sep 26 08:08:57 homematic daemon.info node-red[1110]: [within-time-switch:Sunset to Sunrise]     at Node.send (/usr/local/addons/redmatic/lib/node_modules/node-red/node_modules/@node-red/runtime/lib/nodes/Node.js:216:10)
Sep 26 08:08:57 homematic daemon.info node-red[1110]: [within-time-switch:Sunset to Sunrise]     at withinTimeSwitchNode.<anonymous> (/usr/local/addons/redmatic/var/node_modules/node-red-contrib-sun-position/nodes/within-time-switch.js:313:17)
Sep 26 08:08:57 homematic daemon.info node-red[1110]: [within-time-switch:Sunset to Sunrise]     at withinTimeSwitchNode.emit (events.js:189:13)
Sep 26 08:08:57 homematic daemon.info node-red[1110]: [within-time-switch:Sunset to Sunrise]     at withinTimeSwitchNode.Node.receive (/usr/local/addons/redmatic/lib/node_modules/node-red/node_modules/@node-red/runtime/lib/nodes/Node.js:237:14)
Sep 26 08:08:57 homematic daemon.info node-red[1110]: [within-time-switch:Sunset to Sunrise]     at SwitchNode.Node.send (/usr/local/addons/redmatic/lib/node_modules/node-red/node_modules/@node-red/runtime/lib/nodes/Node.js:224:14)
Sep 26 08:08:57 homematic daemon.info node-red[1110]: [within-time-switch:Sunset to Sunrise]     at applyRules (/usr/local/addons/redmatic/lib/node_modules/node-red/node_modules/@node-red/nodes/core/logic/10-switch.js:441:42)
Sep 26 08:08:57 homematic daemon.info node-red[1110]: [within-time-switch:Sunset to Sunrise]     at applyRule (/usr/local/addons/redmatic/lib/node_modules/node-red/node_modules/@node-red/nodes/core/logic/10-switch.js:224:17)
Sep 26 08:08:57 homematic daemon.info node-red[1110]: [within-time-switch:Sunset to Sunrise]     at getV2 (/usr/local/addons/redmatic/lib/node_modules/node-red/node_modules/@node-red/nodes/core/logic/10-switch.js:199:17)
Sep 26 08:08:57 homematic daemon.info node-red[1110]: [within-time-switch:Sunset to Sunrise]     at getV2 (/usr/local/addons/redmatic/lib/node_modules/node-red/node_modules/@node-red/nodes/core/logic/10-switch.js:168:13)
Sep 26 08:08:57 homematic daemon.info node-red[1110]: [within-time-switch:Sunset to Sunrise]     at getV1 (/usr/local/addons/redmatic/lib/node_modules/node-red/node_modules/@node-red/nodes/core/logic/10-switch.js:181:13)
Sep 26 08:08:57 homematic daemon.err node-red[1110]: [within-time-switch:Sunset to Sunrise] internal error within-time-switch:this.metric is not a function
`

**Comment by Hypnos3** [comment]
I have released Version 0.4.10 - 1 minute ago, which will fix that problem.

The recommend way for be backward compatible doesn't work. This is [also](https://discourse.nodered.org/t/knowing-when-a-node-is-done-new-node-api/15737/9) confirmed by Node-Red Team.

See also #57
