### ISSUE TITLE
Solar Noon & Sunrise angles are swapped

### ISSUE THREAD

**Issue by Nicehavetoo** [rdmtc/node-red-contrib-sun-position#61]
The angles of Solar noon and Sunrise are swapped.
I discovered this when I tried to make sense out of the angle at sunrise.
I couldn't get my head arround it till I looked at solar noon hahaha.

When you trigger the sun_position node in node red and feed the data into a debug message, open related data tree, you can see what I mean.
![image](https://user-images.githubusercontent.com/55870163/65747508-e7b31180-e101-11e9-9721-c2d7e0395843.png)

![image](https://user-images.githubusercontent.com/55870163/65747681-51332000-e102-11e9-9ff8-ec6638ffaa36.png)

I do think it is an enormously great node that supplies a lot of information.
Thank you for putting the time and effort in into making it..

**Comment by Hypnos3** [comment]
This angle is wrong for sunset. It should be the elevation angle. For solarNoon this is also wrong.
I will change this in the next Version.

**Comment by Hypnos3** [comment]
Thank you for this bug report!
