### ISSUE TITLE
Deactivate sun control

### ISSUE THREAD

**Issue by pr-boh** [rdmtc/node-red-contrib-sun-position#62]
Hello, I use this very pretty exampe 3 - testing rules and overrides - and want to disable sun control.
I made an injection with following payload: {"setMode":0}.
But nothing happens. Sun control is still active. 
Do I misunderstand your description:
"an incoming message with msg.mode, msg.payload.mode or where the msg.topic contains setMode and the value of msg.payload is a valid number, will allow to set the mode of the sun control.
    a value of 0 will deactivate sun control, 1 will set to maximize sunlight (Winter) and 2 will set to restrict sunlight (Summer)."

**Comment by Hypnos3** [comment]
There is a bug, that the sun control can not be deactivated. I will fix this with the next version.
