### ISSUE TITLE
Positions like 50% are not taking scale (0-100) into account

### ISSUE THREAD

**Issue by kwesolowski** [rdmtc/node-red-contrib-sun-position#66]
When some rules sets blinds to 50%, payload outputed is 0.5, despite config of blind being 0, 100 with increment 1.

**Comment by Hypnos3** [comment]
there is a bug in https://github.com/rdmtc/node-red-contrib-sun-position/blob/cbc9badd3fcc2c394e7a8b9b5ff32e137cda7f48/nodes/blind-control.js#L268

That will always return a number between 0 and 1 independent of the open/close settings.

Must be something like `return posPrcToAbs_(node, val / 100);`.

I will fix this in the next release.

**Comment by Hypnos3** [comment]
This should be fixed in 0.5.1. Unfortunately, I have little time to test and would therefore ask for feedback if it works.

**Comment by kwesolowski** [comment]
No problem. I will test over next weekend.

Maybe it would be better for me to specify 0-1 and scale outside block? Or
this should be the only issue there?

**Comment by Hypnos3** [comment]
In the end it should be working with 0-100.

**Comment by Hypnos3** [comment]
fixed with Version 1.0.0
