### ISSUE TITLE
Offset for within_time error read from flow.variable

### ISSUE THREAD

**Issue by DaveMe81** [rdmtc/node-red-contrib-sun-position#69]
Hello!

I'm usign the within_time node to switch definately a bulb off after sunrise plus an offset.

I got error, when I put in a flow.variable to the offset field.

I think the flow.variable is set correctly. I want to make it more dynamical. So I have an input field on the dashboard to change it.

The error I get is: msg : string[66]
"Fehler: Kann den Wert von flow.flur_offset_minutes nicht ermitteln"
(means: Could not evaluate value from flow.flur_offset_minute).

`[{"id":"1271c090.177f2f","type":"inject","z":"d0091500.27f078","name":"Flur ausschalten","topic":"","payload":"false","payloadType":"bool","repeat":"30","crontab":"","once":true,"onceDelay":0.1,"x":170,"y":2020,"wires":[["164667fd.ad7ba8"]]},{"id":"3b64577c.0532c8","type":"switch","z":"d0091500.27f078","name":"enabled?","property":"enable","propertyType":"flow","rules":[{"t":"true"}],"checkall":"true","repair":false,"outputs":1,"x":880,"y":2020,"wires":[["63fecb98.faa974"]]},{"id":"44d58956.21af28","type":"debug","z":"d0091500.27f078","name":"offset","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"payload","targetType":"msg","x":1230,"y":1800,"wires":[]},{"id":"290ef784.42af38","type":"change","z":"d0091500.27f078","name":"flur_offset_minutes","rules":[{"t":"set","p":"payload","pt":"msg","to":"flur_offset_minutes","tot":"flow"}],"action":"","property":"","from":"","to":"","reg":false,"x":1010,"y":1800,"wires":[["44d58956.21af28"]]},{"id":"d5006f70.a0894","type":"inject","z":"d0091500.27f078","name":"","topic":"","payload":"","payloadType":"date","repeat":"","crontab":"","once":false,"onceDelay":0.1,"x":760,"y":1760,"wires":[["290ef784.42af38"]]},{"id":"fc31bfc1.96667","type":"change","z":"d0091500.27f078","name":"Flur offset to flow","rules":[{"t":"set","p":"flur_offset_minutes","pt":"flow","to":"payload","tot":"msg"}],"action":"","property":"","from":"","to":"","reg":false,"x":630,"y":1840,"wires":[["26f87857.ad7a98"]]},{"id":"26f87857.ad7a98","type":"ui_slider","z":"d0091500.27f078","name":"","label":"Minuten nach Sonnenaufgang","tooltip":"","group":"45168c17.a3c424","order":0,"width":0,"height":0,"passthru":true,"outs":"end","topic":"Flur_ausschalten_offset","min":"-60","max":"60","step":1,"x":310,"y":1840,"wires":[["fc31bfc1.96667"]]},{"id":"1b291b84.a63974","type":"inject","z":"d0091500.27f078","name":"Default flur offset +35min","topic":"Flur_ausschalten_offset","payload":"35","payloadType":"num","repeat":"","crontab":"","once":true,"onceDelay":0.1,"x":170,"y":1780,"wires":[["26f87857.ad7a98","fc31bfc1.96667"]]},{"id":"164667fd.ad7ba8","type":"within-time-switch","z":"d0091500.27f078","name":"nach Sonnenaufgang +Flur_ausschalten_offset","positionConfig":"61cca1bf.c6359","startTime":"sunrise","startTimeType":"pdsTime","startOffset":"flur_offset_minutes","startOffsetType":"flow","startOffsetMultiplier":60000,"endTime":"sunset","endTimeType":"pdsTime","endOffset":0,"endOffsetType":"none","endOffsetMultiplier":60000,"propertyStart":"","propertyStartType":"none","propertyStartCompare":"true","propertyStartThreshold":"","propertyStartThresholdType":"num","startTimeAlt":"","startTimeAltType":"entered","startOffsetAlt":0,"startOffsetAltType":"none","startOffsetAltMultiplier":60000,"propertyEnd":"","propertyEndType":"none","propertyEndCompare":"true","propertyEndThreshold":"","propertyEndThresholdType":"num","endTimeAlt":"","endTimeAltType":"entered","endOffsetAlt":0,"endOffsetAltType":"none","endOffsetAltMultiplier":60000,"tsCompare":"0","lastMsgOnStartOut":false,"lastMsgOnEndOut":false,"x":560,"y":2020,"wires":[["3b64577c.0532c8"],[]]},{"id":"45168c17.a3c424","type":"ui_group","z":"","name":"Flur ausschalten","tab":"3e4ec211.f6f41e","order":3,"disp":true,"width":"8","collapse":false},{"id":"61cca1bf.c6359","type":"position-config","z":"","name":"zuHause-OAS","isValide":"true","longitude":"0","latitude":"0","angleType":"deg","timeZoneOffset":99,"timeZoneDST":0,"stateTimeFormat":"3","stateDateFormat":"12"},{"id":"3e4ec211.f6f41e","type":"ui_tab","z":"","name":"Sonnen Zeiten","icon":"wi-wu-sunny","order":4,"disabled":false,"hidden":false}]`

**Comment by Hypnos3** [comment]
I tested it and was able to adjust the error. Basically everything works, in "normal operation". The error occurs only when editing the node, because then the time is determined to have this as a tooltip.

I found an error there, so data from the current flow can not be determined. This will be fixed with the next version.

**Comment by Hypnos3** [comment]
Should be fixed with Version 0.5.2!
