### ISSUE TITLE
[Feature Request] blind-control noop mode

### ISSUE THREAD

**Issue by apoc4lyps** [rdmtc/node-red-contrib-sun-position#77]
a option (within blind-control rules) to disable the automation would be nice. this would be usefull to allow specific positions (like open shutter in case of fire alarm) but disable the remaining automation rules.

**Comment by Hypnos3** [comment]
If I understand your feature request right, I think this can be already achieved.

Therefore add a rule as the first rule with no time constraint and only the condition.
In this example it is a sensor that indicates if the door is open. Then the blind should not be closed (In the same way this can be used for fire alarm):
![image](https://user-images.githubusercontent.com/12692680/70188093-1a741a00-16f0-11ea-96bf-9dd1f469ff0a.png)
![image](https://user-images.githubusercontent.com/12692680/70188199-5d35f200-16f0-11ea-9cf8-f99693d60f2a.png)

If the condition is full filled no other of the remaining automation rules are checked.

You can add multiple of such rules at the beginning. Then the first rule gets the highest priority.
So the first rule can be a fire alarm, the second a window contact, etc...

---
In general for that the use case the  overrides with different priorities are exists. With different priorities I decide at my home an override by an manual handling between an override of an fire alarm.
![image](https://user-images.githubusercontent.com/12692680/70187938-b6e9ec80-16ef-11ea-835f-eeb677c4075a.png)
The link feeds into all blind-controller nodes:
![image](https://user-images.githubusercontent.com/12692680/70188035-f3b5e380-16ef-11ea-9568-fbf8a254121f.png)

![image](https://user-images.githubusercontent.com/12692680/70188006-dc76f600-16ef-11ea-990f-bb58358d55f7.png)

---

I ask for feedback if this is already sufficient or something else is desired.

**Comment by apoc4lyps** [comment]
Hi @Hypnos3, first of all thanks for your detailed answer and the work on this project.

I try to archive things like:
- don't move the shutters if window is open (don't lockout yourself at the terrace)
- manual mode (wife wants a specific position)
- allow emergency states / overrides during manual mode

After reviewing your config and the docs a second time I think this can be archived with expire / priority. I'll try to meet my requirements with it.

Regards

**Comment by Hypnos3** [comment]
OK, I close this issue. You can reopen it if still a need for any enhancement.
