### ISSUE TITLE
payload input: date-option documentation missing?

### ISSUE THREAD

**Issue by ozett** [rdmtc/node-red-contrib-sun-position#78]
i cannot find any example or docu for the date-option in the payload field.
any hint very appreciated. or is the docu missing?
how do i use this option? what is the syntax for input?

![image](https://user-images.githubusercontent.com/5937811/71035701-53fb4b00-211c-11ea-8cbc-280ee97c3ead.png)

**Comment by Hypnos3** [comment]
I will add Documentation with the next release.

**Comment by Hypnos3** [comment]
implemented in 1.0.12
