### ISSUE TITLE
within-time -> how to have timespan on certain days?

### ISSUE THREAD

**Issue by ozett** [rdmtc/node-red-contrib-sun-position#80]
i would like to have time-events from within-time not every day, but only on SA or MO.
Is this possible? Do i have to calculate it somehow with jsonata or on the time-drop down?
How do it  have witin time from 12:00-13:00 only on Sunday?

![image](https://user-images.githubusercontent.com/5937811/71243440-a604c200-2310-11ea-9cd7-c5893852ae44.png)

Pete Scargills BigTime has some nice checkboxes for Days and Months. 
within-time on  only on certain weekdays would be great1 👍 

![image](https://user-images.githubusercontent.com/5937811/71243477-bb79ec00-2310-11ea-929e-dfce5d5eb3af.png)

**Comment by ozett** [comment]
maybe time-compare could do it, but looks like overkill to filter on a SA
and no docu? How would i set this filter for certain days of a week?

![image](https://user-images.githubusercontent.com/5937811/71243887-989c0780-2311-11ea-82b5-a78361275626.png)

**Comment by ozett** [comment]
i could maybe be solved with time-inject and gate-node as a filter on this,
but to use only a single  "within-time "-node itself as a gate would be more readable....
maybe you can show how to use within-time only on certain days...

![image](https://user-images.githubusercontent.com/5937811/71244252-650dad00-2312-11ea-8f0b-ac2308d2592d.png)

**Comment by Hypnos3** [comment]
I will add the day selection to the within-time node. But this will take some time.

**Comment by ozett** [comment]
Great! 🎉 🍪 
should i come here to look for update? How do i check progress? Version updates?

**Comment by ozett** [comment]
seems complicated to trigger the blind-node on certains wwekdays.
at the moment looks like i have to send time-inject with Weekdays on the "msg.ts" but i have only two filter conditions (means 2 days). Or i must filter for simple weekdays condition even more complicated with  reg-ex? Or how is is designed to be done?

![image](https://user-images.githubusercontent.com/5937811/71351067-1b6fcd00-2573-11ea-8153-36f45fac8ada.png)

**Comment by Hypnos3** [comment]
The selection of days is already planned for the next version.

**Comment by Hypnos3** [comment]
info for me: consider #84 also for within-time node

**Comment by Hypnos3** [comment]
implemented in node-red-contrib-sun-position@1.0.0-alpha-7

**Comment by Hypnos3** [comment]
![image](https://user-images.githubusercontent.com/12692680/71605632-bae02180-2b6a-11ea-8a34-6341d1be8e66.png)

**Comment by ozett** [comment]
i updated, wonderfull!
thx for implementing it.

i personally like the full daynames,
shortened days to make it more compact...

![image](https://user-images.githubusercontent.com/5937811/71884643-ffeeef80-3138-11ea-828b-50c99956ea7e.png)

**Comment by Hypnos3** [comment]
OK, I will check if I can enhance the display in any of the next version. I have created a new issue --> #91

**Comment by ozett** [comment]
👍
