### ISSUE TITLE
Input of  Coordinates from Openweather

### ISSUE THREAD

**Issue by vlturner** [rdmtc/node-red-contrib-sun-position#81]
* want to pass openweather LAT and LON into node-red-contrib-sun-position. How can I do this?

payload: object
lon: -120.68
lat: 38.2
city: "San Andreas"
country: "US"
_msgid: "8d406753.79f9c8"

Changed it to this now.

object
payload: object
_msgid: "4192fff8.88887"
Latitude: 38.2
Longitude: -120.68

**Comment by Hypnos3** [comment]
This is currently not possible. the Latitude and Longitude must be added in the config.

I can check if it can be added to the `sun position` and to the `moon position` to also have thin in the incoming message.

**Comment by vlturner** [comment]
Would be awesome. Adding it to a mobile pump and want to tie it the the GPSD module ultimately.

**Comment by Hypnos3** [comment]
It is implemented in 1.0.10, which is currently only a test version. It will be available with the next regular version.

Then it is possible to have `msg.latitude` and `msg.longitude` (or `msg.lat` and `msg.lon`) to override settings in configuration node. The configuration Node still needs to be configured properly.
