### ISSUE TITLE
blind-control: increment invalid if start greater zero?

### ISSUE THREAD

**Issue by ozett** [rdmtc/node-red-contrib-sun-position#82]
the blind-control shows an error on the increment !
if the opening-pos value leaves zero (error starts, if we change from zero to any number) . 
if the opening-value is  0, everything is fine on the increment-input.

i cannot understand why a 1  should be an error on the increment, if my opening value is more than zero. must be a bug!? can you confirm?

![image](https://user-images.githubusercontent.com/5937811/71345393-8a462980-2565-11ea-94c8-591a659a8f73.png)

it there is anything to test, i will do...

**Comment by Hypnos3** [comment]
I must check this. It is a time ago, when I had test this.

**Comment by Hypnos3** [comment]
Will be published with next version.
