### ISSUE TITLE
One Universal timer: do i have to use time-inject and within-time together?

### ISSUE THREAD

**Issue by ozett** [rdmtc/node-red-contrib-sun-position#84]
do you know the gira-homeserver and its universal-timer?
i like to replace it and i am trying to use time-inject node.
with gira timers it is easy to check weekdays or a certain year-date and a time to get an event.

![uzsu](https://user-images.githubusercontent.com/5937811/71349134-7fdc5d80-256e-11ea-9e72-a75c53429c0b.gif)

at the moment it looks that i have to use time-inject and somehow hidden time-format-output to trigger events on certain weekdays. Also in the blind-node there seems no easy selection of events on weekdays or weekends.

![image](https://user-images.githubusercontent.com/5937811/71349375-2d4f7100-256f-11ea-9305-ebc7ae75158b.png)

any hints to build simple flow and trigger events only on MO-TUE,WE at 13:00 and FR on 14:00  every week & one event on 12.12.2019 from 13:00-14:00  ?

maybe the holiday-node? but without time? All nodes have mighty features, but some complicated (for me) to get these single events triggered...

**Comment by ozett** [comment]
maybe you could provide a working example how to set weekdays and workdays automatically (at night/ scheduled interval) into this variable like in the [blind-demo](https://github.com/rdmtc/node-red-contrib-sun-position/blob/HEAD/blind_control.md#example-3---testing-rules-and-overrides)?


![image](https://user-images.githubusercontent.com/5937811/71356905-ef107c80-2583-11ea-8cd6-6cd551ac8e06.png)

maybe more elegant and clearer to have this condition test for days within the specific node (blind/time-inject/time-within?)

**Comment by Hypnos3** [comment]
The weekday/workday can be get with the [node-red-contrib-german-holidays](https://github.com/rdmtc/node-red-contrib-german-holidays) node.

Simply triggered short after midnight.
![image](https://user-images.githubusercontent.com/12692680/71380398-47b93700-25cf-11ea-9cfa-2c2429e942dd.png)

**Comment by ozett** [comment]
Great, 
i will try this work-around.

as  with the blind-node: i would be great  and an elegant solution to have checkboxes for days/month all within a node-itself. maybe there is hope for furter version  🌝

**Comment by Hypnos3** [comment]
It is now implemented that days and month can be selected in inject, clock-timer and bloind control (within time will be follow).

As soon as I have the next version release (beta or full) also (but not yet) available. I close the issue first to keep an overview.

**Comment by ozett** [comment]
i updated to 1.0.1 -> wonderful implementation of days. thanks a lot!
but i missed showing on the universal timer to configure timespans of days.
( in the gif see: -> Tage-> Zeitraum)

i normally used this to set  a one-time  timespan for a  special week or three-days in advance.
(config would be scattered a bit if i would use the holdiday calendar).

maybe you  want to thing of this also as a feature enhancement.
example:

![uszu-day1](https://user-images.githubusercontent.com/5937811/71885356-80622000-313a-11ea-9d27-c13bbe6e5fbd.gif)

**Comment by Hypnos3** [comment]
I will think about it. I have generated a new issur to trak this request --> #92
