### ISSUE TITLE
blind-control: output only on input?

### ISSUE THREAD

**Issue by ozett** [rdmtc/node-red-contrib-sun-position#85]
i went through the readme 3 times:
https://github.com/rdmtc/node-red-contrib-sun-position/blob/HEAD/blind_control.md
great and full of helpful details.

BUT 
a  question arises: do i have to trigger the node-input to get node-output on sun-position changes. or an rule-changes? does the node does not send this on its own, like a timer?

maybe i am wrong, but would it be logical if the node would send out its blind-positions on a regular basis on output2, or always if a condition changes?

at the moment it seems that i have to trigger the calculation every 5? mins, to set the blinds to new position on sun/rule-change. is this correct?

maybe a feature to let the node sends out events on change? or regularly? like a timer?

![image](https://user-images.githubusercontent.com/5937811/71350307-51ac4d00-2571-11ea-9e62-267863dad1c8.png)

**Comment by Hypnos3** [comment]
The current released version needs a trigger. The next version will have auto trigger option.

The first output will send only on change, the second output every time a trigger message arrives on input.

**Comment by ozett** [comment]
but this will still need a trigger-input?
the node will not send from itself , if the sun reaches a certain state? or a rule-time is reached ?

**Comment by Hypnos3** [comment]
Yes currently it needs a trigger input.

**Comment by ozett** [comment]
😞 
plans to change this? maybe as enhancement?

(that makes me use another node as trigger, and it makes me eject messages in 5 min intervals only for triggering...using the blind-node as a timer would be preferred 👍 )

**Comment by Hypnos3** [comment]
Yes, the next version still has an auto trigger option (it is currently in testing).

But there are a lot of circumstances where an external trigger is also needed. For example if any global or flow context changes.

The trigger is also for triggering the calculation of the sun position. This calculation needs lot of resources of smaller systems.

The calculation takes place in the configuration node.  And all nodes with the same configuration node share them.  There is also no recalculation within a short period of time.

I am still trying out which time period is most suitable for less powerful systems.

My productive System is currently a RaspberryPi 2b and I'm trigger the nodes every 10 minutes what seems to be enough, but there are maybe other needs.

Over the Christmas season, I will unfortunately only be able to do a lot of further development.

**Comment by ozett** [comment]
i could test something, if  you like, on my more powerful virtual environment...

maybe a checkbox to activate an inline-trigger/clock within the node is an option?
that way one could stay with only one node, or use the trigger output (minimum very minute?) as a trigger for other flows...

looking forward to see and test the new inline-trigger 👍

**Comment by ozett** [comment]
> The trigger is also for triggering the calculation of the sun position. This calculation needs lot of resources of smaller systems.
> The calculation takes place in the configuration node. And all nodes with the same configuration node share them. There is also no recalculation within a short period of time.

as a 2nd thought: why does the node not behave like the holidays flow? i mean: let the node do the sun-event times calculation in the night, i.e. at 01:00 o clock (or once at any other time) and thand store the eventtime within the node. later on let the node trigger the blinds only on this pre-caclulated rule-times. no more calculations or triggering during the day necessary. only execption re-calculations if there is exeptional need to  trigger the node meanwhile on special input events.

so there is only one calculation time in the night (or a configured time) on small systems, after that there are cached and pre-calcualted trigger times for the whole day wich are stored within the node itself, and the node sends this spare events without the need of repeated input triggering and repeated unnecessary re-calculations. 

what do you think?

**Comment by Hypnos3** [comment]
The current implementation in the next version is that for the rules the next time will calculated and for fixed times this will work. But if any dynamic time will be used (time or offset from incoming message, flow context, global context or environment variable) the time can be dynamically changed and thus needs a recalculation. Another problem is the sun position based calculation.

The next version can be installed over command line. If you are using a Homematic CCU the commands are:
```
# source /usr/local/addons/redmatic/home/.profile
# cd /usr/local/addons/redmatic/var
# npm install --save --no-package-lock --global-style --save-prefix="~" --production node-red-contrib-sun-position@1.0.0-alpha-6
```
For other systems I do not have the command line available, but there needs to be called `npm install node-red-contrib-sun-position@1.0.0-alpha-6` in the node-red installation directory to update the version. A Node-RED Restart is neccesary to take effect. On any installation of any other node it could be happen that the version is switched back to the latest normal version. 

This Version is not feature complete and also not complete tested. But I and some of colleagues of me uses this Version already in productive system and no problems reported.

**Comment by ozett** [comment]
Great information, thanks.
i have no CCU, but will try ```npm install node-red-contrib-sun-position@1.0.0-alpha-6```
do i have to get this from github?

**Comment by ozett** [comment]
GREAT!  😄 

i found a new timer (zweitschaltuhr) in  the beta! 
i will try 👍 

![image](https://user-images.githubusercontent.com/5937811/71483055-49b90b00-2806-11ea-8441-336539dac4f2.png)

**Comment by Hypnos3** [comment]
please test node-red-contrib-sun-position@1.0.0-alpha-8
