### ISSUE TITLE
Time injects node sends message twice

### ISSUE THREAD

**Issue by FordAndii** [rdmtc/node-red-contrib-sun-position#9]
My time inject node is configured to inject a timestamp at 7:01 each day:

![6](https://user-images.githubusercontent.com/48220859/54263150-71d5c700-4570-11e9-8647-477ea964fef0.png)
![7](https://user-images.githubusercontent.com/48220859/54263151-71d5c700-4570-11e9-9adc-e1655dcbe7c6.png)

However, it sends the timestamp twice each day. The two messages are fired directly after each other, within just a few seconds.

**Comment by Hypnos3** [comment]
I have created a node and it was send only once:
![image](https://user-images.githubusercontent.com/12692680/54280960-0b18d380-4599-11e9-9a41-2a25d11516ce.png)

There is maybe some settings in behind which will cause this behaviour.

Could you please select the time-inject node and export this and post it here?

**Comment by FordAndii** [comment]
[{"id":"b55c0664.ad32b8","type":"time-inject","z":"a770a501.0cdd3","name":"7:01","positionConfig":"7a9f37a8.318228","payload":"","payloadType":"date","payloadTimeFormat":"0","payloadOffset":0,"payloadOffsetType":"none","payloadOffsetMultiplier":60000,"topic":"","time":"7:01","timeType":"entered","timeDays":"*","offset":0,"offsetType":"none","offsetMultiplier":60000,"property":"","propertyType":"none","timeAlt":"","timeAltType":"entered","timeAltOffset":0,"timeAltOffsetType":"none","timeAltOffsetMultiplier":60000,"once":false,"onceDelay":0.1,"addPayload1":"","addPayload1Type":"none","addPayload1Value":"","addPayload1ValueType":"date","addPayload1Format":"0","addPayload1Offset":0,"addPayload1OffsetType":"none","addPayload1OffsetMultiplier":60000,"addPayload1Days":"*","addPayload2":"","addPayload2Type":"none","addPayload2Value":"","addPayload2ValueType":"date","addPayload2Format":"0","addPayload2Offset":0,"addPayload2OffsetType":"none","addPayload2OffsetMultiplier":60000,"addPayload2Days":"*","addPayload3":"","addPayload3Type":"none","addPayload3Value":"","addPayload3ValueType":"date","addPayload3Format":"0","addPayload3Offset":0,"addPayload3OffsetType":"none","addPayload3OffsetMultiplier":60000,"addPayload3Days":"*","recalcTime":2,"x":130,"y":980,"wires":[["95080a94.151798","b79c411a.e45d6"]]},{"id":"7a9f37a8.318228","type":"position-config","z":"","name":"S*****","isValide":"true","longitude":"0","latitude":"0","angleType":"deg","timezoneOffset":"1"}]

**Comment by Hypnos3** [comment]
Which Version do you use?

I could not really reproduce your problem with version 0.2.6. What I see that in your export the given days are not setup properly.

This is shown by the red triangle and the error under the node:
![image](https://user-images.githubusercontent.com/12692680/54348631-b4b79d80-4649-11e9-8474-326a2cb42f40.png)

Additional you get the error in the log:
![image](https://user-images.githubusercontent.com/12692680/54348663-cb5df480-4649-11e9-81e4-381195ae5cd8.png)

In the current version, it is somewhat unhappy solved, that an empty days result in that all days are checked in the editor:
![image](https://user-images.githubusercontent.com/12692680/54353971-b71ff480-4655-11e9-8990-c5f7ad4da8b8.png)
I will change this in the next version.

To fix your problem you have simply open the configuration, and close this with "done" (or "fertig") and deploy the changed node.

**Comment by FordAndii** [comment]
I also use version 0.2.6, but the errors which are visible in your screenshots have never been shown to me. I followed your instructions (click "done" again and deployed). Let's see how the node behaves tomorrow morning.

**Comment by FordAndii** [comment]
Now it works. Thank you!
