### ISSUE TITLE
[FR] for rules allow additional date restriction

### ISSUE THREAD

**Issue by Hypnos3** [rdmtc/node-red-contrib-sun-position#92]
i updated to 1.0.1 -> wonderful implementation of days. thanks a lot!
but i missed showing on the universal timer to configure timespans of days.
( in the gif see: -> Tage-> Zeitraum)

i normally used this to set  a one-time  timespan for a  special week or three-days in advance.
(config would be scattered a bit if i would use the holdiday calendar).

maybe you  want to thing of this also as a feature enhancement.
example:

![uszu-day1](https://user-images.githubusercontent.com/5937811/71885356-80622000-313a-11ea-9d27-c13bbe6e5fbd.gif)

_Originally posted by @ozett in https://github.com/rdmtc/node-red-contrib-sun-position/issues/84#issuecomment-571512593_

**Comment by ozett** [comment]
i had also a 2nds thought and from my use of the gira-timer i call tell, that the userexperience is somehow bad to enter timespan. and unlogical.

for the blind-control it seems somehow logical to put timspan in the rules-section.
or likely collect an unrestricted amount of timespans like unrestricted amount of rules.
As i can add as many rules as i like, i could collects more than one timespan section (like on gira).
only an input is missing for dates... somehow... 

it dont have to be right in the rules, but timespans could be made like this pattern..

simple and bad mockup for the idea-collection:

![image](https://user-images.githubusercontent.com/5937811/71923237-deb7ee80-318c-11ea-8543-b54692806cde.png)

**Comment by Hypnos3** [comment]
I have implemented this in `node-red-contrib-sun-position@1.0.6`.

This is a test release and needs to be installed explicit over command line. The function is not completely tested.

**Comment by Hypnos3** [comment]
Implemented in 1.0.11.

For Blind-control and clock timer will be full working with next release.
