### ISSUE TITLE
"Configuration is missing" - newly introduced error

### ISSUE THREAD

**Issue by mKeRix** [rdmtc/node-red-contrib-sun-position#93]
**Describe the bug**
I'm using the time-comp node and am getting an unexpected "Configuration is missing" error since a recent upgrade. I suspect it is related to your work on #74, but couldn't pinpoint the issue myself. I've tried changing the relevant settings around and redeploying, but it always ends up the same. Downgrading to 0.5.4 again fixes the issue.

**To Reproduce**
The node is fed a time in milliseconds (you can replicate this with a simple Inject node) and has the settings as shown in the screenshot below. It is also set to check all rules and has no output.

**Expected behavior**
The node accepts the imo complete settings as they are and routes the message further based on whether the (incoming timestamp == now + 30min) or not.

**Screenshots**
<img width="480" alt="Bildschirmfoto 2020-01-09 um 10 54 10" src="https://user-images.githubusercontent.com/770596/72057957-98b77380-32cf-11ea-9c5b-85bf5885483b.png">

**System information (please complete the following information):**
 - Version: 1.0.1
 - Node-Red Version: 1.0.3
 - Hardware: Hass.io Addon running on Intel NUC

**Comment by Hypnos3** [comment]
Thanks for reporting the problem. I have released a new version 1.0.2 which should fix the problem.

The problem was caused by increased validity checks.
