### ISSUE TITLE
sun-position does not update for new day

### ISSUE THREAD

**Issue by nineclicks** [rdmtc/node-red-contrib-sun-position#98]
**Describe the bug**
The times in the sun-position node only work properly on the day that I deployed. Following days keep the old timestamps, sunInSky remains false all day and all of the values in the times property remain from that first day.

**To Reproduce**
- Add an inject node -> sun-position node -> debug node.
- Deploy and wait a day
- Trigger inject node

**Expected behavior**
Solar event times would be for that day rather than the day the flow was last deployed.

**Screenshots**
Before deploying:
<img width="225" alt="Capture" src="https://user-images.githubusercontent.com/18297675/72688204-c2378280-3ab9-11ea-8caf-4d7aea5f2128.PNG">

After deploying:
<img width="228" alt="Capture2" src="https://user-images.githubusercontent.com/18297675/72688208-c663a000-3ab9-11ea-9ca9-9e985ea96e26.PNG">

**System information (please complete the following information):**
 - Node-Red Version 1.0.3
 - Hassio 0.95.4
 - Hardware RaspberryPi2 b+

**Additional context**

**Comment by Hypnos3** [comment]
In the first test I could not re-create the error. I need some time for more testing.

Has your incomming message a msg.time od msg.ts property?

Because if so, the value of this property is tried to be interpreted as time and then only the times based on this point in time and not the current one are calculated.

**Comment by nineclicks** [comment]
The msg.payload is the current timestamp but there is no msg.time or msg.ts set.

**Comment by Hypnos3** [comment]
I do not see the problem as described.

I triggered the flow with an Inject node yesterday and today and got correct calculated times for the local time of the day.

yesterday (trigger UTC = 2020-01-20T20:03Z - local = 2020-01-20 21:03):
```
payload:
   { ts: 1579550586314,
     lastUpdate: 2020-01-20T20:03:06.314Z,
     latitude: 51.08995,
     longitude: 13.63268,
     angleType: 'deg',
     azimuth: 290.86481568322534,
     altitude: -41.25173588591316,
     altitudeDegrees: -41.25173588591316,
     azimuthDegrees: 290.86481568322534,
     altitudeRadians: -0.7199786133722846,
     azimuthRadians: 1.9349560582889287,
     times:
      { solarNoon:
         { value: 2020-01-20T11:17:23.432Z,
           ts: 1579519043432,
           name: 'solarNoon',
           julian: 2458868.9704100946,
           valid: true,
           pos: 10 },
        nadir:
         { value: 2020-01-20T23:17:23.432Z,
           ts: 1579562243432,
           name: 'nadir',
           julian: 2458869.4704100946,
           valid: true,
           pos: 21 },
        goldenHourDuskStart:
         { value: 2020-01-20T14:39:50.706Z,
           ts: 1579531190706,
           name: 'goldenHourDuskStart',
           elevation: 6,
           julian: 2458869.1110035446,
           valid: true,
           pos: 11 },
```

today (trigger UTC = 2020-01-20T23:10Z - local = 2020-01-21 01:10):
```
  payload:
   { ts: 1579561800014,
     lastUpdate: 2020-01-20T23:10:00.014Z,
     latitude: 51.08995,
     longitude: 13.63268,
     angleType: 'deg',
     azimuth: 356.8224030470443,
     altitude: -59.02681975401525,
     altitudeDegrees: -59.02681975401525,
     azimuthDegrees: 356.8224030470443,
     altitudeRadians: -1.0302123516887955,
     azimuthRadians: 3.086133124459377,
     times:
      { solarNoon:
         { value: 2020-01-21T11:17:41.563Z,
           ts: 1579605461563,
           name: 'solarNoon',
           julian: 2458869.970619951,
           valid: true,
           pos: 10 },
        nadir:
         { value: 2020-01-21T23:17:41.563Z,
           ts: 1579648661563,
           name: 'nadir',
           julian: 2458870.470619951,
           valid: true,
           pos: 21 },
        goldenHourDuskStart:
         { value: 2020-01-21T14:41:47.060Z,
           ts: 1579617707060,
           name: 'goldenHourDuskStart',
           elevation: 6,
           julian: 2458870.11235024,
           valid: true,
           pos: 11 },
```

today (trigger UTC = 2020-01-21T01:05Z - local = 2020-01-21T02:05):
```
  payload:
   { ts: 1579568700002,
     lastUpdate: 2020-01-21T01:05:00.002Z,
     latitude: 51.08995,
     longitude: 13.63268,
     angleType: 'deg',
     azimuth: 44.43478829535718,
     altitude: -52.48893224777559,
     altitudeDegrees: -52.48893224777559,
     azimuthDegrees: 44.43478829535718,
     altitudeRadians: -0.9161046885799121,
     azimuthRadians: -2.3660592954091717,
     times:
      { solarNoon:
         { value: 2020-01-21T11:17:41.563Z,
           ts: 1579605461563,
           name: 'solarNoon',
           julian: 2458869.970619951,
           valid: true,
           pos: 10 },
        nadir:
         { value: 2020-01-21T23:17:41.563Z,
           ts: 1579648661563,
           name: 'nadir',
           julian: 2458870.470619951,
           valid: true,
           pos: 21 },
        goldenHourDuskStart:
         { value: 2020-01-21T14:41:47.060Z,
           ts: 1579617707060,
           name: 'goldenHourDuskStart',
           elevation: 6,
           julian: 2458870.11235024,
           valid: true,
           pos: 11 },
```

Maybe the local time is not set correctly on the computer where node-red is running?

**Comment by nineclicks** [comment]
The date everywhere else in my system seems correct. Even payload.ts is correct.

<img width="300" alt="Screen Shot 2020-01-21 at 5 37 21 PM" src="https://user-images.githubusercontent.com/18297675/72858202-d70c4580-3c74-11ea-82e3-dc9a86d09a08.png">

The only other thing I can think of would be setting the start and end time to see if sunInSky works normally.

<img width="484" alt="Screen Shot 2020-01-21 at 5 42 44 PM" src="https://user-images.githubusercontent.com/18297675/72858442-babcd880-3c75-11ea-87c1-dea4f042a5af.png">

**Comment by Hypnos3** [comment]
My family is currently suffering from the common cold, which is why I am unable to investigate further.  As soon as that is over, I will look at it.  With the next version, for example, I plan to additionally output the real time, which serves as the basis.

**Comment by Hypnos3** [comment]
I have implemented a fix in `node-red-contrib-sun-position@1.0.6`, which maybe fixes this.
This is a test release and needs to be installed explicit over command line.

Maybe you can test this.

**Comment by Hypnos3** [comment]
Please test with version starting from 1.0.11.

**Comment by nineclicks** [comment]
I have updated to 1.0.11 and I will update tomorrow what happens, thanks.

**Comment by nineclicks** [comment]
It is working today, looks good. Thank you for the work!
